<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"caminho_paz");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO',"20 Dezembro 2018 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'>O Caminho para a Paz </Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'>Ajaan Chah</Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>

<p class=Normal><i>Sila</i>, <i>samadhi</i> e <i>pañña</i> são os nomes dados aos diferentes aspectos da prática. Praticar <i>sila</i>, <i>samadhi</i> e <i>pañña</i>, significa que praticamos com nós mesmos. <i>Sila</i> correto existe aqui, <i>samadhi</i> correto existe aqui. Por que? Porque nosso corpo está bem aqui! Temos mãos, temos pernas, bem aqui. Aqui é onde praticamos <i>sila</i>. É fácil descrever a lista de tipos de comportamento errados encontrados nos livros, mas o importante é compreender que o potencial para todos está dentro de cada um. O corpo e a linguagem estão conosco aqui e agora. Praticamos a virtude, o que significa tomar cuidado para evitar as ações inábeis de matar, roubar e má conduta sexual. Por exemplo, no passado podemos ter matado animais ou insetos, ou talvez não tenhamos tomado muito cuidado com a linguagem: linguagem mentirosa significa mentir ou exagerar a verdade; linguagem grosseira significa que estamos constantemente sendo abusivos ou rudes com os outros - "idiota", "escória", e assim por diante; linguagem frívola significa tagarelice sem objetivo, falar de modo estúpido sem propósito ou substância. Nos entregamos a tudo isso - sem restrição! Em suma, manter <i>sila</i> significa vigiar a si mesmo, vigiando as ações e a linguagem.</p>

<p class=Normal>Então, quem será o vigilante? Quem assumirá a responsabilidade pelas ações? Quem é "aquele que sabe" antes de mentir, ofender ou dizer algo frívolo? Contemple isso: quem quer que seja "aquele que sabe" é ele quem deve assumir a responsabilidade por <i>sila</i>. Traga essa atenção para vigiar suas ações e linguagem. Esse conhecimento, essa atenção, é o que usamos para vigiar a prática. Para manter <i>sila</i> usamos aquela parte da mente que direciona as ações e que nos leva a praticar o bem ou o mal. Pegamos o vilão e o transformamos num xerife. Agarre a mente rebelde e discipline-a assumindo a responsabilidade por todas as ações e palavras. Olhe para isso e contemple isso. O Buda nos ensinou a sermos cautelosos com as nossas ações. Quem é o cauteloso?</p>

<p class=Normal>A prática envolve o estabelecimento de <i>sati</i>, atenção plena, "naquele que sabe". "Aquele que sabe" é aquela intenção mental que anteriormente nos motivou a matar seres vivos, roubar a propriedade de outras pessoas, fazer sexo ilícito, mentir, difamar, dizer coisas tolas e frívolas e engajar-se em todos os tipos de comportamento desenfreado. "Aquele que sabe" nos leva a falar. Está dentro da mente. Foque a atenção plena (<i>sati</i>) - mantendo-a sempre na memória - nesse "que sabe". Deixe o saber cuidar da sua prática. Use <i>sati</i>, ou atenção plena, para manter a mente lembrando o momento presente e mantenha a compostura mental desse modo. Faça a mente cuidar de si mesma. Faça bem feito.</p>

<p class=Normal>Se a mente for realmente capaz de cuidar de si mesma, não será tão difícil vigiar a linguagem e as ações, pois estas são supervisionadas pela mente. Em outras palavras, manter <i>sila</i> - cuidar das nossas ações e linguagem - não é uma coisa tão difícil. Mantemos a atenção em todos os momentos e em todas as posturas, seja em pé, caminhando, sentado ou deitado. Antes de realizar qualquer ação, falar, ou se envolver em conversas, estabelecemos primeiro a atenção plena. Devemos ter <i>sati</i>, estar com atenção plena, antes de fazer qualquer coisa. Praticamos assim até sermos fluentes. Praticamos dessa forma para que possamos estar a par com o que estiver acontecendo na mente, até o ponto em que a atenção plena se torna sem esforço e estamos atentos antes de agir, atentos antes de falar. É assim que estabelecemos a atenção plena no coração. É com "aquele que sabe" que cuidamos de nós mesmos. Cuidando da linguagem e das ações, estas se tornam graciosas e agradáveis aos olhos e ouvidos, enquanto permanecemos confortáveis e à vontade com essa contenção. Se praticarmos a atenção plena e a contenção até que isso se torne algo confortável e natural, a mente se tornará firme e resoluta na prática de <i>sila</i> e na prática da contenção. Consistentemente iremos prestar atenção à prática e, assim, alcançaremos a concentração. A característica de estar inabalável na prática da atenção plena e da contenção é chamada <i>samadhi</i>. A mente estará firmemente concentrada nesta prática de <i>sila</i> e contenção. Estar firmemente concentrada na prática de <i>sila</i> significa que há uniformidade e consistência na prática da atenção plena e da contenção. Estas são as características dos fatores externos na prática de <i>samadhi</i>. No entanto, também tem um lado interno mais profundo.</p>

<p class=Normal>Uma vez que a intenção na mente para a prática, bem como <i>sila</i> e <i>samadhi</i>, estiverem firmemente estabelecidos, seremos capazes de investigar e refletir sobre o que é benéfico e prejudicial - perguntando a nós mesmos: "Isto está certo?" ... "Isso está errado?" enquanto experimentamos diferentes objetos mentais. Quando a mente faz contato com diferentes visões, sons, aromas, sabores, sensações táteis ou idéias, "aquele que sabe" surgirá e estabelecerá a consciência de gosto ou não gosto, felicidade ou sofrimento, e os diferentes tipos de objetos mentais que experimentamos. Veremos com clareza e veremos muitas coisas diferentes. Se estivermos atentos, veremos os diferentes objetos que surgem na mente e a reação que ocorre ao experimentá-los. "Aquele que sabe" irá automaticamente tomá-los como objetos de contemplação. Uma vez que a mente esteja vigilante e a atenção plena esteja firmemente estabelecida, notaremos todas as reações expressas através do corpo, da linguagem, ou da mente, na medida em que os objetos mentais forem experimentados. <i>Pañña</i> é o aspecto da mente que identifica e seleciona o bom do ruim, o certo do errado, dentre todos os objetos mentais que fazem parte do campo da consciência. Isto é <i>pañña</i> em seus estágios iniciais que amadurece como resultado da prática. </p>

<p class=Normal>Isso significa que começamos a nos apegar ao que é bom ou saudável. Tememos quaisquer defeitos ou falhas na mente - ansiosos que possam prejudicar nosso <i>samadhi</i>. Ao mesmo tempo, começamos a ser diligentes e trabalhar duro, bem como amar e alimentar a prática. Continuamos praticando assim tanto quanto possível, até que possamos chegar ao ponto em que estaremos constantemente julgando e criticando todos aqueles que encontramos, onde quer que formos. Estaremos constantemente reagindo com atração ou aversão ao mundo ao nosso redor, tornando-nos cheios de todos os tipos de incerteza e continuamente nos apegando a visões do modo correto e incorreto de praticar. É como se estivéssemos obcecados com a prática. Mas não precisamos nos preocupar com isso ainda - nesse ponto é melhor praticar muito do que pouco. Praticamos muito e nos dedicamos a cuidar do corpo, da linguagem e da mente. Nunca faremos demasiado. A prática da atenção plena e da contenção com o corpo, a linguagem, e a mente, e a distinção consistente entre o certo e o errado é o que mantemos como objeto na mente. Nos tornamos concentrados dessa maneira e, estando conectados firmes e inabaláveis a esse modo de prática, significa que a mente realmente se torna <i>sila</i>, <i>samadhi</i> e <i>pañña</i> - as características da prática descritas nos ensinamentos.</p>

<p class=Normal>À medida que continuamos a desenvolver e manter a prática, essas diferentes características e qualidades são aperfeiçoadas juntas na mente. No entanto, praticar <i>sila</i>, <i>samadhi</i> e <i>pañña</i> neste nível ainda não é suficiente para produzir os fatores de <i>jhana</i> - a prática ainda é muito grosseira. Ainda assim, a mente já está bastante refinada - no lado refinado do grosseiro! Para uma pessoa comum, não iluminada, que não tenha cuidado da mente ou praticado muita atenção plena e meditação, somente esse tanto já é algo bastante refinado. Neste nível, podemos sentir uma sensação de satisfação ao sermos capazes de praticar em toda a dimensão completa da nossa habilidade. Isso é algo que veremos por nós mesmos; algo que deve ser experimentado pela mente do próprio praticante.</p>

<p class=Normal>Sendo assim, significa que o praticante já está no caminho, ou seja, praticando <i>sila</i>, <i>samadhi</i> e <i>pañña</i>. Estes devem ser praticados em conjunto, pois se algum deles estiver faltando, a prática não se desenvolverá corretamente. Quanto mais <i>sila</i> melhora, mais firme se torna a mente. Quanto mais firme for a mente, mais confiante se torna <i>pañña</i> e assim por diante ... cada parte da prática apoiando e aprimorando todas as outras. Conforme aprofundamos e refinamos a prática, <i>sila</i>, <i>samadhi</i> e <i>pañña</i> irão amadurecer juntos no mesmo ponto -  são refinados a partir da mesma matéria-prima. Em outras palavras, o Caminho tem um começo grosseiro, mas, como resultado do treinamento e refinamento da mente através da meditação e da reflexão, torna-se cada vez mais sutil. À medida que a mente se torna mais refinada, a prática da atenção plena torna-se mais concentrada, concentrando-se em uma área cada vez mais limitada. A prática realmente se torna mais fácil à medida que a mente se volta mais e mais para se concentrar em si mesma. Não cometemos mais grandes erros. Agora, quando a mente for afetada por um assunto específico, surgirão dúvidas - por exemplo, se agir ou falar de um certo modo será certo ou errado - simplesmente continuamos a conter a proliferação mental e, intensificando o esforço na prática, continuamos dirigindo a atenção cada vez mais fundo dentro da mente. A prática de <i>samadhi</i> se tornará progressivamente mais firme e mais concentrada. A prática de <i>pañña</i> é aprimorada para que possamos ver as coisas com mais clareza e com maior facilidade.</p>

<p class=Normal>O resultado final é que somos claramente capazes de ver a mente e seus objetos, sem ter que fazer qualquer distinção entre a mente, o corpo ou a linguagem. Conforme continuamos dirigindo a atenção para dentro e a refletir sobre o Dhamma, a faculdade da sabedoria gradualmente amadurece, e eventualmente ficamos contemplando a mente e os objetos mentais - o que significa que começamos a sentir o corpo como imaterial. Através do insight, não estaremos mais tateando ou incertos na compreensão do corpo e do modo como ele é. A mente experimenta as características físicas do corpo como objetos imateriais que entram em contato com a mente. Em última análise, estamos contemplando apenas a mente e os objetos mentais - aqueles objetos que entram em contato com a consciência. Agora, examinando a verdadeira natureza da mente, podemos observar que, em seu estado natural, não há preocupações ou problemas que prevalecem. É como um pedaço de pano ou uma bandeira amarrada ao final de um poste. Enquanto estiver por conta própria e sem perturbações, nada acontecerá.</p>

<p class=Normal>No seu estado natural não existe na mente amor ou ódio, nem a busca em culpar outras pessoas. A mente é independente, existindo em um estado de pureza que é verdadeiramente claro, radiante e imaculado. Em seu estado puro, a mente é pacífica, sem felicidade ou sofrimento - na verdade, sem experimentar qualquer tipo de sensação (<i>vedana</i>). Esse é o verdadeiro estado da mente. Portanto, o propósito da prática é a busca interior, procurando e investigando até alcançar a mente original. A mente original também é conhecida como a mente pura. A mente pura é a mente sem apegos, sem ser afetada por objetos mentais. Em outras palavras, a mente não persegue os diferentes tipos de objetos mentais agradáveis ou desagradáveis. Em vez disso, a mente está em um estado de contínua vigília e conhecimento - completamente consciente de tudo o que está sendo experimentado. Quando a mente está nesse estado nenhum objeto mental agradável ou desagradável que seja experimentado será capaz de perturbá-la. A mente não "se torna" nada. Em outras palavras, nada pode abalá-la. A mente se conhece como pura. Desenvolveu a sua própria independência verdadeira; alcançou seu estado original. Como ser capaz de fazer com que esse estado original surja? Através da faculdade da atenção plena, refletindo e vendo que todas as coisas são meras condições surgindo da influência dos elementos, sem que nenhum indivíduo as esteja controlando. Assim é como ocorre com a felicidade e o sofrimento que experimentamos. Quando esses estados mentais surgem, eles são apenas "felicidade" e "sofrimento". Não há dono da felicidade. A mente não é a proprietária do sofrimento - os estados mentais não pertencem à mente. Veja por você mesmo. Na realidade, esses não são assuntos da mente, são separados e distintos. Felicidade é apenas o estado de felicidade; o sofrimento é apenas o estado de sofrimento. Somos meramente os conhecedores desses estados. No passado, porque as raízes da cobiça, da raiva e da delusão existiam na mente, sempre que o mais trivial objeto mental, agradável ou desagradável, fosse notado, a mente reagiria imediatamente - nós o tomaríamos experimentando a felicidade ou o sofrimento. Continuamente estaríamos nos entregando a estados de felicidade ou sofrimento. Assim é como ocorre enquanto a mente não se conhece - enquanto não for clara e iluminada. A mente que não está livre é influenciada por quaisquer objetos mentais que experimenta. Em outras palavras, não tem refúgio, incapaz de verdadeiramente depender de si mesma. Recebemos uma impressão mental agradável e ficamos de bom humor. A mente esquece de si mesma.</p>

<p class=Normal>Em contraste, a mente original está além do bem e do mal. Essa é a natureza original da mente. Se nos sentimos felizes por experimentar um objeto mental agradável, isso é uma delusão. Se nos sentimos infelizes por experimentar um objeto mental desagradável, isso é uma delusão. Objetos mentais desagradáveis fazem com que sofremos e os agradáveis nos fazem felizes - esse é o mundo. Objetos mentais vêm com o mundo. Objetos mentais são o mundo, dando origem à felicidade e sofrimento, bem e mal, e tudo o que está sujeito à impermanência e incerteza. Quando alguém se separa da mente original, tudo se torna incerto - apenas há o nascimento e a morte sem fim, a incerteza e a apreensão, o sofrimento e a dificuldade, sem nenhuma forma de deter ou cessar esse ciclo, o ciclo interminável de renascimentos.</p>

<p class=Normal><i>Samadhi</i> significa uma mente firmemente concentrada, e quanto mais praticamos, mais firme a mente se torna. Quanto mais firmemente a mente está concentrada, mais resoluta na prática ela se torna. Quanto mais você contemplar, mais confiante ficará. A mente se torna verdadeiramente estável - a ponto de não poder ser influenciada por nada. Estamos absolutamente confiantes de que nenhum único objeto mental tem o poder de nos abalar. Objetos mentais são objetos mentais; a mente é a mente. A mente experimenta estados mentais bons e ruins, felicidade e sofrimento, porque é deludida pelos objetos mentais. Se não for deludida pelos objetos mentais, não há sofrimento. A mente não-deludida não pode ser abalada. Simplesmente falando, esse estado que surgiu é a própria mente. Se contemplamos de acordo com a verdade o modo como as coisas são, podemos ver que existe apenas um caminho sendo nosso dever segui-lo. Se nos apegamos à felicidade, estaremos fora do caminho - porque se apegar à felicidade causará sofrimento. Se nos apegamos à tristeza, pode ser a causa para o surgimento do sofrimento. Entendemos isso -  já estamos com a atenção plena e com o entendimento correto - mas, ao mesmo tempo, ainda não somos capazes de abandonar completamente os nossos apegos.</p>

<p class=Normal>Então, qual é a maneira correta de praticar? Temos que adotar o caminho do meio, o que significa acompanhar os vários estados mentais de felicidade e sofrimento, enquanto que ao mesmo tempo mantendo-os à distância.</p>

<p class=Normal>Essa é a maneira correta de praticar - mantemos a atenção plena e a plena consciência, mesmo se ainda não formos capazes de abrir mão. Esse é o caminho correto, pois sempre que a mente se apega a estados de felicidade ou sofrimento, a consciência desse apego está sempre presente. Isso significa que quando a mente se apega a estados de felicidade, não elogiamos nem damos valor a isso, e sempre que a mente se apega a estados de sofrimento, não criticamos. Desta forma podemos realmente observar a mente tal como ela é. A felicidade não é correta, o sofrimento não é correto. Há o entendimento de que nenhum desses estados é o caminho correto. Podemos ser incapazes de abandoná-los, mas podemos estar com a atenção plena e a plena consciência. Com a atenção plena estabelecida, não atribuímos indevido valor à felicidade ou ao sofrimento. Não damos importância a nenhuma dessas duas direções que a mente pode tomar, sem restar qualquer dúvida. Sabemos que seguir qualquer um desses caminhos não é o caminho de prática correto, então, em todos os momentos, consideramos o meio-termo da equanimidade como o objeto da mente. Quando praticamos até o ponto no qual a mente vai além da felicidade e do sofrimento, a equanimidade necessariamente surge como o caminho a seguir. Devemos gradualmente segui-la, pouco a pouco - o coração sabendo o caminho para além das contaminações, mas, sem estarmos prontos para finalmente transcendê-las.</p>

<p class=Normal>Sempre que a felicidade surge e a mente se apega, temos que contemplar essa felicidade, e sempre que a mente se apega ao sofrimento, temos que contemplar esse sofrimento. Eventualmente, a mente alcançará um estágio no qual estará plenamente consciente da felicidade e do sofrimento. Nesse ponto será capaz de deixar de lado a felicidade e o sofrimento, o prazer e a dor, e deixar de lado tudo o que é o mundo e assim nos tornamos o "conhecedor dos mundos". Uma vez que a mente - "aquele que sabe" - possa abrir mão, poderá se estabelecer nesse ponto.</p>

<p class=Normal>É nesse ponto que a prática se torna realmente interessante. Onde quer que haja apego na mente, continuamos insistindo naquele ponto, sem desistir. Se há apego à felicidade, continuamos insistindo, não deixando a mente ser levada por esse estado. Se a mente se apega ao sofrimento, nos agarramos a isso, realmente grudamos e contemplamos imediatamente. Mesmo que a mente esteja presa em um estado mental insalubre, sabemos que é prejudicial e que a mente não é negligente. É como pisar em espinhos: é claro que não procuramos pisar em espinhos, tentamos evitá-los, mas mesmo assim às vezes pisamos em um. Mesmo que saibamos disso, somos incapazes de evitar pisar naqueles 'espinhos'. A mente ainda segue vários estados de felicidade e sofrimento, mas não se entrega completamente. Sustentamos um esforço contínuo para destruir qualquer apego na mente - para destruir e eliminar tudo aquilo que é o mundo da mente.</p>

<p class=Normal>Algumas pessoas querem pacificar a mente mas não sabem o que é realmente a verdadeira paz. Não conhecem a mente pacífica! Existem dois tipos de paz - a paz que vem através de <i>samadhi</i> e a paz que vem através de <i>pañña</i>. A mente que está em paz através de <i>samadhi</i> ainda está deludida. A paz que vem através da prática de <i>samadhi</i> depende da mente estar separada dos objetos mentais. Quando não está experimentando nenhum objeto mental, então há calma e consequentemente a pessoa se apega à felicidade que vem com essa calma. No entanto, sempre que há impacto através dos sentidos, a mente cede imediatamente. Tem medo dos objetos mentais. Tem medo da felicidade e do sofrimento; tem medo de elogios e críticas; medo de formas, sons, aromas e gostos.</p>

<p class=Normal>Quem experimenta a  paz apenas através de <i>samadhi</i> tem medo de tudo e não quer se envolver com ninguém ou nenhuma coisa. As pessoas que praticam <i>samadhi</i> desse modo apenas querem ficar isoladas em uma caverna em algum lugar, onde possam experimentar a felicidade de <i>samadhi</i> sem ter que sair. Onde quer que haja um lugar pacífico, elas se esgueiram e se escondem. Esse tipo de <i>samadhi</i> envolve muito sofrimento - as pessoas acham difícil deixar esse estado e conviver com outras pessoas. Elas não querem ver formas ou ouvir sons, não querem experimentar nada! Elas têm que viver em algum lugar calmo e especialmente reservado, onde ninguém venha e perturbe com conversas. Necessitam um ambiente realmente pacífico.</p>

<p class=Normal>Esse tipo de paz não produz os resultados esperados. O Buda não ensinou a praticar <i>samadhi</i> com delusão. Se alguém pratica assim, então pare. Se a mente alcançou a tranquilidade, use-a como base para a contemplação. Contemple a paz da concentração em si e use-a para conectar a mente e refletir sobre os diferentes objetos mentais que a mente experimenta. Contemple as três características de <i>anicca</i> (impermanência), <i>dukkha</i> (sofrimento) e <i>anatta</i> (não-eu). Reflita sobre o mundo todo. Quando tiver contemplado suficientemente, está tudo bem em restabelecer a calma de <i>samadhi</i>. Pode reentrar em <i>samadhi</i> através da meditação sentada e depois, com calma restabelecida, continuar com a contemplação. À medida que ganhamos conhecimento, usamos para combater as contaminações, para treinar a mente.</p>

<p class=Normal>A paz que surge através de <i>pañña</i> é distinta, porque quando a mente se retira do estado de tranquilidade, a presença de <i>pañña</i> afasta o medo das formas, sons, aromas, sabores, sensações táteis e idéias. Significa que, logo que ocorra o contato sensorial, a mente imediatamente tem consciência do objeto mental. Assim que houver um contato num dos meios dos sentidos, o deixamos de lado - a atenção plena é apurada o suficiente para imediatamente abrir mão. Essa é a paz que surge através de <i>pañña</i>.

<p class=Normal>Quando praticamos com a mente dessa maneira, a mente se torna consideravelmente mais refinada do que quando apenas desenvolvemos <i>samadhi</i>. A mente se torna muito poderosa e não tenta mais fugir. Com tal energia nos tornamos destemidos. No passado tínhamos medo de experimentar qualquer coisa, mas agora conhecemos os objetos mentais tal como são e assim não há mais medo. Conhecemos nossa própria força mental e não temos medo. Quando vemos algo, contemplamos. Quando ouvimos um som, contemplamos. Nos tornamos proficientes na contemplação dos objetos mentais. Seja o que for, podemos abrir mão de tudo. Vemos claramente a felicidade e abrimos mão. Vemos claramente o sofrimento e abrimos mão. Onde quer sejam vistos, naquele exato momento abrimos mão. Todos os objetos mentais perdem seu valor e não são mais capazes de nos influenciar. Quando essas características surgem na mente do praticante, é apropriado mudar o nome da prática para <i>vipassana</i>: conhecimento claro de acordo com a verdade. É disso que se trata - conhecimento de acordo com a verdade sobre como as coisas são. Esta é a paz no mais alto nível, a paz de <i>vipassana</i>.</p>

<p class=Normal>Desenvolver <i>samadhi</i> para que possamos simplesmente ficar sentados e cultivar o apego por estados mentais felizes não é o verdadeiro propósito da prática. Devemos evitar isso. O Buda disse que devemos lutar essa guerra, não apenas nos escondermos em uma trincheira tentando evitar as balas do inimigo. Quando é hora de lutar, realmente temos que sair com armas em punho. Eventualmente temos que sair dessa trincheira. Não podemos ficar ali dormindo quando a hora é de lutar. Assim é a prática. Não podemos permitir que a mente apenas se esconda, encolhendo-se nas sombras.</p>

<p class=Normal>Descrevi um esboço da prática. Você, como todos praticantes, deve evitar ser pego em dúvidas. Não duvide do caminho da prática. Quando há felicidade, observe a felicidade. Quando houver sofrimento, observe o sofrimento. Tendo estabelecido a atenção plena, faça o esforço para destruir ambos. Abra a mão, jogue-os de lado. Conheça o objeto da mente e continue abrindo mão. Se quiser fazer meditação sentada ou andando, isso não importa. Se continuar pensando, não importa. O importante é manter a atenção plena, momento a momento. Se estiver realmente aprisionado à proliferação mental, junte tudo isso e o considere como um todo, rompendo-o desde o início, dizendo: "Todos esses meus pensamentos, idéias e fantasias são simplesmente proliferação mental e nada mais. É tudo <i>anicca</i>, <i>dukkha</i> e <i>anatta</i>. Nada disso é seguro de modo algum." 

<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>


<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>
