<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"budismo_ciencia");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO',"15 Junho 2013 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'> Budismo e Ciência </Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'>Ajaan Brahmavamso</Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>

<p class=Normal>Faz algum tempo, fui convidado pelo Observatório de West Perth como parte das comemorações na Austrália Ocidental (WA) do Centenário da Federação. Os grupos de jovens de WA organizaram todos os eventos. Um dos eventos que eles apresentaram foi intitulado "Nosso Lugar no Espaço". A idéia era tentar descobrir se o futuro seguiria a ciência ou se seguiria a religião. Eles queriam ver como essas duas, assim chamadas abordagens contraditórias à vida, iriam se dar no futuro. Assim eles convidaram representantes de um par de religiões. Eu representei os budistas, e um professor de uma escola cristã de prestígio representou os cristãos. O astrônomo do estado e um jovem da Universidade de WA, que estava prestes a obter um doutorado em física, também faziam parte do painel, representando Astronomia e Física. O que eles não sabiam era que antes de me tornar monge eu tinha sido um físico teórico. Então, eu sabia o que os Budistas sabem e eu também sabia o que eles sabiam. Foi um pouco injusto, mas muito divertido. Foi bem divertido falar com o público sobre o Budismo, religião e ciência, e como eles se unem. Há perigos na religião e na ciência, mas ambas podem ser usadas para ajudar as pessoas a encontrarem um caminho nas suas vidas de um modo sábio, compassivo e eficaz.</a>

<p class=Normal><b>O Fim do Universo</b></a>

<p class=Normal>Comecei explicando algumas coisas sobre o Budismo que muitas pessoas não sabem. O Budismo é tão extenso que há ainda muitas coisas que as pessoas no Ocidente não sabem sobre esta grande religião, especialmente acerca das antigas escrituras, os <i>Suttas</i>. Por exemplo, você sabe quem foi o primeiro homem no espaço? Não, certamente não foi Yuri Gagarin. Foi o Venerável Rohitassa! (<a href="../sutta/ANIV.45.php">AN IV.45</a>)</p>

<p class=Normal>Acho que todos sabem que se a meditação for realmente bem sucedida, é possível levitar. Um dos <i>Suttas</i> conta a história de um eremita que vivia sozinho na floresta. Ele desenvolveu a sua meditação e aprendeu a elevar-se no ar e voar. Este eremita em particular não era apenas um levitador comum, era um dos melhores levitadores que já existiu. Com ele a levitação alcançou novas alturas! Visto que ele era capaz de ser muito rápido, capaz de ser mais rápido do que uma flecha, ele decidiu tentar descobrir onde o universo acabava. Ele voou por muitos, muitos, muitos anos, mas sem conseguir encontrar o fim do universo. Ele foi além dos sistemas solares para o espaço profundo usando o poder da mente. Muitas vezes as pessoas dizem que isso é apenas uma crença. Não é real. Mas depois vou mencionar alguns fatos que mostram que isso provavelmente era real e certamente possível. Ele prosseguiu por muitas dezenas de anos, e morreu no caminho, sem nunca encontrar o fim do universo.</p>

<p class=Normal>Renascendo em um dos mundos celestiais o Venerável Rohitassa foi até o Buda e lhe contou a história de sua vida anterior. Que, como um eremita, ele levitou e voou por um tempo sem fim, morrendo na viagem, sem chegar ao fim do cosmos. Ele não foi o primeiro cosmonauta ou astronauta, ele foi o primeiro mongenauta! O Buda o repreendeu, dizendo que essa não é a maneira de encontrar o fim do universo. Em vez disso, disse o Buda enfaticamente que o início e o fim do universo só pode ser encontrado através da investigação interior. Essa é a resposta a uma das perguntas que as pessoas muitas vezes fazem aos Budistas: "Quem os Budistas acreditam criou este universo?" Um cientista reformularia essa mesma pergunta, "Qual é a origem do universo?" A resposta é que o início e o fim do universo encontram-se dentro do nosso próprio corpo e mente. Você é o criador!</p>

<p class=Normal><b>Relembrando Vidas Passadas</b></p>

<p class=Normal>O Budismo está fundamentado na meditação, e a meditação pode revelar muitas, muitas coisas, especialmente memórias profundas do passado. Monges, monjas, e meditadores comuns, podem alcançar tais meditações profundas de modo que não possam apenas levitar, mas também possam se lembrar de vidas passadas! Muitas pessoas são realmente capazes de fazer isso. Quando alguém sai de uma meditação profunda há uma energia incrível. Depois disso, a pessoa não é capaz de dormir, nem será capaz de assistir TV, porque a mente vai estar muito cheia de alegria e felicidade. Além disso, a mente fica tão poderosa que podemos lhe fazer sugestões, sugestões que normalmente não seríamos capazes de cumprir. Mas com o poder da meditação profunda, é possível cumprir as sugestões. Eu realmente tenho ensinado para as pessoas essa meditação especial em retiros de meditação, porque em retiros de meditação algumas pessoas conseguem resultados profundos. Algumas vezes elas se lembram de memórias de quando eram bebes, e depois de estar no ventre da mãe. Se tiverem sorte elas se recordam de lembranças de quando eram uma pessoa muito velha, ou seja, as memórias de uma vida passada! Uma das coisas importantes com relação às memórias de vidas passadas é que elas são muito reais para a pessoa que as experimenta. É como se a pessoa estivesse lá vivenciando. Quem já teve uma experiência dessas não tem nenhuma dúvida com relação a vidas passadas. Deixa de ser uma teoria. Tais lembranças são como lembrar onde estivemos hoje no café da manhã. Não há dúvidas que era você tomando o café da manhã. Não é imaginação. Com a mesma clareza, ou clareza ainda maior, você lembra que aquela pessoa muito velha era você, só que não era há algumas horas, foi há muitas décadas atrás. Era uma época diferente, um corpo diferente e uma vida diferente. Agora, se as pessoas podem fazer isso em retiros de meditação de nove dias, imagine o que pode ser feito se alguém é um monge ou monja, que não medita apenas durante um fim de semana, ou durante nove dias, mas 9 anos, 29, 39 , ou 59 anos. Imagine o quanto de energia pode ser gerada na meditação. Agora imagine quanto mais poder pode ser gerado se alguém é um Buda com uma mente iluminada.</p>

<p class=Normal>Agora vocês já sabem o que devem fazer para descobrir por si mesmos se vocês já viveram antes. Meditar. Não me refiro apenas a meditar para se livrar do estresse e para se acalmar. Quero dizer realmente meditar, profundamente. Medite para experimentar aquilo que chamamos os <i>jhanas</i>. Esses são estados de absorção profundos, em que o corpo desaparece. Não há sensações. Você não consegue ver. Você não consegue ouvir. Você está absolutamente no interior da mente. Não há pensamentos, mas você está perfeitamente consciente. Você está em êxtase. O método, as instruções para essa experiência, estão muito claramente definidas. No meu livro <a href="../livros/meditacao.pdf">O Método Básico de Meditação</a> todos os passos estão descritos. Siga-os, e invista os recursos necessários para ter essa experiência não apenas num retiro de fim de semana, mas em muitos retiros de fim de semana, e em alguns casos durante muitos anos de meditação. Se quiserem seguir o "método científico", vocês têm que experimentar os <i>jhanas</i>. E então, depois de sair desse estado, você irá se perguntar, "Qual é a minha lembrança mais antiga?" Você pode continuar regredindo na sua mente, e, eventualmente, você irá se lembrar. Você vai ver por si mesmo a experiência de vidas passadas. Então você saberá. Sim, é verdade! Você mesmo teve a experiência.</p>

<p class=Normal>O Buda disse que lembrava de vidas passadas, muitas vidas passadas, muitos éons de vidas passadas. Ele disse especificamente que se lembrava 91 éons. Isto é, 90 big bangs, o tempo antes e o tempo depois, intervalos de tempo enormes. Por isso o Buda disse que não era apenas um universo, mas muitos universos. Nós não estamos falando de universos paralelos, como alguns cientistas dizem. Estamos falando de universos seqüenciais, aquilo que o Buda chamou <i>sanvattati vivattati</i>. Isso é pali, significando a expansão do universo e a sua contração, começos e fins.</p>

<p class=Normal>Os próprios <i>Suttas</i> oferecem uma medição para a vida útil de um universo. Quando eu era um físico teórico, minhas áreas de atuação eram o muito pequeno e o muito grande,  a física das partículas fundamentais e a astrofísica. Esses eram os dois aspectos que eu mais gostava, o grande e o pequeno. Então, eu sabia o que significava a idade de um universo e o que seria o "big bang". A idade de um universo, a última vez que vi nas publicações, estava por volta de 17 mil milhões de anos. Os <i>Suttas</i> Budistas dizem que cerca de 37 mil milhões de anos é um ciclo completo. Quando eu comentei isso com um astrônomo, ele disse que sim, que a estimativa estava dentro das possibilidades, seria aceitável. A pessoa que organizou o seminário "Nosso Lugar no Espaço" fez uma piada sobre o fato de que cem ou duzentos anos atrás, o cristianismo disse que o universo tinha cerca de sete mil anos de idade. Esta estimativa com certeza não é aceitável, a Budista é!</p>

<p class=Normal>É notável que há 25 séculos houve uma cosmologia no Budismo que não entra em conflito com a física moderna. Mesmo aquilo que os astrônomos chamam de galáxias, o Buda chamava de sistemas de rodas. Se algum de vocês já viu uma galáxia, saberá que existem dois tipos de galáxia. Em primeiro lugar, há a galáxia espiral. A Via Láctea é um dessas. Vocês já viram uma galáxia espiral? É como uma roda! O outro tipo é o aglomerado globular, que se parece com uma roda com um grande cubo no meio. 'Rodas' é uma forma muito precisa de descrever galáxias. Isto foi explicado por alguém 25 séculos atrás, quando eles não tinham nem telescópios! Eles não precisavam de telescópios, pois poderiam ver por si mesmos!</p>

<p class=Normal>Há muitas coisas interessantes nos <i>Suttas</i> antigos, mesmo para aqueles entre vocês que gostam de coisas estranhas. Algumas vezes as pessoas fazem esta pergunta, "os Budistas acreditam em seres extra terrestres, em alienígenas? Se um alienígena pousasse aqui isso perturbaria o próprio fundamento do Budismo?" Quando estava lendo esses <i>Suttas</i> antigos, eu realmente encontrei uma referência aos alienígenas! É apenas um sutta muito pequeno, que diz haver outros sistemas cósmicos, com outros sóis, outros planetas, e outros seres. Isso é extraído diretamente do Anguttara Nikaya. (AN X.29)</p>

<p class=Normal><b>O Fantasma na Máquina</b></p>

<p class=Normal>Durante o seminário no Observatório em West Perth, alguém da platéia levantou a mão e perguntou: "Por que é que quando olho através de um telescópio sinto que a minha religião é questionada?" Ela era católica. Ela explicou que sentiu medo ao olhar através de um telescópio, porque o que ela viu não concordava com o que lera na Bíblia. Como Budista você não precisa ter medo. Eu tomei essa questão e a dirigi para os cientistas, perguntando: "E se você olhasse através da extremidade oposta do telescópio para investigar quem está olhando? Acho que vocês, cientistas, ficariam com medo. Vocês teriam medo de virar o telescópio para dentro e olharem para si mesmos, e perguntarem quem está olhando para tudo isso?" Parte do problema com a ciência é que tudo está 'lá fora'. É sempre uma pessoa que olha através do telescópio, olhando para o aparelho, mas nunca refletindo de volta para ver quem está realmente olhando para tudo isso. Quem está fazendo isso?</p>

<p class=Normal>Quando a discussão estava começando a ficar um pouco chata, resolvi agitar o astrônomo, conversando sobre a vida. Qualquer cientista saberia que a mecânica quântica, ou a teoria quântica, descreve o mundo como composto de funções de onda. A função de onda especifica a probabilidade de um evento observável. No entanto, quando é envolvida a vida, quando uma observação é feita, a função de onda colapsa e a realidade como conhecemos  acontece. Tem que haver a observação, uma vida, para que isso aconteça. A teoria quântica necessita um observador, uma vida, para dar sentido às equações. Após a revolução da física quântica, um universo objetivo, independente da vida, perdeu o sentido.</p>

<p class=Normal>Outra lei fundamental da física é chamada a Segunda Lei da Termodinâmica, que diz que a entropia sempre aumenta. Em outras palavras, a vida fica mais desordenado, ainda mais caótica. No entanto, recentemente, alguém ganhou o Prêmio Nobel por provar uma exceção, que, quando há um sistema fechado que inclui a vida, a entropia diminui! A vida dá ordem ao caos, refutando a Segunda Lei da Termodinâmica. Por causa da vida temos organização em vez de desordem. O universo é um sistema fechado e nele há vida. É por isso que há organização.</p>

<p class=Normal>Quando eu estava na universidade, a vida era o que os físicos chamavam, o "fantasma na máquina". O "fantasma na máquina" é o que bagunça todas as teorias objetivas. Este fantasma tem assustado muitos cientistas!</p>

<p class=Normal><b>Seguindo as Crenças às Cegas</b></p>

<p class=Normal>Esse método que nas universidades, nos laboratórios, e nos hospitais, tomamos como ciência, muitas vezes sofre da mesma enfermidade que o dogmatismo religioso. Vocês sabem como é o dogmatismo religioso. Temos uma crença e se ela se encaixa com a prática ou não, se é útil ou não, se conduz à felicidade das pessoas, à harmonia e à paz no mundo ou não, nós a seguimos apenas porque é a nossa crença. Mas seguir crenças cegamente, dogmaticamente, é apenas uma receita para a violência e o sofrimento.</p>

<p class=Normal>Uma das coisas bonitas sobre o Budismo que me encorajaram a me tornar um Budista quando eu era jovem, e que até agora me mantém como um Budista, é que o questionamento é sempre incentivado. Você não precisa acreditar. Em um dos textos antigos, o Buda deu um ensinamento para um dos seus monges principais, o venerável Sariputta. Depois de dar o ensinamento, o Buda perguntou: "Sariputta, você acredita nisso que ensinei?" Sariputta, sem qualquer hesitação, disse: "Não, eu não acredito nisso, porque eu não experimentei isso ainda". O Buda disse: "Muito bem! Muito bem! Muito bem!" Essa é a atitude que deve ser  incentivada em todos os discípulos, seja da religião ou da ciência. Não acreditar, mas manter uma mente aberta, até ter a verdadeira experiência. Esta atitude vai contra o dogmatismo, é contrária ao fundamentalismo, que não vemos apenas na religião, mas que também vemos na ciência.</p>

<p class=Normal>"A eminência de um grande cientista", diz o velho ditado, "é medida por quanto tempo ele obstrui o progresso no seu campo."</p>

<p class=Normal>O mais famoso cientista, quão mais proeminente seja, mais as suas opiniões são tidas como verdade do evangelho. Sua fama impede que outras pessoas o desafiem, retardando chegar em uma "verdade" melhor. No Budismo, quando você encontra uma verdade melhor, use-a de uma vez.</p>

<p class=Normal><b>O Problema com o Dogmatismo</b></p>

<p class=Normal>Há uma história antiga, da época do Buda, sobre dois amigos que foram à procura de um tesouro em uma cidade que tinha sido abandonada (<a href="../sutta/DN23.php#T29">DN 23.29</a>). Primeiro eles encontraram algum cânhamo e decidiram fazer dois feixes de cânhamo e levá-los embora. Eles seriam capazes de vendê-lo quando voltassem para casa. Logo depois de terem feito estes grandes feixes de cânhamo eles se depararam com tecido feito de cânhamo. Um dos homens disse: "Para que preciso de cânhamo? O tecido é melhor". O outro homem disse: "Não, isto já está bem amarrado, já carreguei isso por tanto tempo, vou continuar com a minha carga de cânhamo". Em seguida, eles encontraram linho, tecido de linho, algodão, e tecido de algodão, e cada vez o homem que carregava o cânhamo, dizia: "Não, o cânhamo está bem para mim", enquanto seu amigo mudava de carga para o que era mais valioso. Mais tarde, eles encontraram prata, e em seguida ouro. Cada vez um dos homens sempre mudava o que ele estava carregando para algo melhor, mas o outro homem teimosamente manteve o seu feixe de cânhamo. Quando chegaram em casa, a família do homem que levava o ouro ficou muito satisfeita. Quanto ao homem que carregava o cânhamo, a sua família não ficou nada satisfeita! Por que não mudamos as nossas opiniões, as nossas idéias, quando vemos algo melhor? A razão por que não fazemos isso é por causa do apego. Este é o meu ponto de vista. Estamos confortáveis com os velhos pontos de vista, mesmo sabendo que eles estão errados. Nós realmente não queremos mudar. Às vezes a nossa auto-imagem está ligada a essas opiniões. Como o cientista, que está apegado às suas realizações, apegado ao que viu até agora, ele ou ela resistem às novas idéias.</p>

<p class=Normal>Esse é o problema chamado dogmatismo. Às vezes, quando falo sobre levitação, as pessoas dizem levitação não existe, é apenas um mito. Espere até você ver alguém levitando! Se você viu alguém levitar, se os três monges aqui levantam-se cerca de um metro, isso não seria algo desafiante?</p>

<p class=Normal>Desculpe, não podemos fazer isso em público. É contra as nossas regras. Uma das razões pelas quais não podemos demonstrar poderes psíquicos na frente das pessoas é porque se o fizéssemos, alguém provavelmente iria gravá-lo em uma câmera de vídeo e enviá-lo para um canal de televisão. Em seguida, todos, até mesmo do exterior, viriam a Perth. Não para ouvir o Dhamma, não para ouvir sobre o Budismo, mas só para ver os monges fazerem seus truques. Então, seríamos pressionados a dar demonstrações o tempo todo. Seria como um circo, e não um templo. O ponto é que os monges não estão aqui para demonstrar truques.</p>

<p class=Normal>Mesmo se um monge faz algum milagre, muitas pessoas diriam: "Isso é apenas um truque, foi feito com efeitos especiais. Eles não estão realmente levitando." Se você não quiser acreditar, não irá acreditar. Este é o problema com o dogmatismo. O que não queremos ver, não vemos. Quando não queremos acreditar, entramos em negação. É por isso que digo que muitos cientistas estão em negação sobre a natureza da mente.</p>

<p class=Normal><b>O Menino sem Cérebro</b></p>

<p class=Normal>Este é um caso bem conhecido que lança um desafio para a ciência moderna. É o caso do professor John Lorber e o estudante sem cérebro. [<a href="#N1">1</a>]<a name=R1></a> O Professor Lorber era um neurologista da Universidade de Sheffield, que chefiava uma cadeira de pesquisa em pediatria. Ele fez uma série de pesquisas sobre hidrocefalia, ou água no cérebro. O médico do estudante na universidade percebeu que o jovem tinha a cabeça um pouco maior do que uma cabeça normal, e assim o encaminhou para o Professor Lorber, simplesmente por curiosidade. Quando fizeram um scanner do cérebro do aluno viram que o seu crânio estava cheio, principalmente com fluido cerebrospinal. O estudante tinha um QI de 126, ganhou um diploma de primeira classe em matemática, e era socialmente completamente normal. E no entanto o jovem não tinha praticamente nada de cérebro. Esta não é apenas uma fabricação; outras pesquisas encontraram mais pessoas sem cérebro. Durante a primeira guerra mundial, quando houve tremenda carnificina nas trincheiras da Europa, soldados tiveram seus crânios literalmente explodidos por balas e estilhaços. Diz-se que os médicos descobriram que algumas das cabeças rompidas desses cadáveres estavam vazias. Não havia cérebro. A evidência desses médicos foi posta de lado por ser muito difícil de entender. Mas o professor Lorber foi em frente com as suas descobertas, e publicou-as, para grande perturbação da comunidade científica. Bilhões de dólares são destinados para as pesquisas sobre o cérebro. Pontos de vista atuais sustentam que são os desequilíbrios no cérebro que causam as depressões, a falta de inteligência, ou os problemas emocionais. E no entanto há evidências que mostram não ser necessário um grande cérebro para ter uma mente excelente.
Certa vez um amigo médico em Sydney discutiu este caso comigo. Ele disse que tinha visto a tomografia computadorizada, e confirmou que o caso era bem conhecido na comunidade médica. Ele explicou que o jovem só tinha aquilo que é conhecido como tronco cerebral reptiliano. Normalmente, qualquer bebe que nasça com apenas o tronco cerebral reptiliano, sem o córtex e as outras coisas, geralmente morre imediatamente, ou dentro de poucos dias após o nascimento. Um tronco cerebral reptiliano não é capaz de manter as funções básicas do corpo tais como o coração, a respiração, ou o fígado. Não é suficiente para manter as funções superiores do cérebro. Não é suficiente para a linguagem, não é suficiente para a inteligência, certamente não é suficiente para ser um estudante de primeira classe em matemática. Este médico disse, "Ajaan Brahm, você não acredita o problema que isso está causando no meu campo da ciência. Destroça tantas pesquisas feitas no passado. Isso está desafiando tantas empresas farmacêuticas que estão ganhando bilhões de dólares em lucros". Como os cientistas dogmáticos não conseguem entender como uma pessoa praticamente sem cérebro pode ser inteligente, eles simplesmente enterram os resultados no fundo do arquivo, classificando-a como uma anomalia. Mas a verdade não simplesmente desaparece.</p>

<p class=Normal><b>A Mente e o Cérebro</b></p>

<p class=Normal>Assim que começamos a incluir nas equações a mente, esse "fantasma na máquina", os cientistas tendem a ficar desconcertados. Eles se refugiam no dogma, e dizem: "Não, isso não pode existir". </p>

<p class=Normal>No que diz respeito ao Budismo há seis sentidos. Não apenas os cinco sentidos da ciência, ou seja, visão, audição, olfato, paladar e tato, mas além disso, a mente. Desde o início do Budismo, a mente tem sido o sexto sentido. Vinte e cinco séculos atrás, o sexto sentido era bem reconhecido. Portanto, isso não significa mudar as coisas para manter-se de acordo com os tempos modernos, foi assim desde o início. O sexto sentido, a mente, é independente dos outros cinco sentidos. Em particular, a mente é independente do cérebro. Se alguém se vountariar a fazer um transplante de cérebro comigo, você pega o meu cérebro e eu levo o seu cérebro, ainda serei Ajaan Brahm e você ainda vai ser você. Quer experimentar? Se isso fosse possível, e acontecesse, você ainda seria você. A mente e o cérebro são duas coisas distintas. A mente pode fazer uso do cérebro, mas não obrigatoriamente.</p>

<p class=Normal>Alguns de vocês podem ter tido experiências fora do corpo. Essas experiências fora do corpo foram recentemente objeto de investigação científica. Experiências fora do corpo são agora um fato científico! Eu gosto de agitar as pessoas dizendo coisas assim. Recentemente vi que o Dr. Sam Parnia, pesquisador da Universidade de Southampton Medical School, escreveu um artigo, afirmando que a consciência sobrevive à morte. [<a href="#N2">2</a>]<a name=R2></a> Ele disse que não sabia como isso acontece, ou por que isso acontece, mas diz ele, isso acontece. Suas evidências foram obtidas de pessoas que tiveram experiências fora do corpo no seu hospital. O Dr. Parnia, investigou e entrevistou muitos, muitos pacientes. Baseado na informação que eles lhe deram, avaliada por um cientista com a cabeça fria, a conclusão foi que sim, as pessoas estavam conscientes durante o tempo que elas estiveram mortas. O que foi especialmente muito convincente foi que com frequência as pessoas de fato podiam descrever ao médico os procedimentos médicos que foram feitos durante o tempo em que elas estavam clinicamente mortas. Elas podiam descrevê-lo como se estivessem olhando para o seu corpo a partir de uma posição acima da mesa. Mas o Dr. Parnia não pôde explicar como isso acontece. Ele não pôde explicar por que isso acontece. Mas outras descobertas médicas também apóiam o que foi descrito acima. Finalmente, as suas descobertas replicaram o trabalho desenvolvido anteriormente pelo Dr. Raymond A. Moody nos Estados Unidos. [<a href="#N3">3</a>]  </p>     

<p class=Normal><a name=R3></a>A evidência mostrou aos médicos pragmáticos que experiências fora do corpo acontecem. Mas como isso pode acontecer? Se concordarmos que a mente pode ser independente do corpo, então temos uma explicação plausível. O cérebro não precisa estar funcionando para uma mente existir. Os fatos científicos aí estão, a prova está aí, mas um grande número de cientistas não gostam de admitir os fatos. Eles preferem fechar os olhos por causa do dogmatismo.</p>

<p class=Normal><b>Venha e Veja por Você Mesmo</b></p>

<p class=Normal>Se tivéssemos apenas uma pessoa que tenha sido confirmada como clinicamente morta que pudesse descrever para os médicos, assim que ela tenha sido revivida, o que tinha sido dito e feito durante esse período de morte, isso não seria bastante convincente? Quando eu estava estudando a física de partículas elementares havia uma teoria que para provar a sua existência necessitava do que foi chamado de partícula 'W'. No cíclotron, em Genebra, o CERN financiou um projeto de pesquisa enorme, chocando átomos uns contra os outros com um enorme acelerador de partículas, para tentar encontrar uma dessas partículas 'W'. Eles gastaram literalmente centenas de milhões de libras no projeto. Eles encontraram uma, apenas uma partícula 'W'. Eu não acho que eles encontraram outra desde então. Mas tendo sido encontrada uma partícula 'W', os pesquisadores envolvidos nesse projeto acabaram recebendo o prêmio Nobel de Física. Eles provaram a teoria encontrando apenas uma partícula 'W'. Isso é boa ciência. Apenas um é suficiente para provar uma teoria.</p>

<p class=Normal>Quando se trata de coisas que nós não queremos acreditar, uma experiência factual clara e inegável é chamada de anomalia. Anomalia é uma palavra na ciência para alguma evidência desconcertante que podemos esconder no fundo do arquivo e não olhar de novo, porque é uma ameaça à nossa visão do mundo. Isso ameaça aquilo que queremos acreditar. Ameaça o nosso dogma. No entanto, uma parte essencial do método científico é que as teorias têm que ser abandonadas em favor das evidências, respeitando os fatos. O ponto é que há evidência de uma mente independente do cérebro. Mas uma vez que essa evidência seja aceita, e sigamos o método científico, então, muitas teorias entesouradas, o que chamamos de "vacas sagradas" terão que ser abandonadas.</p>

<p class=Normal>Quando vemos algo que desafia alguma teoria, na ciência ou na religião, não se deve ignorar a evidência. Temos que mudar a teoria para se adequar aos fatos. Isso é o que fazemos no Budismo. Todo o Dhamma do Buda, tudo o que ele ensinou, se isso não se encaixa na experiência, então não devemos aceitá-la. Não devemos aceitar as palavras do Buda em contradição com a experiência. Isso está claramente indicado no Kalama Sutta. (<a href="../sutta/ANIII.65.php">AN III.65</a>) O Buda disse para não acreditar, porque está escrito nos livros, ou mesmo se eu disser isso. Não basta acreditar porque é tradição, ou porque soa bem, ou porque é reconfortante. Certifique-se que se adapta à sua experiência. A existência da mente, independente do cérebro, está de acordo com a  experiência. Os fatos mostram isso.</p>

<p class=Normal>Às vezes, no entanto, não podemos confiar nos especialistas. Você não pode confiar em Ajaan Brahm. Você não pode confiar nas revistas científicas. Porque muitas vezes as pessoas são tendenciosas. O Budismo lhe oferece um método científico para a sua prática. O Budismo diz, faça o experimento e descubra por você mesmo se aquilo que o Buda disse é verdade ou não. Confira a sua experiência. Por exemplo, desenvolva o método para testar a verdade de vidas passadas e do renascimento. Não basta acreditar com base na fé, descubra por você mesmo. O Buda ofereceu um experimento científico que pode ser repetido.</p>

<p class=Normal>Até entendermos a lei de <i>kamma</i>, que faz parte do Budismo, <i>kamma</i> será apenas uma teoria. Você acredita que existe um Deus "lá em cima" que decide quando você pode ser feliz ou infeliz? Ou tudo que acontece é apenas fruto do acaso? Sua felicidade e seu sofrimento na vida, sua alegria, sua dor e decepções, são merecidas? Você é o responsável ou será culpa de alguém? É por mero acaso que somos ricos ou pobres? É por má sorte que ficamos doentes e morremos em tenra idade? Porque? Você mesmo pode encontrar a verdadeira resposta. Você pode experimentar a lei de <i>kamma</i> através da meditação profunda. Quando o Buda sentou sob a figueira-dos-pagodes em Bodhgaya, os dois conhecimentos que ele obteve, pouco antes da sua iluminação, foi o conhecimento da verdade do renascimento com base na experiência e o conhecimento da Lei de <i>kamma</i> com base na experiência. Isto não foi teoria, não apenas mais pensamentos, e não algo elaborado a partir de discussões em torno da mesa do café, isto foi a compreensão da natureza da mente com base numa profunda experiência. Você também pode ter essa mesma experiência.</p>

<p class=Normal>Todas as religiões do mundo, exceto o Budismo, mantêm a existência de uma alma. Elas afirmam um "eu" real, uma "essência de todo o ser", uma "pessoa", um "eu". O Budismo diz que não há um eu! Quem está certo? O que é esse "fantasma na máquina"? É uma alma, é um ser, ou é um processo? O que é isso? Quando o Buda disse que não há ninguém aqui, ele nunca intencionou que isso fosse apenas para ser acreditado, ele quis dizer que isso deve ser experimentado. O Buda disse, como um fato científico, que não existe um "eu". Mas, como qualquer fato científico, isso tem que ser experimentado, cada um por si mesmo, <i>paccattam veditabbo viññuhi</i>. Muitos de vocês entoam essas palavras em pali todos os dias. É a ciência básica Budista. Você tem que manter a mente aberta. Você não acredita que há "não-eu", você não acredita que há um "eu", ambas crenças são dogmatismo. Mantenha a mente aberta até concluir o experimento. O experimento é a prática de <i>sila, samadhi e pañña</i>, (virtude, concentração e sabedoria). O experimento é a prática Budista. Fazer os mesmos procedimentos experimentais que fez o Buda sob a figueira-dos-pagodes. Repita-o e veja se você obtém os mesmos resultados. O resultado é chamado Despertar.</p>

<p class=Normal>Homens e mulheres têm repetido essa experiência muitas vezes ao longo dos séculos. É no laboratório da prática Budista que surgem os Despertos, os Arahants. Os Arahants são os que fizeram o experimento e encontraram o resultado. É por isso que o Budismo sempre foi o método científico. É a forma de saber por si mesmo a verdade do Despertar.</p>

<p class=Normal>O Budismo é também o método científico para descobrir a verdade sobre a felicidade, aquilo no qual a maioria das pessoas estão interessadas. O que é a felicidade? Faz pouco tempo alguns alunos da nossa escola islâmica local vieram visitar nosso monastério. Eu fiz um pequeno jogo com eles, que também foi uma maneira esclarecedora para demonstrar a existência da mente. Eu estava tentando explicar o Budismo, então eu lhes perguntei:</p>

<p class=Normal>"Vocês estão felizes? Coloquem as suas mãos para cima se vocês estiverem felizes agora".</p>

<p class=Normal>Inicialmente não houve resposta. Em seguida, uma pessoa respondeu e levantou a mão.</p>

<p class=Normal>"Ah! Você estão todos infelizes?" Eu disse: "Apenas uma pessoa, vamos! Vocês estão felizes ou não?"</p>

<p class=Normal>Mais alunos colocaram as mãos para cima.</p>

<p class=Normal>"Tudo bem, todas essas pessoas que colocaram as suas mãos para cima dizendo que estão felizes, com o seu dedo indicador agora vocês podem apontar para essa felicidade? Vocês podem dar as coordenadas no espaço?" Elas não conseguiram localizar essa felicidade.</p>

<p class=Normal>É difícil localizar a felicidade, não é? Você já esteve deprimido? Da próxima vez que se sentir deprimido, tente apontar para esse sentimento com o dedo indicador! Você vai descobrir que não será capaz de localizar a depressão, ou a felicidade, no espaço. Não é possível dar as coordenadas, porque estas coisas residem na mente, não no corpo, não no espaço. A mente não está localizada no espaço. É por isso que depois que a pessoa morre, se ela se torna um fantasma, poderá aparecer em qualquer lugar do  mundo imediatamente. As pessoas às vezes me perguntam: "Como isso pode acontecer?" Como pode uma pessoa que morre, digamos, em Nova York, aparece imediatamente em Perth? É porque a mente não está localizada no espaço, é por isso. É por isso que você não pode apontar para a felicidade, você não pode apontar para a depressão, mas ambas são reais. Você está imaginando a felicidade? Você imagina a depressão? São reais. Todos sabemos disso. Mas você não pode localizá-las no espaço tridimensional. Depressão, felicidade, e muitas outras coisas reais, tudo permanece no espaço-mente.</p>

<p class=Normal>A mente não está no cérebro, não está no coração. Vimos que alguém pode não ter cérebro, mas ainda assim ter uma mente. Você pode tirar o seu coração, e ter um coração biônico, ou um transplante de coração, e você ainda seria você. Esta compreensão da mente é a razão porque os Budistas não têm nenhuma objeção em relação à clonagem. Você deseja me clonar, vá em frente! Mas não pense que se você clonar Ajaan Brahm, será capaz de ter um Ajaan Brahm que irá para Singapura esta noite, outro que ficará em Perth para a palestra da próxima sexta-feira, outro que ficará no monastério Bodhinyana, outro que poderá ir para Sydney, e outro que poderá ir para Melbourne. Se você me clonar, a pessoa que se parece comigo vai ter a personalidade, o conhecimento, inclinação e todo o demais completamente diferentes. As pessoas clonam carros Toyota da mesma forma. Eles parecem ser exatamente iguais, mas o desempenho depende realmente do motorista dentro do carro. Isso é a clonagem, apenas replicar um corpo. Com certeza tem a mesma aparência, mas o corpo é tudo que uma pessoa é? Você já viu gêmeos idênticos? São gêmeos idênticos, com a mesma personalidade? Eles têm a mesma inteligência? As suas inclinações são  idênticas? Será que pelo menos eles gostam da mesma comida? A resposta normalmente é não.</p>

<p class=Normal>Por que as pessoas têm tantos problemas com a clonagem? Clonem tanto quanto quiserem. Apenas serão criados mais corpos nos quais entrarão fluxos de consciência. Esses fluxos de consciência vêm de vidas passadas. Qual é o problema? Nunca seremos capazes de prever o resultado. Suponha que tenha sido tirado o cérebro de Einstien, extraída parte do DNA dele, e clonado um novo Einstien. Ele pode parecer o mesmo, mas eu garanto que ele não vai ser nem metade tão inteligente.</p>

<p class=Normal>Se as pessoas querem continuar com a pesquisa de células-tronco, que irá ajudar a humanidade, então por que não? Na pesquisa com as células-tronco não há um "ser" envolvido. O "ser" ainda não surgiu. No Budismo, entende-se que o "ser" se estabelece  no ventre da mãe, a qualquer momento, desde a concepção até o nascimento. Às vezes, nem sequer se estabelece no útero e o feto é natimorto. As objeções à pesquisa com células tronco são dogmáticas, não científicas, e sem compaixão. São tolas, naquilo que me diz respeito. Acho que algumas vezes arrancaria os cabelos se não fosse um monge.</p>

<p class=Normal>Se alguém quiser conhecer a evidência científica para o renascimento, veja o trabalho do professor Ian Stevenson. Ele passou toda a sua vida na Universidade de Virginia pesquisando renascimentos com uma sólida base científica. [<a href="#N4">4</a>] <a name=R4></a>Chester Carlson, o inventor da xerografia (incentivado por sua esposa), ofereceu os recursos para  permitir que o Professor Stevenson se dedicasse em tempo integral nessa pesquisa. Se não fosse pelo fato de que as pessoas não querem acreditar no renascimento, o Dr. Ian Stevenson agora seria um cientista mundialmente famoso. Ele até passou alguns anos como professor visitante do Magdalene College, em Oxford, assim vocês podem ver que não se trata  apenas de algum professor esquisito; ele tem todas as credenciais de um respeitado acadêmico ocidental.</p>

<p class=Normal>O Dr. Stevenson tem mais de 3000 casos em seus arquivos. Um exemplo interessante foi o caso muito claro de um homem que se lembrava muitos detalhes de sua vida passada, sem nenhuma possibilidade que ele pudesse ter  obtido essas informações de alguma outra fonte. Essa pessoa morreu apenas algumas semanas antes de ter renascido! O que levanta a questão, durante todos esses meses em que o feto estava no útero, quem era o feto? No que diz respeito ao Budismo, a mãe manteve o feto com o próprio fluxo de consciência dela. Mas quando um outro fluxo de consciência surgiu, então o feto se tornou a nova pessoa. Esse é um caso em que o fluxo de consciência se estabeleceu no útero da mãe quando o feto estava quase completamente desenvolvido. Isso pode acontecer. Isso era compreendido pelo Budismo 25 séculos atrás. Se o fluxo de consciência não se estabelecer no ventre da mãe, a criança é um natimorto. Há muitas evidências que confirmam isso.</p>

<p class=Normal><b>Ciência e Budismo</b></p>

<p class=Normal>Quando um Budista olha através de um telescópio, ele não tem medo do que poderá encontrar. Ele não tem medo da ciência. A ciência é uma parte essencial do Budismo. Se a ciência for capaz de desmentir o renascimento, então os Budistas deveriam abandonar a idéia do renascimento. Se a ciência desmentir o não-eu, e mostrar que há um eu, então todos os Budistas deveria abandonar o não-eu. Se a ciência provar que não há tal coisa como <i>kamma</i>, mas em vez disso, há um grande Deus no céu, então, todos os Budistas deveriam acreditar em Deus. Isto é, se for a ciência demonstrável. O Budismo não tem vacas sagradas. No entanto, eu encorajo vocês a fazerem essas experiências por si mesmos. Aposto que vocês irão descobrir que não há "ninguém aqui dentro". Vocês irão descobrir <i>kamma</i>. Vocês irão descobrir que estiveram aqui antes, que esta não é a sua primeira vida. Se vocês não se comportarem nesta vida, ainda terão uma outra vida por vir. Vocês acham que deram um fim às fraldas, à escola? Vocês realmente querem passar por tudo isso de novo? Se não quiserem, tomem cuidado.</p>

<p class=Normal>Então, aqui está o que penso sobre a ciência e o Budismo. Eu penso que o Budismo é ciência pura, uma ciência que não pára "lá fora", mas também investiga a mente, o "ser", o "fantasma na máquina". E não ignora quaisquer anomalias. O Budismo toma tudo como seus dados, especialmente das experiências, e os analisa cientificamente. O Budismo é incrivelmente bem sucedido.</p>

<p class=Normal>Uma das razões porque as pessoas celebram a ciência é devido a todas as suas conquistas tecnológicas. Uma das razões porque o Budismo está crescendo nos dias de hoje é por causa de todas as suas realizações na "tecnologia da mente". O Budismo resolve problemas. Explica as dificuldades mentais. O Budismo consegue resolver esses problemas internos, porque tem todas estratégias, essas antigas "engenhocas" que realmente funcionam. Se você experimentar algumas dessas engenhocas Budistas, você irá descobrir por si mesmo que elas dão resultados, elas resolvem o sofrimento interior e a dor. É por isso que o Budismo está crescendo. Eu penso que o Budismo irá suplantar a ciência!</p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>


<p class=Normal><b>Notas:</b></p>

<p class=Normal>Baseado numa palestra dada para pessoas leigas no Dhammaloka Buddhist Centre, Nollamara, Western Australia, em 19.10.2001. </p> 


<p class=Normal><a name=N1></a> [1] Veja o artigo <i>Is Your Brain Really Necessary?</i> Science, Vol. 210, 12 Dezembro 1980, por Roger Lewin sobre as descobertas do Professor Lorber. [<a href="#R1">Retorna</a>] </p>

<p class=Normal><a name=N2></a> [2] Sam Parnia e Peter Fenwick, Resuscitation Journal, Vol. 52, Issue 1, Janeiro 2002, pag 5-11. <i>Near death experiences in cardiac arrest: Visions of a dying brain or visions of a new science of consciousness</i>. [<a href="#R2">Retorna</a>] </p>

<p class=Normal><a name=N3></a> [3] Raymond A. Moody, <i>Life after life: The investigation of a phenomenon Survival of Bodily Death</i>. Alexander Books: Alexander NC, USA, 1981, [<a href="#R3">Retorna</a>] </p>

<p class=Normal><a name=N4></a> [4] Dr. Ian Stevenson, <i>Where Reincarnation and Biology Intersect</i>. 1997, Praeger Publishers, New York, USA. [<a href="#R4">Retorna</a>] </p>






<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>

<!-- Counter/Statistics -->
<script language="JavaScript"
src="http://us.js2.yimg.com/us.js.yimg.com/lib/smb/js/hosting/cp/js_source/whv2_001.js">
</script>
<script language="javascript">geovisit();</script>
<noscript><img src="http://visit.webhosting.yahoo.com/visit.gif?time"
alt="setstats" border="0" width="1" height="1"></noscript>


<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>