<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"definindo_sati");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO',"16 Março 2013 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'> Definindo a Atenção Plena </Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'>Ajaan Thanissaro</Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>

<p class=Normal>O que significa ter atenção plena na respiração? Algo muito simples: manter em mente a respiração. Continuemos lembrando da respiração sempre que inspiramos, sempre que expiramos. O estudioso britânico que criou a expressão "atenção plena", (<i>mindfulness</i>), para traduzir a palavra em Pali <i><a href="../glossario.php#sati">sati</a></i> provavelmente foi influenciado pela prece Anglicana de estar sempre atento às necessidades dos outros, em outras palavras, ter sempre as necessidades destes em mente. Mas mesmo que a palavra "plenamente atento" tenha sido provavelmente extraída de um contexto cristão, o próprio Buda definiu <i>sati</i> como a capacidade de lembrar, ilustrando a sua função na prática da meditação com os quatro <i>satipatthanas</i>, ou fundamentos da atenção plena.</p>

<p class=Normal> “E o que, <i>bhikkhus</i>, é a faculdade da atenção plena? Neste caso, <i>bhikkhus</i>, o nobre discípulo tem atenção plena, ele possui suprema atenção plena e discriminação, ele se recorda e lembra aquilo que foi feito e dito há muito tempo. Ele permanece contemplando o corpo como um corpo, ardente, plenamente consciente e com atenção plena, tendo colocado de lado a cobiça e o desprazer pelo mundo. Ele permanece contemplando as sensações como sensações ... a mente como mente ... os objetos mentais como objetos mentais, ardente, plenamente consciente e com atenção plena, tendo colocado de lado a cobiça e o desprazer pelo mundo. Essa é chamada a faculdade da atenção plena.”  (<a href="../sutta/SNXLVIII.10.php">SN XLVIII.10</a>)</p>

<p class=Normal>A análise completa dos <i>satipatthanas</i>, (<a href="../sutta/DN22.php">Maha-satipatthana Sutta, DN 22</a>), começa com instruções de estar sempre atento na respiração. Instruções como "tragam a rasa atenção, (<i>bare attention</i>), para a respiração", ou "aceitem a respiração", ou qualquer outra coisa que os professores modernos nos dizem que a atenção plena é suposta ser, são na verdade funções de outras qualidades mentais. Não são automaticamente uma parte de <i>sati</i>, mas podemos trazê–las sempre que estas sejam apropriadas.</p>

<p class=Normal>Uma qualidade que é sempre adequada no estabelecimento da atenção plena é estar vigilante ou alerta. A palavra em Pali para vigilante, alerta ou plena consciência, <i><a href="../glossario.php#sapajanna">sampajañña</a></i>, é outro termo que é muitas vezes mal compreendido. Não significa estar consciente do presente sem escolha, ou compreender o presente. Exemplos do Cânone mostram que <i>sampajañña</i> significa estar consciente do que está sendo feito ao movimentar o corpo, ao movimentar a mente. Afinal, se é para obter insights sobre como estamos causando sofrimento, nosso foco principal sempre tem que ser o que realmente estamos fazendo. É por isso que a atenção plena e a plena consciência devem ser sempre usadas em conjunto na meditação.</p>

<p class=Normal>No <i>Satipatthana Sutta</i>, ambos <i>sati</i> e <i>sampajañña</i> são combinados com uma terceira qualidade:  ardente, (<i><a href="../glossario.php#atapi">atapi</a></i>). Aqui ‘ardente’ significa estar aplicado naquilo que está sendo feito, dando o melhor de si para fazê–lo com habilidade. Isso não significa que devemos nos manter esforçando e suando o tempo todo, apenas que haja continuidade tanto no desenvolvimento de hábitos benéficos, quanto no abandono dos hábitos prejudiciais. Lembremos que nos oito elementos do caminho para a libertação, a atenção plena correta nasce do esforço correto. O esforço correto é o esforço para ser habilidoso. A atenção plena ajuda o esforço na medida em que nos lembra permanecer com ele, de modo que não o abandonemos.</p>

<p class=Normal>Todas estas três qualidades obtêm seu foco à partir do que o Buda chamava de <i><a href="../glossario.php#yoniso_manasikara">yoniso manasikara</a></i>, a atenção com sabedoria. Note: trata–se de uma atenção com sabedoria, não uma mera ou simples atenção. O Buda descobriu que a forma como damos atenção às coisas é determinada por aquilo que consideramos importante: as dúvidas que trazemos para a prática, os problemas que queremos que prática resolva. Nenhum ato de atenção jamais é de mera atenção. Se não houvesse problemas na vida, poderíamos simplesmente nos abrirmos para o que quer que surgisse. Mas o fato é que há um grande problema alí no meio de tudo que fazemos: o sofrimento que vem ao agir com ignorância ou delusão. É por isso que o Buda não nos diz para ver cada momento com os olhos de um principiante. Temos que manter sempre em mente a questão do sofrimento e do seu fim.</p>

<p class=Normal>Caso contrário a atenção sem sabedoria irá atrapalhar, voltando-se para questões como "Quem sou eu?", "Eu tenho um eu?" –  perguntas que tratam de questões existenciais e de identidade. Estas questões, o Buda disse, nos levarão a um emaranhado de idéias e nos deixarão presos em espinhos. As questões que levam à liberdade têm foco na compreensão do sofrimento, no abandono da causa do sofrimento, e no cultivo do caminho para o fim do sofrimento. O desejo de respostas para essas perguntas é que nos faz ficarmos alertas para as nossas ações –  pensamentos, palavras e atos –  e nos torna ardentes para que sejam  realizadas com habilidade.</p>

<p class=Normal>A atenção plena é o que mantém a perspectiva da atenção com sabedoria em mente. Pesquisas psicológicas recentes têm mostrado que a atenção se dá em momentos discretos. Podemos estar atentos a alguma coisa apenas por um período muito curto de tempo e temos que nos lembrar, momento após momento, de voltar para aquilo se quisermos continuar a estar atentos. Em outras palavras, a atenção contínua – o tipo que pode observar as coisas ao longo do tempo – tem de ser costurada à partir de intervalos curtos. É para isso que existe a atenção plena. Ela mantém em mente o objeto e o propósito da atenção.</p>

<p class=Normal>Livros populares sobre meditação, no entanto, oferecem uma série de outras definições para a atenção plena, e um monte de outras funções que esta deve cumprir – são tantas que a pobre palavra fica totalmente distorcida, perdendo a sua forma. Em alguns casos, a atenção plena é até mesmo definida como o Despertar, como na frase: "Um momento de atenção plena é um momento de Despertar" –  algo que o Buda nunca diria, porque a atenção plena é condicionada e <i>nirvana</i> não é.</p>

<p class=Normal>Estas não são apenas questões menores a serem discutidas pelos estudiosos críticos. Se não vermos as diferenças entre as qualidades que estamos trazendo para a meditação, elas se misturam e se confundem, tornando difícil  surgir um insight real. Se assumirmos que um dos fatores do caminho para o Despertar é o próprio Despertar, é como chegar no meio de uma estrada e então cair no sono ali mesmo. Nunca chegaremos ao fim da estrada, e nesse meio tempo  estaremos fadados a sermos atropelados pelo envelhecimento, enfermidade e morte. Assim necessitamos ter claro o nosso rumo, e isso exige, entre outras coisas, que saibamos exatamente o que a atenção plena é e o que ela não é.</p>

<p class=Normal>Eu já vi a atenção plena ser definida como "carinhosa ou afetuosa atenção" ou "atenção compassiva", mas afeto e compaixão não são o mesmo que a atenção plena. São coisas distintas. Se forem levadas para a meditação, é necessário que fique claro que essas qualidades estão agindo ademais da atenção, porque a habilidade na meditação requer discernir quando qualidades como a compaixão são úteis e quando elas não são. Como o Buda diz, há momentos em que o afeto é uma causa para o sofrimento, portanto é bom estar atento. </p>
<p class=Normal>Às vezes, a atenção plena é definida como apreciar o momento por todos os pequenos prazeres que este nos pode oferecer: o gosto de uma uva passa, a sensação de uma xícara de chá em nossas mãos. No vocabulário do Buda, esta apreciação é chamada de contentamento ou satisfação, (<i>pamojja</i>). O contentamento é útil quando estamos enfrentando dificuldades físicas, mas não é sempre útil no campo da mente. De fato, o Buda certa vez disse que o segredo de sua iluminação foi que ele não permitiu se contentar com qualquer realização que já tivera alcançado. Ele continuou avançando em suas realizações até que não houvesse nada mais elevado para se atingir. Portanto o contentamento tem de conhecer o seu tempo e lugar. A atenção plena, se não for misturada com contentamento, pode ajudar a manter esse fato em mente.</p>

<p class=Normal>Alguns professores definem a atenção plena como "não–reação" ou "aceitação radical." Se olharmos para essas palavras no vocabulário do Buda, os termos mais próximos que iremos encontrar serão equanimidade, (<i>upekkha</i>), e paciência, (<i>khanti</i>). Equanimidade significa aprender a deixar de lado nossas preferências para que possamos observar o que realmente está presente. Paciência é a habilidade de não ser perturbado pelas coisas que não gostamos, não abandonar as situações difíceis, mesmo quando elas não sejam solucionadas tão rapidamente quanto queiramos. No estabelecimento da atenção plena, no entanto, permanecemos com as coisas desagradáveis não somente simplesmente aceitando-as, mas sim observando e compreendendo. Uma vez que vejamos claramente que uma qualidade particular, como a aversão ou cobiça é prejudicial para a mente, não poderemos permanecer pacientes ou equânimes perante aquilo. Teremos que fazer o esforço necessário para nos livrarmos disso e nutrir qualidades hábeis em seu lugar, lançando mão de outros fatores do caminho: o pensamento correto, (<i>samma–sankappo</i>), e o esforço correto, (<i>samma–vayamo</i>).</p>

<p class=Normal>A atenção plena, afinal, é parte de um caminho maior traçado pela atenção com sabedoria. Temos que sempre lembrar de trazer o mapa maior para aplicá–lo em tudo o que fazemos. Por exemplo, agora mesmo estamos tentando manter a respiração em mente porque vemos que a concentração, como um fator do caminho, é algo que precisa ser cultivado, e a atenção plena na respiração é uma boa maneira de fazê–lo. A respiração também é uma boa perspectiva à partir da qual podemos observar diretamente o que está acontecendo na mente, ver quais qualidades mentais estão dando bons resultados e quais não estão.</p>

<p class=Normal>A meditação envolve muitas qualidades mentais, e temos que ter clareza sobre quais são elas, o que as distinguem, e o que cada uma delas pode fazer. Dessa forma, quando as coisas estão em desequilíbrio,  podemos identificar o que está faltando e  promover o que for necessário para compensar a sua ausência. Se estamos nos sentindo confusos e irritados, tentemos trazer um pouco de gentileza e contentamento. Quando estamos preguiçosos, reavivemos a noção dos perigos dos hábitos prejudiciais e complacentes. Não se trata apenas de acumular mais e mais atenção plena. Temos que acrescentar outras qualidades também. Primeiro temos que estar atentos o suficiente para costurar as coisas, para manter as questões básicas da meditação em mente e observar as coisas ao longo do tempo. Então tentamos notar – vigilantes e alertas – de modo a ver o que mais colocar e mexer na panela.</p>

<p class=Normal>É como cozinhar. Quando não gostamos do sabor da sopa fazemos ajustes, não podemos apenas adicionar mais e mais sal. Às vezes acrescentamos cebola, às vezes alho, por vezes orégano –  o que quer sentimos ser necessário. Basta ter em mente o fato de que temos toda uma prateleira de temperos para usar.</p>

<p class=Normal>E lembremos que cozinhar tem um propósito. No mapa do caminho, atenção plena correta não é o ponto final. Se supoem que ela conduza à concentração correta.</p>

<p class=Normal>Com freqüência é dito que a atenção plena e a concentração são duas formas distintas de meditação, mas o Buda nunca fez uma divisão clara entre as duas. Em seus ensinamentos, a atenção plena se mistura com a concentração; e a concentração constitui a base para uma atenção plena ainda melhor. Os quatro fundamentos da atenção plena também são os temas de concentração. O mais elevado nível de concentração é aquele em que a atenção plena se torna pura. Como observou uma vez <a href="../arquivo_textos_theravada/tradicao_de_florestas.php#Lee">Ajaan Lee Dhammadharo</a>, um mestre da Tradição das Florestas da Tailândia, a atenção plena, (<i>sati</i>), combinada com ardor, (<i>atapi</i>), se transforma no fator de concentração chamado <i>vitakka</i>, ou "pensamento aplicado", no qual mantemos os pensamentos sempre concentrados em uma coisa. E o estado alerta ou de plena consciência, (<i>sampajañña</i>),  combinado com ardor, (<i>atapi</i>), se transforma em outro fator de concentração: <i>vicara</i>, a "avaliação" ou o  "pensamento sustentado". Avaliamos o que está acontecendo com a respiração. É confortável? Se for, continuamos com ela. Se não for, o que podemos fazer para torná–la mais confortável? Tentamos torná–la um pouco mais longa, um pouco mais curta, mais profunda, mais superficial, mais rápida, mais lenta. Vemos o que acontece. Quando encontramos uma maneira de respirar que nutre um sentimento de plenitude e estímulo, podemos então espalhar a plenitude por todo o corpo. Devemos saber como nos relacionarmos com a respiração de modo que esta alimente um bom fluxo de energia em todo o corpo. Quando nos sentimos assim estimulados,  podemos nos acalmar com facilidade.</p>

<p class=Normal>Podemos ter apego à idéia de que nunca devemos mexer com a respiração, que devemos apenas observá–la como ela ocorre. No entanto, a meditação não é apenas um processo passivo de estar apenas presente diante do que quer que seja, sem julgar, sem realizar qualquer mudança. A atenção plena permanece costurando as coisas ao longo do tempo, mas ela também mantém em mente a idéia de que há um caminho a ser cultivado, e acalmar a mente é uma parte habilidosa desse caminho.</p>

<p class=Normal>É por isso que a avaliação, (<i>vicara</i>) –  julgar a melhor maneira de maximizar o prazer da respiração – é essencial para a prática. Em outras palavras, não abandonamos o nosso poder de julgamento enquanto desenvolvemos a atenção plena. Simplesmente treinamos para ser menos críticos e mais criteriosos, para produzir resultados tangíveis.</p>
<p class=Normal>Quando a respiração fica realmente plena e estimulante por todo o corpo, podemos deixar de lado a avaliação e simplesmente tornar-nos uno com a respiração. Esse senso de unicidade é também algumas vezes chamado de atenção plena, em um sentido literal: a plenitude da mente, (<i>mind-fullness</i>), um senso de unicidde que permeia todo o espectro da consciência. Estamos em unicidade com qualquer coisa na qual o foco repouse, em unicidade com o quer que estejamos fazendo. Não há nenhum "eu" independente. Este é o tipo de atenção que é fácil de confundir com o Despertar, porque pode parecer tão libertadora, mas no vocabulário do Buda esta não é nem a atenção plena, nem o Despertar. Isto é, <i>cetaso ekodibhava</i>, a unificação da mente – um fator da concentração, presente em todos os níveis desde o segundo <i>jhana</i> até a base da consciência infinita, (<i>viññanañcayatana</i>). Portanto, isto não é nem mesmo o nível máximo de concentração que se pode alcançar, e muito menos o Despertar.</p>

<p class=Normal>O que significa que ainda há mais por fazer. É este o ponto em que a atenção plena, a vigilância, e o ardor continuam o seu trabalho. A atenção plena lembra de que não importa o quão maravilhoso seja este senso de unicidade, ainda não resolvemos o problema do sofrimento. O estado de alerta tenta se concentrar no que a mente ainda está fazendo nesse estado de unicidade – quais escolhas ocultas  estão sendo feitas para dar continuidade a esse sentido de unicidade, e quais níveis sutis de sofrimento essas escolhas estão causando – enquanto o ardor tenta encontrar uma maneira de deixar de lado até mesmo essas escolhas sutis, de modo a se livrar desse sofrimento.</p>

<p class=Normal>Mas mesmo esse sentimento de unicidade é um meio para um fim mais elevado. Trazemos a mente para um estado de firme unicidade, de modo a deixar de lado as suas formas normais de dividir a experiência em “mim” e “fora de mim”, mas não paramos nisso. Tomamos então essa unicidade e continuamos submetendo-a a todos os fatores da atenção plena correta. É quando as coisas realmente importantes começam a se separar por conta própria. Ajaan Lee usa a imagem do minério em uma rocha. Permanecer com o senso de unicidade é como se contentar simplesmente com o conhecimento de que há estanho, prata e ouro na rocha: se isso é tudo que fazemos, nunca obteremos qualquer uso para isso. Mas se aquecermos a rocha até o ponto de fusão dos diferentes metais, estes irão se separar por conta própria.</p>

<p class=Normal>O insight libertador vem do testar, do experimentar. Em princípio é assim que conhecemos o mundo. Se não fôssemos criaturas ativas, não teríamos qualquer compreensão do mundo. As coisas seriam esquecidas, ignoradas, e nós não saberíamos como elas foram conectadas porque não teríamos nenhuma maneira de influenciá-las de modo a ver quais efeitos se dão com a alteração de certas causas. É porque agimos no mundo que entendemos o mundo.</p>

<p class=Normal>O mesmo acontece com a mente. Não podemos simplesmente sentar por aí na esperança de que uma única qualidade mental – atenção plena, aceitação, contentamento, unicidade – faça todo o trabalho. Se quisermos saber mais sobre os potenciais da mente, teremos que estar dispostos a agir – com as sensações no corpo, com as qualidades na mente. É então que conseguimos compreender causa e efeito.</p>
<p class=Normal>E isso exige todos os nossos poderes de inteligência – e isso não significa apenas a inteligência textual. Significa também a habilidade de notar o quê estamos fazendo, interpretar os resultados do que fizemos, e descobrir meios engenhosos de agir de modo que cause cada vez menos sofrimento e estresse: esperteza para o nobre caminho. A atenção plena permite que vejamos essas conexões pois ela nos lembra sempre de permanecer com essas questões, de permanecer com as causas até ver seus efeitos. Mas a atenção plena por si só não pode fazer todo o trabalho. Não podemos ajustar a sopa simplesmente despejando mais pimenta nela. Podemos adicionar outros ingredientes, conforme  forem necessários.</p>

<p class=Normal>Por isso é melhor não atribuir demasiados signfificados à palavra "atenção plena", ou atribuir-lhe demasiadas funções. Caso contrário, não poderemos discernir com clareza quando uma qualidade como o contentamento é útil ou não, quando precisamos conduzir a prática para a unicidade e quando precisamos desmontar a prática em suas partes.</p>

<p class=Normal>Dessa forma, mantenhamos as especiarias na prateleira claramente identificadas, e aprendamos através do uso qual tempero é bom para qual efeito. Só então poderemos desenvolver o nosso pleno potencial como um cozinheiro.</p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>

<p class=Normal><b>Notas:</b></p>

<p class=Normal>Traduzido do inglês por Gabriel N Laera a quem agradecemos por essa valiosa contribuição ao Dhamma.</p>


<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>



<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>