<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"desembaracando ");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO'," 5 Maio 2007 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'> Desembaraçando o Presente -<br> O Papel da Atenção com Sabedoria </Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'>Ajaan Thanissaro </Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>

<p class=Normal>&nbsp;</p>

<p class=Normal>Se os caminhos da mente fossem simples, os seus problemas seriam simples e fáceis de resolver. O Buda, ao mostrar como dar um fim a esses problemas, poderia ter dado instruções simples e breves – uma abordagem única para tudo aquilo que ocorrer no presente, um nobre caminho único: apenas atenção plena, apenas concentração, ou somente  atenção não-reativa. Ou ele poderia nem ter se preocupado muito em ensinar sabendo que as pessoas poderiam facilmente resolver os seus problemas por conta própria. “Confiem,” ele poderia dizer, “na sua natureza interior, no seu entendimento inato,” e deixado por isso mesmo. Mas não é assim que a mente funciona e não foi assim que ele ensinou. </p> 

<p class=Normal>Mesmo apenas alguns minutos gastos observando os caminhos da mente podem mostrar  quão complexos e enrolados eles são. E isso significa que os seus problemas também são complexos. Especialmente o problema do sofrimento: como o Buda advertiu, as causas do sofrimento são como um novelo embaraçado, como uma corda embolada cheia de nós. </p>

<p class=Normal>Qualquer pessoa que tenha solucionado problemas complexos sabe que o truque para encontrar a solução encontra-se no modo como a questão é formulada: identificar o problema e classificar o modelo dos fatores a ele relacionados. Vendo o modelo, você poderá decidir em quais fatores focar como decisivos para a solução e quais fatores devem ser ignorados para que você não seja desviado para becos sem saída. Formular a questão significa também decidir como abordar cada um dos fatores decisivos, de modo que, ao invés de manter ou exacerbar o problema eles auxiliem na solução. O que isso significa em resumo é, ao se defrontar com um problema, saber quais perguntas serão  benéficas e quais perguntas não serão. </p>

<p class=Normal>Se, por exemplo, você for um médico numa sala de emergências e o seu paciente estiver se queixando de dores no peito, você terá que tomar muitas decisões rapidamente. Você terá que decidir quais exames serão necessários, quais perguntas fazer ao paciente e quais sintomas físicos devem ser identificados antes de poder diagnosticar as dores como um sintoma de indigestão ou o começo de um ataque cardíaco, ou alguma outra coisa completamente diferente. Você também tem que decidir quais as perguntas que não devem ser feitas para não ser atrapalhado por  informações irrelevantes. Se você focar nos sintomas errados, o paciente poderá morrer – ou irá passar desnecessariamente mais uma noite na unidade de terapia intensiva, privando, assim, de um leito, um outro paciente que tenha de fato sofrido um ataque cardíaco. Uma vez feito o diagnóstico, você terá que decidir qual tratamento será adotado e como acompanhar o tratamento para ver se ele de fato está funcionando. Se os sintomas forem interpretados de modo equivocado você poderá causar mais dano que benefício. Se forem interpretados corretamente, você poderá salvar vidas. </p>  

<p class=Normal>O mesmo princípio se aplica na solução do problema do sofrimento, sendo que essa é a razão porque o Buda atribuiu uma importância capital à habilidade de interpretar a questão do sofrimento de modo apropriado. Ele chamou essa habilidade <i>yoniso manasikara</i> – atenção com sabedoria – e ensinou que nenhuma outra qualidade interior gera mais benefício para desenredar o sofrimento e conquistar a libertação (<a href="../sutta/It.16.php">It 16</a>).</p>

<p class=Normal>Ao proferir a explicação mais detalhada sobre a atenção com sabedoria (<a href="../sutta/MN2.php">MN 2</a>), o Buda começa com o exemplo da atenção sem sabedoria, que se centraliza nas questões de identidade e existência: “Eu existo?” “Não existo?” “O que sou?” “Existi no passado?” “Existirei no futuro?” Essas questões não são sábias porque elas conduzem a um “emaranhado de idéias, uma confusão de idéias,” tais como “Tenho um eu,” ou “Não tenho um eu,” todas as quais conduzem ao enredamento e nenhuma, ao fim do sofrimento. </p>

<p class=Normal>Em contraste, o Buda então descreve a atenção com sabedoria como a habilidade de identificar que “Isto é sofrimento,” “Esta é a origem do sofrimento,”  “Esta é a cessação do sofrimento,” “Este é o caminho que conduz à cessação do sofrimento.” Essas são as quatro categorias que o Buda, no seu primeiro discurso, chamou de quatro nobres verdades. A habilidade de interpretar a questão do sofrimento de acordo com essas categorias é aquilo que permite em última instância dar um fim ao problema do sofrimento de uma vez por todas. É por isso que esse tipo de atenção é sábia. </p>

<p class=Normal>A lição mais óbvia que pode ser extraída desse método para distinguir a atenção com sabedoria da atenção sem sabedoria é que a atenção sem sabedoria interpreta as questões da mente como categorias abstratas, enquanto que a atenção com sabedoria as interpreta como coisas que podem ser identificadas diretamente na experiência imediata como “Isto ... Esta … Esta … Este.” As idéias de identidade e existência são a base do pensamento abstrato e muitos filósofos têm argumentado que se encontram no fundamento de qualquer busca espiritual. O Buda, no entanto, observou que a idéia “Eu sou o pensador” encontra-se na raiz de todas as categorias e rótulos de proliferação conceitual, o tipo de idéia que pode se virar e atacar a pessoa que a está empregando. São categorias notoriamente difíceis de identificar com exatidão, dissolvendo-se freqüentemente numa semântica arbitrária. “Eu existo?” – depende do que você quer dizer com “existir.” “Tenho um eu?” – depende do que você quer dizer com “eu.” As idéias guiadas por esse tipo de definições, com freqüência, acabam sendo vítimas de motivos ou intenções dissimulados por trás das definições, significando que não são confiáveis. </p>

<p class=Normal>No entanto, o sofrimento é algo que pode ser conhecido diretamente: pré-verbal, pessoal, mas universal. Ao interpretar as questões da mente em torno do sofrimento, o Buda baseou os seus ensinamentos numa aspiração plenamente confiável – o desejo dos seus ouvintes de dar um fim a todo o sofrimento  – e focou em algo que não depende de definições. Na verdade, ele nunca oferece uma definição formal para o termo “sofrimento”. Ao invés disso, ele explica através de exemplos –  o sofrimento do nascimento, envelhecimento, enfermidade e morte – e depois aponta para o elemento funcional que é compartido por todas as formas de sofrimento mental: apego aos cinco agregados da forma, sensação, percepção, formações mentais e consciência. O apego não é a totalidade do sofrimento, mas é o aspecto do sofrimento mais útil para se focar com o propósito de dar um fim ao sofrimento. </p>

<p class=Normal>Embora exista um discurso no qual o Buda define o apego como desejo-cobiça (<a href="../sutta/SNXXII.121.php">SN XXII.121</a>), ele nunca descreve com precisão o que é desejo-cobiça. No que parece ser a parte mais antiga do Cânone, o Atthaka Vagga (<a href="../sutta/sutta_nipata.php#Quatro">Snp IV</a>), ele preenche uma longa discussão sobre o apego com trocadilhos e jogos de palavras, um estilo que desencoraja qualquer tentativa de sistematizar e definir, pela própria proliferação conceitual que isso gera. O que isso significa é que se você quiser aperfeiçoar o seu entendimento com relação ao apego, desejo-cobiça e sofrimento, você não poderá se apegar a palavras ou textos. Você tem de olhar de modo mais profundo para a sua experiência presente. </p>

<p class=Normal>No entanto, ao apontar repetidamente para a experiência direta, o Buda não desencoraja todo tipo de pensamento e conceitos. A habilidade para distinguir as quatro categorias da atenção com sabedoria requer pensamento e análise – o tipo de pensamento que questiona os entendimentos e desentedimentos passados e pondera sobre aquilo que está acontecendo no presente; o tipo de análise que é capaz de identificar conexões entre as ações e os seus resultados e pode avaliar se foram benéficas ou não. Por exemplo, há desejos que agem como causa do sofrimento e outros que podem formar parte do caminho que conduz ao seu fim. Embora o Buda ofereça um delineamento geral para indicar que tipo de desejo funciona de que modo, você deve aprender como observar os seus próprios desejos com cuidado e honestidade para identificar que tipo de desejo eles são. </p>

<p class=Normal>Ao prosseguir analisando o presente sob a perspectiva dessas quatro categorias, você estará  seguindo os passos do Buda à medida que ele se aproximava da iluminação. Tendo focado no apego como suporte funcional do sofrimento, ele investigou as condições que constituíam a sua base e as encontrou em três tipos de desejo ou sede: desejo pelos prazeres sensuais, desejo por estados de existência e desejo de destruir estados de existência. Depois ele identificou a cessação do sofrimento como o total desapego, a cessação e a libertação desse tipo de desejos. E ele identificou as qualidades mentais e práticas que conduziriam a essa cessação – entendimento correto, pensamento correto, linguagem correta, ação correta,  modo de vida correto, esforço correto, atenção plena correta e concentração correta – todos elas podem potencialmente ser encontradas no momento presente. </p> 

<p class=Normal>Portanto, ao invés de simplesmente jogar o momento presente em você como um todo monolítico, o Buda dirige a sua atenção para quatro coisas significativas que podem ser  encontradas ali. Isso porque há um padrão nas mudanças que experimentamos momento a momento. A mudança nunca é tão aleatória ou radical de modo que o conhecimento obtido no passado seja inútil no presente. Os conceitos ainda servem um propósito importante, muito embora possam estar carentes do frescor do aqui e agora imediato. Quando você enfia o dedo numa fogueira, é inevitável que você se queime. Se você cuspir contra o vento, é inevitável que volte na sua cara. É bom ter em mente lições como essas. Embora os padrões que sustentam o sofrimento possam ser mais enredados que aqueles por detrás do fogo e do vento, eles ainda assim são padrões. Isso pode ser aprendido e dominado e as quatro categorias da atenção com sabedoria são cruciais para compreender esses padrões e dirigi-los para o fim do sofrimento. </p> 

<p class=Normal>Em termos práticos, distinguir entre as categorias só vale a pena se você tiver que tratar cada categoria de modo distinto. Um médico que formula uma teoria de dezesseis tipos de dor de cabeça só para, por exemplo, tratá-las todas com aspirina, estará perdendo o seu tempo. Mas aquele que ao observar que diferentes tipos de dor de cabeça respondem a diferentes tipos de medicamentos, e aí desenvolver um teste acurado para diferenciá-las, estará fazendo uma genuína contribuição para a ciência médica. O mesmo princípio se aplica às categorias da atenção com sabedoria. Como o Buda declarou no primeiro relato da sua iluminação, uma vez que ele havia identificado cada uma das quatro categorias, ele viu que cada uma tinha de ser tratada de forma distinta. O sofrimento tinha de ser compreendido, a sua causa abandonada, a cessação realizada e o caminho para a sua cessação desenvolvido por completo. </p>

<p class=Normal>O que isso significa é que, como meditador, você não pode tratar tudo no momento presente do mesmo modo. Você não pode simplesmente permanecer não-reativo ou simplesmente aceitar tudo aquilo que vier. Se momentos de calma e tranqüilidade surgirem na mente, você não deve simplesmente notá-los e deixar que eles desapareçam. Você deve aprender como evoluí-los para os jhanas – a plenitude do êxtase e felicidade da concentração correta que constitui o núcleo do caminho. Quando o sofrimento mental surge, você não pode deixá-lo ir simplesmente. Você deve focar todo o poder de concentração e sabedoria que tiver no momento para tentar compreender o apego que se encontra por detrás daquilo. </p>

<p class=Normal>O Buda e os seus discípulos ampliam esse ponto em discursos nos quais eles mostram como a atenção com sabedoria deve ser aplicada aos vários aspectos do presente. Aplicada aos cinco agregados da forma, sensação, percepção, formações mentais e consciência, atenção com sabedoria significa vê-los de tal modo que  induza um senso de desencantamento que irá ajudar a aliviar o desapego (<a href="../sutta/SNXXII.122.php">SN XXII.122</a>). Aplicada às percepções de beleza ou irritação, significa vê-las de tal modo que impeça a alimentação dos obstáculos à concentração correta, assim como o desejo sensual ou a má vontade. Aplicada à sensação de tranqüilidade, o potencial para o êxtase, significa vê-la de tal modo que ajude a desenvolvê-la como um fator para a iluminação (<a href="../sutta/SNXLVI.51.php">SN XLVI.51</a>).</p>

<p class=Normal>Mesmo numa categoria em particular, não há apenas uma abordagem que funcione em todos os casos. Num dos discursos o Buda observa que alguns estados mentais inábeis enfraquecem  se você simplesmente observá-los com equanimidade, enquanto que outros requerem um esforço ativo para eliminá-los (<a href="../sutta/MN101.php">MN 101</a>). Num outro discurso, ele amplia essa observação recomendando cinco maneiras de lidar com os pensamentos que distraem: substituindo-os por pensamentos hábeis, focando nas suas desvantagens, ignorando-os conscientemente, relaxando a tensão necessária para mantê-los e suprimindo-os com a força (<a href="../sutta/MN20.php">MN 20</a>). Em nenhum discurso, no entanto, ele dá regras rígidas para dizer que tipo de pensamento irá responder a que tipo de abordagem. Você terá que descobrir por si mesmo qual abordagem funciona melhor. Você terá de descobrir por si mesmo afiando o seu discernimento através de tentativa e erro identificando o que funciona e o que não funciona numa determinada situação. </p>

<p class=Normal>O mesmo princípio se aplica aos estados mentais hábeis. O Buda resumiu o caminho da prática para o fim do sofrimento nos 37 apoios para a iluminação que estão agrupados em sete conjuntos – quatro fundamentos da atenção plena, quatro esforços corretos, quatro bases para o poder, cinco faculdades dominantes, sete fatores da Iluminação e o nobre caminho óctuplo. E mais uma vez, cabe a você aprender através de tentativa e erro qual o modo de conceber o caminho que será mais benéfico num determinado momento da sua prática. </p>

<p class=Normal>Isso significa que a aplicação da atenção com sabedoria aos estados mentais hábeis e inábeis não se resume numa única tentativa para que ela seja produtiva. <p class=Normal>As tarefas conectadas com cada uma das quatro categorias da atenção com sabedoria devem ser todas testadas através de tentativa e erro e serem aprendidas como uma técnica. Emprestando uma analogia do Cânone, a perfeita iluminação não é uma questão de tomar um arco e flecha e esperar que com sorte se acerte o alvo. O insight que conduz à iluminação ocorre através da prática num alvo, até que você seja “capaz de atirar a longas distâncias, atirar com precisão uma série rápida, e penetrar uma grande massa.” (<a href="../sutta/ANIX.36.php">AN IX.36</a>).</p>

<p class=Normal>Como observado pelo Buda no seu primeiro discurso, ele não reivindicou a perfeita iluminação até que tivesse  a completa maestria das tarefas apropriadas a todas as quatro categorias. Ao desenvolver por completo os fatores do caminho, ele compreendeu completamente os cinco agregados influenciados pelo apego ao ponto de abandonar todo desejo e cobiça por eles. Foi então que ele realizou o fim do sofrimento. Com isso, as categorias da atenção com sabedoria haviam realizado a sua tarefa na solução do problema do sofrimento, mas mesmo assim elas ainda tinham utilidade. Como afirmou o Ven. Sariputta, mesmo um arahant perfeitamente iluminado as aplica  para desfrutar de uma permanência prazerosa no aqui e agora. (<a href="../sutta/SNXXII.122.php">SN XXII.122</a>).</p>

<p class=Normal>Em todos esses casos, a atenção com sabedoria significa ver as coisas em relação à sua função – o que elas podem fazer – enquanto que o ato da atenção com sabedoria é em si mesmo um tipo de ação adotada em função daquilo que ela é capaz de fazer pela mente. E o teste para a atenção com sabedoria é que ela é na verdade eficaz no auxílio para dar um fim ao sofrimento. Quando comparamos isso com os exemplos do Buda para a atenção sem sabedoria, vemos que a atenção não é sábia quando interpreta as coisas como ser/existir e identidade, e é sábia quando as interpreta como ações e seus resultados. Na verdade, a atenção com sabedoria observa o ser/existir em si como uma ação, com cada ato de ser/existir, ou assunção de uma identidade, sendo avaliado pelo prazer ou dor que ele produz. Quando olhamos para nós mesmos com atenção com sabedoria, focamos não naquilo que somos, mas naquilo que estamos fazendo – e em particular se aquilo que estamos fazendo é inábil – conduzindo ao sofrimento – ou hábil, conduzindo ao seu fim. </p>

<p class=Normal>Este é um ponto importante para ter em mente quando refletimos nas duas críticas que com freqüência são formuladas contra as quatro categorias de atenção com sabedoria. A primeira crítica é que elas proporcionam uma visão limitada da riqueza e variedade da vida, que elas não abrangem o número praticamente infinito de meios hábeis de encarar as experiências. Ao formular uma teoria da existência, você poderia argumentar que quanto mais variedade ela contiver, tanto melhor. Mas ao escolher um médico, você não gostaria que ele insistisse em explorar uma infinidade de métodos para avaliar a sua enfermidade. Você quer alguém que foque nos métodos que têm mais probabilidade de funcionar. O mesmo se aplica à atenção com sabedoria. As quatro categorias, com as suas tarefas respectivas, não têm o propósito de abarcar a realidade, mas de focar a sua atenção nos fatores corretos para curar o problema existencial mais básico. O Buda limita a sua discussão a essas quatro categorias porque ele não quer que você se distraia do problema que está à vista. </p>

<p class=Normal>A segunda crítica é que as quatro categorias são dualistas e, portanto, inferiores a uma visão do mundo não dualista. Novamente, ao formular uma teoria da existência, você poderia argumentar, baseado na maior abrangência do conceito não dual de existência comparado com o dualista, que uma teoria não dualista seria superior a uma dualista e que, por conseguinte resultaria numa teoria mais unificada. Mas a atenção com sabedoria não é uma teoria da existência. É um guia para o que fazer no momento presente. Porque o momento presente é tão enredado e complexo, as múltiplas categorias oferecidas para a atenção com sabedoria são uma força ao invés de fraqueza. Ao invés de limitá-lo a um modo de compreensão e interpretação dos eventos no presente, elas proporcionam um entendimento mais perspicaz e uma variedade de opções sobre como lidar com os enredos e complexidades do sofrimento. </p>

<p class=Normal>Ao oferecer alternativas para solucionar um problema, em princípio, nenhuma quantidade de opções em particular é superior a qualquer outra. O que importa é que as opções sejam suficientemente adequadas para o problema, mas não em excesso de modo a obscurecer a solução e acabarem se convertendo elas mesmas num enredo. Em outras palavras, as opções têm de ser julgadas, não contra princípios abstratos, mas por aquilo que elas  capacitam-no a fazer. Embora o Buda descreva o seu caminho para o fim do sofrimento como a forma de fazer que em última instância dá um fim ao fazer, enquanto você estiver fazendo algo no momento presente, a atenção com sabedoria assegura que aquilo que você estiver fazendo permaneça como parte do caminho: você sabe quais são os fios do nó do sofrimento que devem ser puxados e quais devem ser deixados de lado. E uma vez que você desembaraçar o problema do sofrimento, todo o mais também será desembaraçado. </p>


<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>



<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>
