<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"essencia");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO',"2 Junho 2012 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'>A Essência do Budismo </Tit1>
<p class=Tit3 align=center style='text-align:center'> por </Tit3>
<p class=Tit2 align=center style='text-align:center'>Nyanatiloka Thera </Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>


<p class=Normal>Farei uma breve exposição da essência genuína do ensinamento do Buda tal como ainda encontramos nas escrituras budistas trazidas até nós na língua pali. [<a href="#N1">1</a>]       

<p class=Normal><a name=R1></a>Dentre os ouvintes, muitos não são budistas, o que torna o conhecimento do ensinamento original do Buda algo quase desconhecido. Não é preciso dizer que, para tais pessoas, não é possível adquirir um criterioso e completo entendimento de um tema tão amplo e profundo dentro do espaço de tempo limitado de minha fala. Ainda assim alguns de vocês talvez possam assimilar certas idéias que pareçam importantes; e estas talvez se revelem um estímulo para futuras investigações neste imenso e profundo universo de pensamento. Mesmo que estas palavras não tenham outro efeito além da remoção de pelo menos alguns dos muitos preconceitos e falsas idéias sobre a doutrina do Buda, isto já seria uma grande recompensa.</p>

<p class=Normal>Não parece irônico que tal doutrina religiosa – a mais sóbria de todas – seja ainda considerada por muitos ocidentais como uma forma de idolatria ou misticismo? O filósofo alemão Friedrich Nietzsche, vários anos atrás, entendeu e enfatizou a absoluta sobriedade e clareza do Budismo quando afirmou:</p>

<p class=Normal>"O Budismo é cem vezes mais realista que o Cristianismo. É herdeiro da tradição de dispor os problemas com frieza e objetividade. Veio à vida após centenas de anos de desenvolvimento filosófico. A noção de Deus é afastada logo de início. Oração é algo fora de questão. O mesmo vale para o ascetismo. Não há imperativo categórico. Nenhuma coerção, nem mesmo dentro da comunidade monástica. Portanto, não obriga a lutar contra aqueles de fé diferente. É um ensinamento que se volta vigorosamente contra o sentimento de vingança, animosidade e ressentimento." [<a href="#N2">2</a>]  <a name=R2></a></p>
 
<p class=Normal>Antes de dar início à exposição do ensinamento do Buda devemos nos familiarizar, ainda que brevemente, com a personalidade do Buda. O termo “Buda” significa literalmente “O Iluminado”. Tal nome foi adquirido pelo sábio indiano Gotama quando de sua iluminação aos pés da árvore figueira-dos-pagodes em Bodhgaya na Índia. Ele nasceu como filho de um rei indiano nas fronteiras do atual Nepal, por volta de 600 anos antes de Cristo. Aos 29 anos, ele renunciou a vida mundana e trocou sua carreira de príncipe pela de mendigo sem casa. Após seis anos de intenso esforço ele finalmente alcançou seu objetivo: libertação do ciclo de renascimentos ou Samsara. O Buda descreve este tempo em suas próprias palavras como segue:</p>

<p class=Normal>"Bhikkhus, antes de ter alcançado a plena iluminação, sendo eu mesmo sujeito ao nascimento, decadência, doença, morte, tristeza e impureza eu também buscava o que é sujeito ao  nascimento, decadência, doença, morte, tristeza e impureza. E assim bhikkhus, após algum tempo, enquanto ainda jovem, um moço de cabelos pretos, no primor da juventude, tendo recentemente ingressado na vida adulta, contra os desejos de mãe e pai que choravam e se lamentavam, eu cortei o cabelo e barba e, vestido com o manto amarelo, sai da vida de casa para a vida sem lar. Assim consagrado à vida sem lar, eu me esforçava em busca do bem mais elevado, o incomparável caminho para a suprema paz." [<a href="#N3">3</a>]  <a name=R3></a>  </p>

<p class=Normal>Num primeiro momento o futuro Buda aprendeu com dois grandes yogis que haviam alcançado níveis elevados de mente e poderes psíquicos. Mas nenhum deles o satisfez, pois seus ensinamentos não conduziam à paz infinita e libertação da mente. Então ele os abandonou após ter realizado seus ensinamentos completamente. Depois disso, ele encontrou cinco ascetas, que praticavam as formas mais severas de mortificação e tortura da carne esperançosos de conseguir por este caminho a libertação. O futuro Buda tornou-se um deles. Ele sujeitou-se com máxima perseverança aos extremos do jejum e da auto-mortificação até que ficasse parecido com um esqueleto. Completamente exausto, ele sucumbiu, ruiu. Assim, ele veio a entender que a mortificação do corpo é vã e inútil, e nunca irá conduzir à paz do coração e à libertação. Desse momento em diante ele desistiu do jejum e das mortificações, enxergando refúgio no desenvolvimento mental e moral. Com uma mente calma e serena, ele começou a investigar a verdadeira natureza da existência.</p>
<p class=Normal>Para onde quer que ele voltasse os olhos, via apenas uma realidade: a lei do sofrimento, a insatisfatoriedade de todas as formas de existência. Ele compreendeu que o destino dos seres não é o resultado de acaso cego, nem depende da ação arbitrária de um criador imaginário, mas que nosso destino deve ser traçado de volta até as nossas ações ou kamma. Ele observou o doente e o leproso, e viu em sua miséria e sofrimento apenas o resultado de ações, ou kamma, feitas em vidas anteriores. Ele observou o cego e o aleijado e viu em sua debilidade e desamparo apenas a colheita dolorosa das sementes plantadas por eles em outras vidas. Ele observou o rico e o pobre, o feliz e o infeliz; e para onde quer que voltasse os olhos viu esta lei de retribuição, a lei moral da causa e efeito, o Dhamma.</p>

<p class=Normal>Este Dhamma, ou lei moral universal descoberto pelo Buda, pode ser resumido nas Quatro Nobres Verdades: as verdades acerca do domínio universal do sofrimento, sua origem, extinção e o caminho que leva a sua extinção.</p>

<p class=Normal> (I)	A primeira verdade, sobre a universalidade do sofrimento, afirma, de modo breve que todas as formas de existência são necessariamente sujeitas ao sofrimento.</p>
<p class=Normal> (II) A segunda verdade, sobre a origem do sofrimento, afirma que todo sofrimento está enraizado no desejo egoísta e na ignorância, em <i>tanha</i> e <i>avijja</i>. A causa dessa aparente injustiça se explica afirmando que nada no mundo pode vir a existir sem razão ou causa; não somente nossas tendências latentes, mas nosso destino inteiro, todo açoite e todo pesar, resultam de causas que devemos buscar parcialmente nessa vida, parte em estados anteriores de existência. A segunda verdade ensina além disso que a vida futura, com seu quinhão de açoite e pesar, deve resultar das sementes plantadas nesta e em vidas anteriores.</p>
<p class=Normal> (III) A terceira verdade, ou verdade acerca da extinção do sofrimento, mostra como, mediante a extinção do desejo e ignorância, todo sofrimento irá desaparecer e a libertação deste Samsara será alcançada.</p>
<p class=Normal> (IV) A quarta verdade mostra o caminho pelo meio do qual este objetivo é atingido. Trata-se do Nobre Caminho Óctuplo, ou seja, entendimento correto, pensamento correto, linguagem correta, ação correta, modo de vida correto, esforço correto, atenção plena correta e concentração correta.</p>

<p class=Normal>A partir dessas Quatro Nobres Verdades iremos esclarecer alguns pontos essenciais para uma compreensão geral do Dhamma. Ao fazer isso, estaremos ao mesmo tempo refutando um grande número de preconceitos largamente espalhados quanto ao ensinamento do Buda.</p>

<p class=Normal>Antes disso, porém, vamos esboçar o Nobre Caminho Óctuplo, pois este é o caminho de retidão e sabedoria que constitui a essência da prática budista – o modo de vida e pensamento a ser adotado por qualquer seguidor verdadeiro do Buda.</p>

<p class=Normal> (1) O primeiro estágio do Caminho Óctuplo, como mencionado antes, é o entendimento correto, isto é, entendimento da verdadeira natureza da existência, bem como das lei morais que a governam. Em outras palavras, é o entendimento correto do Dhamma, ou seja, das Quatro Nobres Verdades.</p>
<p class=Normal> (2) O segundo estágio do Caminho Óctuplo é o pensamento correto, isto é, um puro estado da mente, livre de desejo sensual, má vontade e crueldade; em outras palavras, pensamentos de auto-renúncia, bondade e misericórdia.</p>
<p class=Normal> (3) O terceiro estágio é linguagem correta. Consiste em palavras que não são falsas, ríspidas, nem escandalosas ou frívolas, ou seja, palavras verdadeiras, pacificadoras e sábias.</p>
<p class=Normal> (4) O quarto estágio é a ação correta, ou seja, abster-se de intencionalmente matar ou ferir seres vivos, abster-se de tomar desonestamente a propriedade de outros, abster-se de cometer adultério.</p>
<p class=Normal> (5) O quinto estágio é o modo de vida correto, isto é, um meio de vida tal que não traga prejuízo e sofrimento para outros seres.</p>
<p class=Normal> (6) O sexto estágio é o esforço correto. Trata-se do esforço quádruplo que fazemos para superar e evitar novas más ações do corpo, linguagem e mente; e o esforço feito para desenvolver novas ações de retidão, sabedoria e paz interior e de cultivá-las até a perfeição.</p>
<p class=Normal> (7) O sétimo estágio é a atenção plena correta, ou vigilância da mente. Trata-se da sempre pronta clareza mental, operando em relação a qualquer coisa que estejamos fazendo, falando e pensando; e de manter em nossa mente as realidades da existência, a saber, impermanência, insatisfatoriedade e fenomenalidade [<a href="#N4">4</a>]  <a name=R4></a> - não-eu, (<i>anicca, dukkha, anatta</i>), de todas as formas de existência. </p> 
<p class=Normal> (8) O oitavo estágio é a concentração correta. Este tipo de concentração se dirige a um objeto moralmente saudável e sempre está ligada com pensamento, esforço e atenção plena corretas.</p>

<p class=Normal>Portanto, o Caminho Óctuplo é um caminho de virtude (<i>sila</i>), de treinamento mental (<i>samadhi</i>) e de sabedoria (<i>pañña</i>).</p>

<p class=Normal>A Virtude nesse sentido é indicada pela linguagem correta, ação correta e modo de vida correto. O Treinamento mental é indicado pelo esforço correto, atenção plena correta e concentração correta. A sabedoria é indicada pelo entendimento correto e pensamento correto.</p>

<p class=Normal>Assim, este libertador Caminho Óctuplo é um caminho de cultura interior, de progresso interior. Apenas pela adoração externa, cerimônias e preces egoístas nunca se fará qualquer progresso real no caminho da retidão e insight. O Buda diz: “Seja sua própria ilha de refúgio, seja seu próprio abrigo, não busque por nenhuma outra proteção! Deixe que a verdade seja sua ilha de refúgio, que a verdade seja seu abrigo, não busque por nenhuma outra proteção!”. Para que se tenha eficácia real, para assegurar um progresso interior absoluto, todos os nossos esforços devem se basear em nosso próprio entendimento e insight. Todo progresso interior absoluto está enraizado no entendimento correto, sem entendimento correto não há a realização da perfeição e a inabalável paz de Nibbana.</p>

<p class=Normal>A crença na eficácia moral do mero ritual ou cerimônia (<i>silabbata-paramasa</i>) constitui, de acordo com o ensinamento do Buda um poderoso obstáculo ao progresso interior. Alguém que toma refúgio em práticas meramente externas está no caminho errado. Pois, para que se consiga progresso interior real, todos os nossos esforços devem necessariamente se basear em nosso próprio entendimento e insight. Qualquer progresso real se enraíza no entendimento correto, sem este não há realização da paz e santidade inabaláveis. Além do mais, esta crença cega em práticas meramente externas é a causa de muita miséria e infelicidade no mundo. Conduz a uma estagnação mental, ao fanatismo e intolerância, auto-exaltação e desprezo pelos outros, contendas, discórdias, guerra, disputas e derramamento de sangue, como a história da Idade Média dá suficiente testemunho. Uma tal crença embota e enfraquece a capacidade de pensar, sufoca no ser humano qualquer emoção elevada, transformando-o num escravo mental e favorecendo o crescimento de todos os tipos de hipocrisia.</p>
 
<p class=Normal>O Buda se expressou de modo claro e positivo quanto a este ponto. Ele disse: “o homem imerso na ilusão nunca irá se purificar pelo mero estudo de livros sagrados ou sacrifícios a Deus, jejuns, dormir no chão, vigílias difíceis e cansativas ou repetição de orações. Tampouco presentes dados a sacerdotes, autoflagelações, execução de ritos e cerimônias podem purificar aquele que é cheio de desejo. Não é pelo consumo de carne ou peixe que o homem se torna impuro, e sim pela embriaguez, obstinação, fanatismo, engodo, inveja, auto-exaltação, desprezo pelos outros e más intenções – são estas coisas que tornam o homem impuro.”</p>

<p class=Normal> “Existem dois extremos: inclinação para os prazeres sensuais e inclinação para a mortificação do corpo. Tais extremos foram rejeitados pelo Perfeito, que descobriu o Caminho do Meio, que produz visão e conhecimento, que conduz à paz, à penetração libertação e iluminação. Este Nobre Caminho Óctuplo que conduz ao fim do sofrimento, a saber, entendimento correto, pensamento correto, fala correta, meio de vida correto, esforço correto, plena atenção correta e concentração da mente correta.” [<a href="#N5">5</a>]  <a name=R5></a></p>  

<p class=Normal>Uma vez que o Buda ensina que todo progresso genuíno no caminho da virtude é necessariamente dependente de nossa própria compreensão e insight, todo dogmatismo é excluído do ensinamento do Buda. O Buda rejeita a fé cega em autoridades, algo completamente oposto ao espírito do ensinamento. No Kalama Sutta o Buda diz:</p>

<p class=Normal>"Não sigam meramente por ouvir dizer ou por tradição, pelo que foi trazido a vocês de tempos antigos, por rumores, por mero raciocínio e deduções lógicas, aparências externas, por opiniões e especulações estimadas, por meras possibilidades, e não acreditem somente porque eu sou seu mestre. Mas, quando por vocês mesmos, tiverem visto uma coisa como algo mau e que conduz ao sofrimento e prejuízo, então devem rejeitar isto. E quando perceberem que uma coisa é boa e inofensiva, e conduz a bênçãos e bem-estar, então vocês devem praticar tal coisa." [<a href="#N6">6</a>]  <a name=R6></a>
</p>
 
<p class=Normal>O Buda compara alguém que apenas acredita ou repete o que outros descobriram com um cego. Aquele que deseja fazer progresso no caminho da libertação deve experimentar e entender a verdade por si mesmo. Sem o próprio entendimento, progresso algum é possível.</p>

<p class=Normal>O ensinamento do Buda é, talvez, a única religião que não exige crença em uma tradição, ou em certos eventos históricos. Apela somente para o entendimento de cada um. Onde quer que existam seres capazes de pensar, lá as verdades proclamadas pelo Buda poderão ser entendidas e realizadas, independente de raça, país, nacionalidade ou classe social. Estas verdades são universais, não estão ligadas a um país ou época em particular. E em qualquer um, mesmo no mais humilde, jaz latente a capacidade para ver e realizar estas verdades, e alcançar a mais alta Perfeição. Quem quer que viva uma vida nobre, sente já um gosto da verdade e, em maior ou menor grau, trilha o Nobre Caminho Óctuplo da Paz que todos os nobres e santos trilharam, estão trilhando e trilharão no futuro. As leis universais da moralidade sustentam o bem sem variações em todos os lugares e tempos, independente de alguém se dizer budista, hindu, cristão ou muçulmano, ou qualquer outro nome que seja.</p>

<p class=Normal>É a condição interna de uma pessoa e suas ações que contam, não um simples nome. O verdadeiro discípulo do Buda se coloca distante de todo dogmatismo. Ele é um livre pensador no mais elevado sentido do termo. Não segue dogmas positivos nem negativos, pois ele sabe: ambos não passam de meras opiniões, visões, enraizadas na cegueira e no auto-engano. O Buda disse acerca de si mesmo: O Perfeito é livre de qualquer teoria, pois o Perfeito viu: assim é a forma, assim ela surge, assim ela se vai; assim é a sensação, assim ela surge, assim ela se vai; assim é a percepção, assim ela surge, assim ela se vai; assim são as formações mentais, assim elas surgem, assim elas se vão; assim é a consciência, assim ela surge, assim ela se vai.</p>

<p class=Normal>I. Esta importante verdade da fenomenalidade e vazio de toda existência pode e deve ser entendida por qualquer pessoa, por seus próprios esforços.</p>

<p class=Normal>De acordo com o ensinamento do Buda a existência individual nada mais é do que um processo de fenômenos físicos e mentais, um processo que acontece desde tempos imemoriais, muito antes  deste nascimento aparente, e que vai continuar depois da morte por um período de tempo imemorial. No que segue veremos que os cinco khandas mencionados acima, os grupos da existência, não constituem nenhuma entidade real, ou ego – <i>atta</i>, e que nenhuma entidade-ego existe separada deles, portanto, a crença em uma entidade-ego é uma ilusão.</p>

<p class=Normal>Aquilo que chamamos de nosso corpo físico é, na verdade, um nome para uma combinação multifacetada de partes componentes que na realidade não constituem uma entidade ou personalidade. Isto é claro para todos, sem necessidade de mais argumentos. Todos sabem que o corpo muda momento a momento, que velhas células estão continuamente morrendo e outras nascendo; em síntese, que o corpo, será completamente outro corpo depois de alguns anos, que nada permanecerá da carne, sangue e ossos, etc. Conseqüentemente o corpo do bebê não é o corpo do menino e o do jovem não é o corpo do velho de cabelos grisalhos. Logo, o corpo não é um algo que persiste, mas antes um processo contínuo de surgimento e perecimento, consistindo de um perpétuo perecer e surgir de novas células. Aquilo que chamamos de nossa vida mental, por seu turno, é um processo contínuo de mudanças de sentimentos, percepções, formações mentais e estados de consciência. Neste momento um sentimento agradável surge, no seguinte, um doloroso; neste momento um estado de consciência, noutro um novo estado de consciência. Aquilo que chamamos de ser, indivíduo, uma pessoa, não possui por si mesmo, como tal, nenhuma realidade independente. Em sentido absoluto (<i>paramattha</i>) nenhum indivíduo ou pessoa está lá para ser encontrado, tudo que há é a perpétua mudança na combinação dos estados físicos, sentimentos, volições e estados de consciência.</p>

<p class=Normal>O que chamamos de “carruagem” não tem existência separada e independente do eixo, rodas, cabos, etc. O que chamamos “casa” é apenas um nome conveniente para pedras, madeira e ferros, dispostos de uma certa maneira, de modo a cercar uma porção de espaço, mas uma entidade casa como tal, separada, não existe.</p>

<p class=Normal>Precisamente do mesmo modo, o que chamamos de “ser”, “indivíduo”, “pessoa”, ou de “eu” ou “ele”, etc., é apenas a combinação mutante de fenômenos físicos e mentais que não tem existência real, em si mesmo.</p>

<p class=Normal>As palavras “eu”, “você”, “ele”, etc., são apenas termos úteis em nossa fala corrente (<i>vohara</i>) ou  convencional que não designam realidades (<i>paramattha-dhamma</i>). Os fenômenos mentais e físicos não constituem uma entidade-ego, nem tampouco existe algo fora desses fenômenos que possa ser chamado de entidade-ego, eu ou alma, que seja possuidor ou dono do corpo. Assim, quando as escrituras budistas falam de pessoas, ou mesmo do renascimento de pessoas, fala-se nesses termos para facilitar o entendimento, não devemos tomar estas afirmações no sentido de uma verdade última. O assim chamado “ser” ou “eu” em sentido absoluto não é nada além de um processo em perpétua mudança. Portanto, falar do sofrimento de uma “pessoa”, é em sentido absoluto incorreto. Pois não se trata de uma pessoa, mas sim de um processo físico-mental sujeito a transitoriedade e sofrimento.</p>

<p class=Normal>Em sentido absoluto temos apenas processos sem fim, incontáveis ondas de vida no oceano sempre mutável dos estados mentais, sentimentos, percepções, volições e estados de consciência. Dentro destes fenômenos nada há de persistente, nem mesmo pela curta duração de dois momentos consecutivos.</p>

<p class=Normal>Tais fenômenos possuem uma duração momentânea. Eles morrem a cada momento, e a cada momento novos fenômenos nascem; um morrer e nascer sem fim, um incessante movimento das ondas. Tudo está em perpétuo fluxo; “panta rhei” - todas as coisas estão fluindo – disse o filósofo grego Heráclito. As velhas formas caem em pedaços, novas nascem. Um sentimento desaparece, outro vem em seu lugar. Um estado de consciência existe nesse momento, um outro no momento seguinte. Tudo se encontra numa perpétua mudança de fenômenos mentais e materiais. Desse modo, um momento segue o outro, um dia segue o outro, os anos se seguem uns aos outros, uma vida segue a outra. E assim este incessante processo de mutação prossegue por milhares de anos, mesmo por aeons. Um oceano eterno de sentimentos, percepções, volições e estados de consciência que surgem e perecem, tal é a existência, tal é o Samsara, o mundo do surgir e perecer, do crescimento e da decadência, um mundo de tristeza, miséria, lamentação e desespero.</p>

<p class=Normal>Sem um verdadeiro insight dessa fenomenalidade, ou ausência de eu (egolessness) ou impessoalidade (<i>anatta</i>) de toda existência, será impossível entender apropriadamente as Quatro Nobres Verdades.</p>

<p class=Normal>II. Em conexão com isso, voltemos para a segunda nobre verdade, a origem do sofrimento enraizada no desejo egoísta e na ignorância (<i>tanha e avijja</i>). De modo a compreender melhor esta verdade, será preciso falar de uma doutrina freqüentemente incompreendida e mal interpretada. Trata-se da doutrina budista do renascimento (vejam capítulo II). Com relação a este ensinamento, o Budismo é freqüentemente acusado de ser contraditório. Se diz que o Budismo, por um lado nega a existência da alma e por outro ensina a transmigração da alma. Nada pode ser mais equivocado do que isso, pois o Budismo não ensina transmigração nenhuma. A doutrina budista do renascimento – que em realidade é a mesma lei da causalidade estendida aos domínios moral e mental – nada tem a ver com a doutrina bramanista da reencarnação ou transmigração. Existe uma diferença fundamental entre estas doutrinas.</p>

<p class=Normal>De acordo com o ensinamento bramanista, existe uma alma independente do corpo que, após a morte, deixa o envelope físico e vai para um novo corpo, de modo semelhante a alguém que joga fora uma roupa velha e veste uma nova. Completamente diferente, entretanto, é a doutrina budista do renascimento. O Budismo não reconhece nesse mundo nenhuma existência de mente separada da matéria. Todos os fenômenos mentais são condicionados pelos meios dos sentidos e não podem existir sem eles. De acordo com o Budismo, mente sem matéria é uma impossibilidade. E como vimos, os fenômenos mentais, assim como os corpóreos, são sujeitos a mudança e nenhum elemento persistente, ou entidade-ego ou alma está lá para ser descoberto. Logo, onde não há entidade imutável ou alma, não se pode falar em transmigração.</p>

<p class=Normal>Então como é possível renascimento sem algo que renasça, sem um ego ou alma? Aqui devo mencionar que mesmo a palavra “renascimento”, neste contexto, não é, de fato, correta, mas usada como um mero recurso didático. O que o Buda ensina é, corretamente falando, a lei de causa e efeito operando no domínio moral. Pois, assim como tudo no mundo físico acontece de acordo com leis, como o surgimento de qualquer estado físico depende de um estado precedente como causa, assim esta vida físico-mental presente depende de causas anteriores ao seu nascimento. Desta forma, segundo o Budismo, o presente processo vital é o resultado do desejo pela vida num nascimento prévio, e o desejo pela vida neste nascimento é a causa da continuidade do processo vital depois da morte.</p>

<p class=Normal>Mas, como não há nada que persiste de um momento de consciência para outro, também não há elemento contínuo a existir neste processo vital sempre mutante que passe de uma vida para a outra.</p>
<p class=Normal>Nada transmigra deste momento para o próximo, nem desta vida para uma próxima. Este processo de ser continuamente produzido e produzir pode ser comparado a ondas no oceano. No caso da onda, não há a menor quantidade de água que viaje de fato pela superfície do oceano. A estrutura de onda que parece correr pela superfície da água, embora crie a aparência de uma mesma massa de água, de fato nada mais é além do contínuo surgir e desaparecer de novas massas d'água. Este surgir e perecer é produzido pela transmissão de força gerada originalmente pelo vento. De modo similar, o Buda não ensina que existe uma entidade-ego ou alma que percorre o oceano do renascimento, mas que na realidade o que temos é somente uma vida-onda que, conforme sua natureza e atividades, aparece aqui como homem, ali como mulher e alhures como um ser invisível.</p>

<p class=Normal>III. Existe um outro ensinamento do Buda que freqüentemente dá origem a sérios equívocos. É o ensinamento de Nibbana, ou extinção do sofrimento. Esta terceira nobre verdade aponta que, através da cessação de todo desejo egoísta e toda ignorância, necessariamente todo sofrimento tem um fim, se extingue e novos nascimentos não terão lugar. Pois se a semente é destruída, não pode brotar novamente. Se o desejo egoísta que faz com que nos agarremos convulsivamente à vida é destruído, após a morte não ocorrerá um novo momento, a continuação deste processo de existência, o que se chama de renascimento. Onde não há nascimento, não há morte. Onde não há surgir, não há perecer. Onde não existe vida, não pode haver sofrimento. Agora, devido à extinção do desejo egoísta, todos os fenômenos correlatos tais como presunção, busca de uma identidade, cobiça, raiva, ódio, crueldade também se extinguem. Esta liberdade do apego egoísta significa o mais elevado estado de abnegação, sabedoria e santidade.</p>

<p class=Normal>Uma vez que, depois da morte do Santo, do Arahat, o processo físico-mental não mais continua, é comum interpretar tal evento equivocadamente como significando a aniquilação de um eu, de um ser real, e por isso se diz que o objetivo seria simplesmente a aniquilação. Deve-se protestar enfaticamente contra tal afirmação equivocada. Como é possível falar da aniquilação de um eu, alma, ego, onde tal coisa não se encontra? Vimos que na realidade não existe nenhuma entidade-ego ou alma, portanto, também nenhuma “transmigração” desta coisa para um novo útero.</p>

<p class=Normal>O novo processo corpóreo que começa no útero da mãe sem dúvida é a continuação de um prévio processo corpóreo, mas somente um resultado ou efeito, causado pelo desejo egoísta e apego pela vida do indivíduo moribundo. Deste modo, aquele que sustenta que a não-produção de um novo processo vital é idêntico à aniquilação de um eu deveria dizer também que abstenção de intercurso sexual é o mesmo que aniquilação de uma criança – o que é, claro, absurdo.</p>

<p class=Normal>Aqui, uma vez mais, devemos enfatizar que sem uma percepção clara da fenomenalidade ou ausência de ego (egolessness, <i>anatta</i>) de toda existência, será impossível obter uma real compreensão do ensinamento do Buda, especialmente aquele sobre renascimento e Nibbana. Este ensinamento de <i>anatta</i> é de fato a única doutrina caracteristicamente budista com a qual todo ensinamento se sustenta ou desaba.</p>
<p class=Normal>Outra crítica muito ouvida contra o Budismo é a de que ele seria um ensinamento melancólico e pessimista. Pelo que foi dito até aqui, tal crítica se revela sem fundamento. Afinal, como foi visto, o Buda não apenas mostra e explica o fato da miséria, ele também apresenta um caminho para que achemos total liberação dela. A partir disto, podemos dizer que o ensinamento do Buda é o mais ousado otimismo proclamado no mundo.</p>

<p class=Normal>Em verdade, o Budismo é um ensinamento que assegura esperança, conforto e felicidade, mesmo para o menos afortunado. É um ensinamento que oferece, mesmo para o mais vil dos criminosos prospectos de perfeição e paz finais. Nada disso com base em fé cega, preces, ascetismo, cerimônias superficiais, ritos e rituais, mas sim por seguir de modo cuidadoso e perseverante o Nobre Caminho Óctuplo para purificação interior, pureza e emancipação do coração que consiste de entendimento correto, pensamento correto, linguagem correta, ação  correta, modo de vida correto, atenção plena correta e concentração e paz da mente correta.</p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>
 
<p class=Normal><b>Notas:</b></p>

<p class=Normal><a name=N1></a> [1] Conferência transmitida pelo rádio em Colombo, 1933. [<a href="#R1">Retorna</a>] </p>

<p class=Normal><a name=N2></a> [2] O Anticristo. Parágrafo 20, excertos. [<a href="#R2">Retorna</a>] </p>

<p class=Normal><a name=N3></a> [3] <a href="../sutta/MN26.php#T13">MN 26.13</a> - Seguindo a tradução do autor. [<a href="#R3">Retorna</a>] </p>

<p class=Normal><a name=N4></a> [4] Esclarecedor aqui o uso de fenomenalidade (phenomenality em inglês) como tradução para <i>anatta</i>. A palavra fenômeno vem do grego e significa aquilo que é percebido, aquilo que é observado como um dado da experiência. O filósofo Immanuel Kant introduz este sentido de fenômeno e opõe a fenômenos o que ele chama de númeno ou coisa-em-si (Ding an sich). Neste sentido fenomenalidade parece uma boa escolha para <i>anatta</i>, afinal a idéia de <i>anata</i> é de que não há nada por trás daquilo que aparece como sendo uma pessoa, ou seja, uma alma oculta. Não somos um ser mas sim um parecer. Uma epistemologia que não postula entidades absolutas e imutáveis por trás dos fenômenos ou aparências é chamada de fenomenista, termo que freqüentemente é associado por estudiosos diversos ao Budismo. (nota do tradutor) [<a href="#R4">Retorna</a>] </p>

<p class=Normal><a name=N5></a> [5] <a href="../sutta/SNLVI.11.php">SN LVI.11</a> - Seguindo a tradução do autor. [<a href="#R5">Retorna</a>] </p>

<p class=Normal><a name=N6></a> [6] <a href="../sutta/ANIII.65.php">AN III.65</a> - Seguindo a tradução do autor. [<a href="#R6">Retorna</a>]


<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>



<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>

