<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"kamma_renascimento");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO',"16 Abril 2013 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'><i>Kamma</i> e Renascimento  [<a href="#N1">1</a>] <a name=R1></a></Tit1>

<p class=Tit3 align=center style='text-align:center'> por </Tit3>

<p class=Tit2 align=center style='text-align:center'>Nyanatiloka Thera </Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>
<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>


<p class=Normal>Quando se contempla o mundo e pensa-se acerca do destino dos seres, para muitas pessoas parece que tudo na natureza é injusto. Por que, pode-se perguntar, uma pessoa é rica e poderosa e outra pobre e aflita? Por que alguém leva uma vida boa e saudável enquanto outro desde o nascimento é doente e fraco? Por que uns são dotados de aparência agradável, inteligência e sentidos perfeitos enquanto outros são feios e repulsivos, mentalmente deficientes, cegos, surdos e mudos? Por que uma criança nasce em meio à miséria mais completa e cercada de pessoas vis, criada como criminosa, enquanto outra nasce cercada de fartura e conforto, filha de pais de mente nobre, e desfruta todas as vantagens de um tratamento agradável, a melhor educação mental e moral, e vê tão somente boas coisas ao seu redor? Por que alguns, freqüentemente sem o mínimo esforço, são bem sucedidos em todos os seus empreendimentos, enquanto todos os planos de outra pessoa falham? Por que alguns vivem no luxo enquanto outros vivem na pobreza e na aflição? Por que uns são felizes e outros infelizes? Por que alguns vivem uma longa vida, enquanto outros  são levados pela morte no auge da vida? Por que as coisas são desse modo? Por que tais diferenças existem na natureza?</p>

<p class=Normal>Dentre todas as circunstâncias e condições que constituem o destino de um ser, nenhuma, de acordo com o ensinamento do Buda, pode vir a existir sem causa prévia e sem a presença de um número de condições necessárias. Assim como, por exemplo, de uma semente podre de manga nunca surgirá um pé de manga com frutos doces e saudáveis, do mesmo modo más ações volitivas ou mau <i>kamma</i>, produzido em nascimentos prévios, são as sementes ou causas-raízes de um destino ruim num nascimento posterior. É um postulado necessário do pensamento que o destino bom e ruim de um ser, bem como seu caráter latente, não pode ser o produto de mero acaso, mas necessariamente tem suas causas num nascimento prévio.</p>

<p class=Normal>De acordo com o Budismo, nenhuma entidade orgânica, física ou psíquica, pode vir à existência sem uma causa prévia, isto é, sem um estado apropriado precedente a partir do qual se desenvolva. De modo semelhante, nenhuma entidade orgânica pode jamais ser produzida por algo externo a si mesma. [<a href="#N2">2</a>]<a name=R2></a> Esta pode originar-se apenas de si mesma, isto é, deve existir desde já no embrião. Para ser preciso, além desta causa e condição-raiz, ou semente, existem ainda muitas condições menores requeridas para seu efetivo surgimento e desenvolvimento, assim como o pé de manga, além de sua causa principal – a semente – requer para que germine, cresça e se desenvolva outras condições como água, terra, luz, calor, etc. Deste modo, a causa verdadeira do nascimento de um ser, junto com seu caráter e destino, remonta às volições kâmmicas produzidas num nascimento anterior.</p>

<p class=Normal>De acordo com o Budismo, existem três fatores necessários para o renascimento de um ser humano, ou seja, para a formação de um embrião no útero materno. São eles: o óvulo da fêmea, o esperma do macho e a energia-do-karma (<i>kammavega</i>), que nos suttas é chamado metaforicamente de <i>"gandhabba"</i>, isto é, "espírito" ou "alma". Esta energia do <i>kamma</i> projeta-se do indivíduo moribundo no momento da morte. O pai e a mãe fornecem apenas material físico necessário para a formação do embrião. No que diz respeito aos traços característicos, as tendências e faculdades latentes no embrião podem ser explicadas pelo ensinamento do Buda da seguinte maneira: o moribundo, com todo seu ser convulsivamente apegado à vida, no momento exato da morte emite as energias kâmmicas que, como um raio de luz, atingem o útero pronto para a concepção. Assim, mediante o encontro entre energias kâmmicas, esperma e óvulo, surge a célula-ovo como um precipitado. [<a href="#N3">3</a>]   

<p class=Normal><a name=R3></a>Podemos comparar este processo com as vibrações do ar produzidas pela fala, que, ao atingir o órgão auditivo de outro ser humano produzem som, que é uma sensação puramente objetiva. Neste caso, não ocorre uma transmigração do som, mas apenas uma transferência de energia, chamada de vibração do ar. De modo similar, a energia do <i>kamma</i>, emitida pelo moribundo, produz, a partir do material fornecido pelos pais, o novo ser embrionário. Mas nenhuma transmigração de um ser real, ou entidade-alma ocorre nessa ocasião, simplesmente a transmissão da energia kâmmica.</p>

<p class=Normal>Portanto, podemos dizer que o atual processo vital (<i>upapatti-bhava</i>) é a objetificação do correspondente processo kâmmico pré-natal. Assim, nada transmigra de uma vida para outra. E aquilo que chamamos nosso ego é na verdade apenas o processo contínuo de mudança, de contínuo surgir e perecer. Os momentos, pois, seguem-se uns aos outros, dia após dia, ano após ano, vida após vida. Exatamente como a onda, que aparentemente corre pela superfície do lago, não passa de contínuo surgir e desaparecer de sempre novas massas d’água, cada momento renovado pela transmissão de energia, quando visto de perto e em sentido último, não representa uma entidade-ego que passa pelo oceano do <i>samsara</i>, mas apenas um processo de fenômenos físicos e psíquicos que ocorre sempre de novo, movido pelo apego à vida.</p>

<p class=Normal>É sem dúvida verdade que a condição mental dos pais, no momento da concepção, tem influência considerável sobre o caráter do ser embrionário, e que a natureza da mãe pode produzir grande impressão no caráter do ser que ela carrega no ventre. A unidade indivisível da individualidade psíquica da criança, entretanto, não pode ser produzida pelos pais. Não se deve aqui confundir a causa efetiva – estado anterior a partir do qual o atual estado surge – com as influências e condições externas.  Se fosse realmente o caso que o novo indivíduo, como unidade inseparável, fosse o produto dos seus pais, gêmeos nunca exibiriam tendências totalmente opostas. Em tal caso, crianças e especialmente gêmeos possuiriam, sem exceção, o mesmo caráter dos pais.</p>
 
<p class=Normal>Em todos os tempos e países da terra, a crença no renascimento foi sustentada por muitas pessoas; esta crença deriva de um instinto ou intuição que jaz dormente em todos os seres. Em todos os tempos grandes pensadores ensinaram a continuidade da vida após a morte. Desde tempos imemoriais alguns ensinavam acerca da metempsicose [<a href="#N4">4</a>]<a name=R4></a>, ou seja, transformação da alma, ou metamorfose, ou transformação do corpo, etc., como por exemplo, as doutrinas esotéricas do Egito antigo, Pitágoras, Empédocles, Platão, Plotino, Píndaro, Virgílio, bem como algumas tribos africanas. Muitos pensadores modernos também ensinam a continuação do processo vital depois da morte.</p>

<p class=Normal>O grande cientista alemão Edgar Dacque, no livro <i>The primeval World, Saga and Mankind,"</i> [<a href="#N5">5</a>]<a name=R5></a>
falando acerca da crença difundida entre todos os povos do mundo numa transmigração após a morte, nos dá o seguinte aviso:</p>

<p class=Normal style='margin-left:1.0in'>Pessoas cultas e familiarizadas com ciência, como os antigos egípcios e indianos, agiam e viviam de acordo com esta crença. Eles abandonaram estas crenças somente depois do surgimento do realismo e racionalismo ingênuo dos gregos e judeus. Por esta razão seria melhor, quanto a este problema, não assumir a atitude fria da pseudo-civilização moderna, mas ao invés disso, adotar uma atitude reverente ao tentar resolver este problema em toda sua profundidade.</p>

<p class=Normal>Esta lei de renascimento pode tornar-se compreensível mediante a suposição de um fluxo vital subconsciente (em páli, <i>bhavanga-sota</i>), mencionada no <i>Abidhamma Pitaka</i> e explicada em detalhe nos comentários, especialmente o <i><i>Visuddhimagga</i></i>. A importância fundamental de <i>bhavanga-sota</i>, ou corrente vital subconsciente, como hipótese para explicação de várias doutrinas Budistas como renascimento, <i><i>kamma</i></i>, lembrança de vidas passadas, etc., não foi até agora suficientemente reconhecida ou compreendida pelos estudiosos ocidentais. O termo <i>bhavanga-sota</i> é idêntico aquilo que os psicólogos modernos como Jung, chamam de alma ou subconsciente, não querendo dizer com isso, obviamente a entidade eterna dos ensinamentos cristãos, mas um processo subconsciente sempre em mudança. Esta corrente de vida subconsciente é condição necessária para toda a vida. Nele, todas as impressões e experiências são armazenadas, ou melhor, aparecem como um processo múltiplo de imagens passadas, ou fotografias da memória, que, entretanto, como tais se escondem da consciência completa, mas que, especialmente nos sonhos, cruzam o limiar da consciência  tornando-se totalmente conscientes. </p>

<p class=Normal>O professor James [<a href="#N6">6</a>]<a name=R6></a> (cujas palavras traduzo aqui a partir da versão alemã) diz: "muitas realizações de gênio têm aqui seu início. Na conversão, na experiência mística e como oração, tal fato coopera com a vida religiosa. Contém todas as reminiscências momentaneamente inativas e fontes para todas as nossas paixões vagamente motivadas, impulsos, intuições, hipóteses, fantasias e superstições; em resumo, todas as nossas operações não-racionais daí resultam. É a fonte dos sonhos, etc."</p>

<p class=Normal>Jung, em seu livro <i>“Problemas da Alma em Nossos Dias”</i>, afirma: "da fonte viva do instinto brota toda criatividade." E em outro lugar: "o que quer que tenha sido criado pela mente humana resulta de conteúdos que são germes inconscientes (ou subconscientes)." E mais: "o termo instinto é, obviamente, nada mais que um nome coletivo para todos os fatores orgânicos e psíquicos, cuja natureza é em grande parte desconhecida para nós."</p>

<p class=Normal>A existência de um fluxo vital subconsciente, ou <i>bhavanga-sota</i>, é um postulado necessário de nosso pensamento. Caso tudo que nós vimos, ouvimos, pensamos, experienciamos e fizemos não fosse, sem exceção, registrado de algum modo em algum lugar, quer seja no extremamente complexo sistema nervoso (comparável a um gravador ou disco fonográfico ) ou no subconsciente ou inconsciente, nunca seríamos capazes de lembrar o que estivemos pensando num momento precedente; não saberíamos da existência de outros seres e coisas; não saberíamos quem são os nossos pais, professores, amigos e assim por diante; nem saberíamos como pensar, visto que o pensamento é condicionado pela lembrança de experiências anteriores. Nossa mente seria uma completa tabula rasa, mais vazia que a mente de um recém nascido, mais vazia até que o embrião no útero materno.</p>

<p class=Normal>Portanto, o fluxo vital subconsciente, ou <i>bhavanga-sota</i>, pode ser chamado de precipitado de nossas ações e experiências anteriores, que deve estar ocorrendo desde tempos imemoriais e deve ainda continuar por um período incomensurável de tempo por vir. Portanto, o que constitui a natureza mais íntima do ser humano, ou de qualquer outro ser, é este fluxo vital subconsciente, do qual não sabemos de onde vem nem para onde vai. Como disse Heráclito: “Nos mesmos rios [<a href="#N7">7</a>]<a name=R7></a> entramos e não entramos, somos e não somos.” [<a href="#N8">8</a>]<a name=R8></a> De forma semelhante diz o <i>Milindapanha</i>: “<i>na ca so, na ca anno</i>; nem é o mesmo, nem é um outro (que renasce).” Toda a vida, seja corpórea, consciente ou subconsciente, é um fluxo, um processo contínuo de vir-a-ser, mudança e transformação. Não há elemento persistente a ser descoberto neste processo. Dessa forma, não há um ego permanente, uma personalidade a ser encontrada, somente estes fenômenos transitórios.</i>

<p class=Normal>Acerca da irrealidade do ego, o psicólogo húngaro Volgyesi em sua <i>Mensagem para um Mundo Nervoso</i> disse:

<p class=Normal style='margin-left:1.0in'>"Sob influência das mais recentes descobertas, os psicólogos começaram a perceber a verdade acerca da entidade-ego, o valor meramente relativo do sentimento do eu (ego-feeling), da grande dependência deste homenzinho em relação ao complexo de fatores inexaurível do mundo ... a idéia de um eu independente, de um livre arbítrio autônomo: devemos abandonar estas idéias e reconciliar-nos com a verdade de que não existe eu real algum. Aquilo que tomamos por nossa sensação de eu não é nada além da mais maravilhosa fata-morgana [<a href="#N9">9</a>]<a name=R9></a>
 feita pela natureza."</p>

<p class=Normal>Em sentido último, não existem nem mesmo coisas tais como estados mentais, isto é, coisas estacionárias. Sensação, percepção, consciência, etc., são na realidade meros processos de sentir, perceber, tornar-se consciente, etc., dentro dos quais e fora dos quais não se esconde nenhum tipo de entidade separada e permanente.</p>
	
<p class=Normal>Posto isto, um entendimento real da doutrina do Buda acerca de <i>kamma</i> e renascimento é possível apenas para aquele que vislumbrou a natureza sem ego, ou <i>anatta</i>, e a condicionalidade, ou <i>idappaccayata</i>, de todos os fenômenos da existência. Desta forma, diz-nos o <i>Visuddhimagga</i> (Cap XIX):

<p class=Normal style='margin-left:1.0in'>Por todo lugar, em todos os reinos de existência, o nobre discípulo vê somente fenômenos mentais e corporais que operam devido à concatenação de causas e efeitos. Nenhum produtor do ato volitivo ou <i>kamma</i> ele vê, além do próprio <i>kamma</i>, nenhum recipiente do resultado do <i>kamma</i>, além deste mesmo resultado. E ele sabe muito bem que os sábios usam apenas linguagem convencional quando, no que diz respeito ao ato kâmmico, eles falam de um agente, ou com respeito ao resultado do <i>kamma</i>, de um recipiente.</p>

<p class=Normal style='margin-left:1.0in'>Nenhum agente das ações é encontrado,<br>
	ninguém que colha os frutos;<br>
	fenômenos vazios prosseguem:<br>
	isto apenas é a visão correta.</p>

	<p class=Normal style='margin-left:1.0in'>E enquanto as ações e seus resultados<br>
	seguem sempre de novo, tudo condicionando,<br>
	não se encontra um princípio,<br>
	como com a semente e a árvore.</p>

	<p class=Normal style='margin-left:1.0in'>Nenhum deus, nenhum Brahma, pode ser chamado<br>
	o criador desta roda da vida:<br>
	fenômenos vazios seguem,<br>
	todos dependentes de condições.</p>

	<p class=Normal>No <i>Milindapanha</i> o rei pergunta a Nagasena:
			<p class=Normal style='margin-left:1.0in'> “O que é isto, venerável senhor, que renascerá?”<br>
			“Uma combinação psico-física (<i>nama-rupa</i>). Ó Rei.”<br>
“Mas como, Venerável Senhor? Essa seria a mesma combinação psico-física atual?<br>
“Não, Ó Rei. Mas a presente combinação psico-física produz kâmmicamente atividades volitivas saudáveis e prejudiciais, e graças a tal <i>kamma</i>, uma nova combinação psico-física irá renascer.”</p>

<p class=Normal>Uma vez que em sentido último (<i>paramathavasena</i>) não há uma entidade-ego, ou personalidade, não se pode falar apropriadamente que tal ente renasce. O que nos interessa aqui é este processo psicofísico, que cessa com a morte, de modo a continuar depois em outro lugar.</p>

<p class=Normal>De modo similar, lemos no <i>Milindapanha</i>:</p>
			<p class=Normal style='margin-left:1.0in'> “O renascimento, Venerável Senhor, ocorre sem transmigração?!<br>
			“Sim, Ó Rei.”<br>
“Mas como, Venerável senhor, pode ocorrer renascimento sem o   passamento de algo? Por favor, dê-me um símile.”<br>
“Se, Ó Rei, um homem acende uma vela com a ajuda de outra vela, a luz de uma vela passa para a outra vela?<br>
“Não, Venerável Senhor.”<br>
"Assim mesmo, Ó Rei, ocorre o renascimento sem transmigração."</p>

<p class=Normal>Além disso, temos no <i>Visudhimagga</i> (Cap. XVII):</p>
<p class=Normal style='margin-left:1.0in'>Quem quer que não tenha uma idéia clara acerca da morte e não saiba que esta consiste na dissolução dos cinco agregados da existência (i.e. corporeidade, sensações, percepções, formações mentais, consciência) pensa que há uma pessoa, ou ser, que morre e transmigra para um novo corpo, etc. Quem quer que não tenha uma idéia clara acerca do renascimento, e não saiba que este consiste no surgimento dos cinco agregados da existência, pensa que é uma pessoa ou ser que renasce, ou que a pessoa reaparece em um novo corpo. Quem quer que não tenha uma idéia clara de <i>Samsara</i>, o ciclo de renascimentos, pensa ser uma pessoa real que vaga deste mundo para um outro, que vem daquele mundo para este, etc.  Aquele que não tem uma idéia clara acerca da fenomenalidade da existência, pensa que o fenômeno é o ego ou algo pertencente ao ego, ou algo permanente alegre ou prazeroso. Aquele que não tem uma idéia clara acerca da origem condicionada dos fenômenos da existência bem como acerca da origem das volições kâmmicas condicionadas pela ignorância, pensa que é o ego que compreende ou que falha em compreender, que age ou provoca a ação, que entra numa nova existência com o renascimento. Ou ele pensa que os átomos ou o Criador, etc., com a ajuda de processos embrionários, moldam o corpo dotando-o com suas várias faculdades; que é o ego que recebe as impressões dos sentidos, que sente, que deseja, que se apega, que entra na existência novamente em outro mundo. Ou ele pensa que todos os seres passam a existir devido ao destino ou ao acaso.</p>

<p class=Normal style='margin-left:1.0in'>Isso é um mero fenômeno, uma coisa condicionada,<br>
que surge na existência seguinte.<br>
Mas não transmigra para lá de uma vida anterior <br>
e no entanto, não pode surgir sem uma causa prévia.</p>
<p class=Normal style='margin-left:1.0in'>Quando esse fenômeno físico-mental (o feto) condicionalmente originado surge, diz-se que o ser entrou na (próxima) existência. Entretanto, nenhum ser (<i>satta</i>), ou princípio vital (<i>jiva</i>) transmigrou da existência prévia para esta existência, e ainda assim, este embrião não poderia ter surgido sem uma causa prévia.</p>

<p class=Normal>Tal fato pode ser comparado com o reflexo do nosso rosto no espelho, ou com o eco de nossa voz. Assim como a imagem no espelho e o eco são produzidos por nosso rosto ou voz sem que haja o passamento do rosto ou da voz, o mesmo ocorre com a consciência-do-renascimento. Caso existisse uma completa identidade ou mesmidade entre a vida anterior e a atual, o leite nunca se tornaria coalhada; e caso ocorresse uma alteridade absoluta, a coalhada nunca poderia ser condicionada pelo leite. Portanto, não se deve admitir nem uma completa identidade, nem uma absoluta alteridade com relação aos diferentes estágios da existência. Assim, <i>na ca so, na ca anno</i>: “nem é o mesmo, nem é um outro.” Como dito acima: toda a vida, seja corpórea, consciente ou subconsciente, é um fluxo, um contínuo processo de tornar-se, mudança e transformação.</p>

<p class=Normal>Para resumir o precedente podemos dizer: em sentido último não há seres ou coisas reais, nem criadores ou criações; existe apenas este processo de fenômenos corpóreos e mentais. A totalidade desse processo de existência tem um lado ativo e um passivo. O lado ativo ou causal da existência consiste do processo do <i>kamma</i> (<i>kamma-bhava</i>), ou seja, atividade kâmmica benéfica ou prejudicial. O lado passivo ou causado consiste dos resultados do <i>kamma</i>, ou <i>vipaka</i>, o assim chamado processo de renascimento (<i>upapatti-bhava</i>), i.e. o surgimento, crescimento, decadência e passamento de todos esses fenômenos neutros sob o ponto de vista de <i>kamma</i>.</p>

<p class=Normal>Desta forma, em sentido absoluto, não existe ser real que vague pelo ciclo dos renascimentos, mas meramente o que ocorre é este duplo processo de atividades kâmmicas e resultados kâmmicos. A vida presente é, por assim dizer, o reflexo da passada, e a vida futura é o reflexo da presente. A vida presente é o resultado da atividade kâmmica passada, e a vida futura o resultado da atividade kâmmica presente.</p>

<p class=Normal>Portanto, não há em lugar algum uma entidade-ego a ser encontrada que possa ser o executor da atividade kâmmica ou o recebedor do resultado kâmmico. Assim, o Budismo não ensina uma transmigração real, visto que em sentido absoluto não há tal coisa como um ser ou entidade-ego, menos ainda a transmigração desta.</p>

<p class=Normal>Em cada pessoa, como dito antes, parece que jaz dormente a débil noção instintiva de que a morte não pode ser o fim de todas as coisas, mas que algum tipo de continuidade deve existir. Em que sentido pode acontecer isso, entretanto, não é imediatamente claro.</p>

<p class=Normal>Talvez seja verdadeiro que uma prova direta do renascimento não possa ser dada. Temos, porém, relatos autênticos acerca de crianças em Burma e outros locais que às vezes são capazes de lembrar de modo bastante claro (provavelmente em sonhos) eventos de sua vida anterior. A propósito, aquilo que vemos nos sonhos é em grande parte reflexos distorcidos de eventos e coisas reais experimentados nesta ou em outra vida. E como poderíamos explicar o surgimento de prodígios como Jeremy Bentham, que aos quatro anos era capaz de ler e escrever grego e latim; ou John Stuart Mill, que aos três anos já lia grego e aos seis escrevera uma história de Roma; ou Babington Macaulay, que aos seis escreveu um compêndio de história mundial; ou Beethoven, que aos sete dava concertos públicos; ou Mozart, que compunha antes dos seis anos; ou Voltaire, que leu as fábulas de La Fontaine aos três anos de idade. Não teriam estes prodígios e gênios, que em grande parte vieram de famílias de pais iletrados, construído em vidas anteriores as fundações de suas faculdades extraordinárias? "<i>Natura non facit saltus:</i> a natureza não dá saltos."</p>

<p class=Normal>Podemos afirmar corretamente que a doutrina Budista de <i>kamma</i> e renascimento oferece a única explicação plausível para todas as variações e dissimilaridades na natureza. De uma semente de maça pode surgir apenas uma macieira, não uma mangueira; de uma semente de manga somente uma mangueira, não uma macieira. Assim, todas as coisas animadas como seres humanos, animais, etc., provavelmente mesmo as plantas e até os cristais devem, necessariamente, ser manifestações ou objetificações de algum tipo específico de impulso subconsciente ou vontade de viver.  Quanto a estes últimos pontos citados o Budismo nada diz; simplesmente afirma que toda vida vegetal pertence a ordem germinal ou <i>bija-niyama</i>.</p>

<p class=Normal>O Budismo ensina que se em nascimentos anteriores, o <i>kamma</i> corporal, verbal e mental, ou as atividades volitivas, foram más e inferiores e assim influenciaram de modo desfavorável o fluxo vital subconsciente (<i>bhavanga-sota</i>), então também os resultados, manifestos na vida presente deverão ser maus e desagradáveis. O caráter e as novas ações induzidas ou condicionadas pelos quadros e imagens negativas do fluxo mental subconsciente também deverão ser maus e desagradáveis. Se os seres, entretanto, semearam boas sementes nas vidas passadas, irão colher bons frutos na vida atual.</p>

<p class=Normal>No <a href="../sutta/MN135.php">Culakammavibhanga Sutta (MN 37.3)</a> um brâmane apresenta o problema:</p>

<p class=Normal style='margin-left:1.0in'>"Mestre Gotama, qual é a causa e condição pela qual os seres humanos são vistos como inferiores ou superiores? Pois, as pessoas podem ter vida curta ou vida longa, podem ser doentias ou saudáveis, feias ou bonitas, sem poder ou poderosas, pobres ou ricas, nascidas em classes inferiores ou superiores, tolas ou sábias. Qual é a causa e condição, Mestre Gotama, pela qual os seres humanos são vistos como inferiores ou superiores?"</p>
<p class=Normal style='margin-left:1.0in'>O Abençoado respondeu:</p>
<p class=Normal style='margin-left:1.0in'>"Os seres são os donos das suas ações, estudante, herdeiros das suas ações, nascem das suas ações, estão atados às suas ações, possuem as suas ações como refúgio. É a ação que distingue os seres entre inferiores ou superiores."</p>
	
<p class=Normal>No Anguttara Nikaya III, 40 se diz: Matar, roubar, adulterar, mentir, caluniar, fala grosseira e fútil, quando praticados, cultivados e quando nos engajamos freqüentemente nessas atividades, isto nos conduzirá ao inferno, ao mundo animal ou ao mundo dos fantasmas famintos. E mais: “Aquele que mata e é cruel vai para o inferno ou, caso renasça como humano, terá uma vida curta. Aquele que tortura outros seres, será afligido por doenças. O que odeia será horrendo, o invejoso não exercerá influência, o teimoso ocupará posições inferiores, o indolente será ignorante.” Em sentido contrário, beleza, influência, riquezas, status nobre e inteligência.</p>

<p class=Normal>George Grimm, no livro <i>A Doutrina do Buda</i>, tenta mostrar como a lei da afinidade pode no momento da morte regular o alcance da ligação com o novo óvulo. Ele diz:</P>

<p class=Normal style='margin-left:1.0in'>Aquele que é desprovido de compaixão e mata seres humanos ou mesmo animais, carrega dentro de si a inclinação para abreviar vidas. Ele encontra satisfação, mesmo prazer, na vida abreviada de outras criaturas. Óvulos de vida curta têm, portanto, alguma afinidade que faz com que eles sejam conhecidos por tal pessoa após a morte, o que põe o indivíduo no campo de ação de um novo óvulo, para seu próprio prejuízo. De modo semelhante, óvulos que carregam em si a potencialidade de desenvolver um corpo deformado, possuem afinidades com pessoas que encontram prazer em maltratar e desfigurar outros.<br>
Qualquer pessoa raivosa origina dentro de si mesma uma afinidade por corpos feios e seus germes respectivos, pois é marca característica da raiva desfigurar o rosto.<br>
Aquele que é ciumento, avarento, arrogante, carrega dentro de si a tendência de invejar as coisas dos outros e desprezá-los. Em conformidade com isso, os óvulos destinados a se desenvolver em circunstancias externas de pobreza possuem afinidades com tais pessoas.</p>

<p class=Normal>Gostaria aqui de retificar várias aplicações erradas do termo <i>kamma</i> prevalecentes no Ocidente e afirmar de uma vez por todas: a palavra páli <i>kamma</i> vem da raiz <i>kar</i>, fazer, fabricar, agir, significando, portanto, “ação, feito”, etc. Como termo técnico Budista, <i>kamma</i> é o nome para as volições ou intenções benéficas e prejudiciais (<i>kusala</i> e <i>akusala-cetana</i>), os fatores mentais e a consciência com eles associados, manifestados como ação física, verbal ou mental. Já nos suttas encontramos: “Intenção (<i>cetana</i>), monges, que eu chamo <i>kamma</i>. Mediante a intenção é que se executa o <i>kamma</i> por meio do corpo, linguagem e mente” (<i>cetanaham bhikkhave kammam vadami; cetayitva kammam karoti kayena vacaya manasa</i>). Portanto, <i>kamma</i> é ação volitiva ou intencional, nada mais, nada menos.</p>

<p class=Normal>Deste fato resultam as três afirmações seguintes:</p>
<p class=Normal style='margin-left:1.0in'>1. O termo <i>kamma</i> nunca compreende o resultado da ação, como muitas pessoas no Ocidente, desorientadas pela teosofia, desejariam que fosse. <i>Kamma</i> é a ação volitiva benéfica ou prejudicial e <i>kamma-vipaka</i> é o resultado da ação.</p>
<p class=Normal style='margin-left:1.0in'>2. Algumas pessoas consideram cada ocorrência, mesmo nossas novas ações benéficas e prejudiciais, como resultado de nosso <i>kamma</i> pré-natal. Em outras palavras, eles acreditam que os resultados de novo se convertem em causas de novos resultados, e assim sucessivamente <i>ad infinitum</i>. Desta forma eles caracterizam o Budismo como fatalismo; eles chegam a conclusão de que, neste caso, nosso destino não pode ser influenciado ou mudado, e nenhuma libertação pode ser alcançada.</p>
<p class=Normal style='margin-left:1.0in'>3. Há uma terceira aplicação errada do termo <i>kamma</i>, que é uma ampliação da primeira visão segundo a qual o termo <i>kamma</i> diz respeito ao resultado da ação. É a suposição de um assim chamado <i>kamma</i> conjunto, <i>kamma</i> de massa, <i>kamma</i> grupal ou <i>kamma</i> coletivo. De acordo com esta visão, um grupo de pessoas, p.ex. uma nação, deve ser responsável pelas más ações praticadas anteriormente pelo “mesmo” povo. Na realidade, entretanto, o povo presente pode não ser constituído pelos mesmos indivíduos que fizeram as ações prejudiciais. Para o Budismo, é verdade que qualquer pessoa que sofra fisicamente, sofre pelas suas ações passadas e presentes. Portanto, cada um daqueles indivíduos nascidos na nação sofredora se está sofrendo fisicamente, tal fato se deve ao mal praticado em outro lugar, aqui ou em alguma das inumeráveis esferas de existência, ele pode não ter nada a ver com as más ações da nação. Podemos dizer que pelo mau <i>kamma</i> ele foi atraído à condição infernal apropriada para si mesmo. Em resumo, o termo <i>kamma</i> se aplica, em cada caso, somente à atividade volitiva benéfica e prejudicial de indivíduos singulares. O <i>kamma</i>, dessa forma, é a causa ou semente da qual os resultados advirão ao individuo, nesta vida ou numa outra. [<a href="#N10">10</a>] </p>      

<p class=Normal><a name=R10></a>Conseqüentemente, está nas mãos do ser humano o poder para moldar seu destino futuro mediante a vontade e a ação ou <i>kamma</i>, seja este um destino elevado ou inferior, de felicidade ou miséria. Além disso, o <i>kamma</i> é a raiz ou semente não apenas para continuação do processo vital após a morte, ou seja, o renascimento, mas mesmo nessa vida presente, nossas ações ou <i>kamma</i> podem produzir bons ou maus resultados, bem como exercer influência decisiva em nosso caráter e destino atuais. Assim, por exemplo, se praticamos diuturnamente a benevolência (amor-bondade) em relação a todos os seres vivos, tanto humanos quanto animais, iremos crescer em bondade enquanto o ódio e todas as más ações feitas através do ódio, bem como os estados mentais aflitivos assim produzidos, não irão surgir facilmente em nós; nossa natureza e caráter se tornarão firmes, felizes, pacíficos e calmos.</p>

<p class=Normal>Se praticarmos altruísmo e liberalidade, a cobiça e a avareza irão diminuir. Se praticarmos amor e benevolência, a raiva e o ódio irão desvanecer. Se desenvolvermos sabedoria e conhecimento, a ignorância e a delusão irão gradativamente desaparecer. Quanto menos cobiça, ódio e ignorância (<i>lobha, dosa, moha</i>) habitarem em nossos corações, menos vezes iremos cometer ações más e prejudiciais com o corpo, a linguagem e a mente. Isto porque todas as coisas más, todos os destinos ruins, na verdade são enraizados na cobiça, no ódio e na ignorância; dessas três coisas, ignorância ou delusão (<i>moha, avijja</i>) é a raiz mestra e causa primeira de todo mal e miséria no mundo. Se não existir mais ignorância, não haverá mais cobiça e ódio, nem renascimento, nem sofrimento.</p>

<p class=Normal>Tal objetivo, entretanto, em sentido último, será realizado apenas pelos Santos (<i>arahants</i>), quer dizer, aqueles que, de uma vez por todas, se libertaram dessas três raízes; isto é realizado através do insight penetrativo, ou <i>vipassana</i>, em relação à impermanência, insatisfatoriedade e insubstancialidade (<i>anicca, dhukkha e anatta</i>) de todo este processo vital e pelo desapego a todas as formas de existência que dele resultam. Tão logo cobiça, ódio e ignorância se tornem extintas total e completamente, e, portanto, a vontade e a sede pela vida, que produzem um apego convulsivo à existência cheguem a um fim, então não haverá mais renascimento, e terá sido realizado o objetivo mostrado pelo Iluminado, a saber, extinção de todo renascimento e sofrimento. Assim, o <i>arahant</i> não executa mais <i>kamma</i>, isto é, não produz mais ações volitivas kâmmicamente benéficas ou prejudiciais. Ele está livre desta vontade afirmadora da vida expressa em ações físicas, palavras ou pensamentos, livre desta semente ou causa de toda vida e existência.</p>

<p class=Normal>Agora, aquilo que chamamos de caráter é na realidade a soma dessas tendências subconscientes produzidas em parte pelas atividades volitivas (<i>kamma</i>) pré-natais, em parte por nossas ações volitivas atuais. Tais tendências podem, ao longo da vida, tornarem-se indutoras de atividade volitiva benéfica ou prejudicial do corpo, fala ou mente. Caso, entretanto, a sede pela vida enraizada na ignorância seja completamente extinta, então não ocorrerá a entrada numa nova existência. Uma vez que a raiz de uma palmeira seja completamente destruída, a palmeira morrerá. Da mesma maneira, uma vez que as três raízes más da afirmação da vida – cobiça, raiva, ignorância – forem para sempre destruídas, não ocorrerá o ingresso numa nova existência. Aqui não devemos esquecer que tais expressões relativas a uma pessoa como eu, ele, santo, etc., são meros nomes convencionais para o que em realidade não passa de um processo vital impessoal.</p>

<p class=Normal>Devo dizer, em conexão com isto, que de acordo com o Budismo, é somente a última volição kâmmica imediatamente anterior a morte, chamada de <i>kamma</i> próximo da morte, que decide quanto ao renascimento que seguirá imediatamente. Nos países Budistas, portanto, é costume fazer com que o moribundo relembre suas boas ações, de modo a que surja nele um estado mental feliz e kâmmicamente puro, como preparação para um renascimento favorável. Ou os parentes mostram a ele coisas belas que serão ofertadas ao Buda para seu bem e benefício, dizendo: “Isto, meu querido, iremos oferecer ao Buda para seu próprio bem e benefício.” Também podem deixar que ele ouça um sermão religioso, ou que sinta o aroma de flores, ou que prove doces ou toque roupas preciosas dizendo: “Isto, meu querido, iremos oferecer ao Buda para seu próprio bem e benefício.”</p>

<p class=Normal>No <i>Visuddhimagga</i> (Cap. XVII) é dito que, no momento que antecede a morte, como regra, na memória do malfeitor vai aparecer a imagem de qualquer mal por ele cometido; ou que pode aparecer em seus olhos mentais uma circunstância auxiliar ou objeto, chamada de <i>kamma-nimitta</i>, conectada com a má ação, como sangue, uma adaga manchada de sangue, etc.; ou ele pode ver diante de sua mente uma indicação de seu renascimento miserável iminente, <i>gati-nimitta</i>, como chamas ardentes, etc. Para outro moribundo, pode aparecer diante da mente a imagem de um objeto voluptuoso incitador de seu desejo sensual.</p>

<p class=Normal>Para um bom homem pode aparecer diante de si qualquer ato nobre, <i>kamma</i>, feito antes por ele; ou um objeto presente naquele momento, o <i>kamma-nimitta</i>; ou ele pode ver em sua mente uma indicação de seu iminente renascimento, <i>gati-nimitta</i>, como palácios celestiais, etc.</p>

<p class=Normal>Encontramos nos suttas a distinção entre três tipos de <i>kamma</i> ou ações volitivas, considerando o tempo de amadurecimento, a saber: (1) <i>kamma</i> que produz frutos nessa vida (<i>ditthadhamma-vedaniya-kamma</i>); (2) <i>kamma</i> que produz fruto na vida seguinte (<i>upapajja-vedaniya-kamma</i>); (3) <i>kamma</i> que produz fruto em vidas posteriores (<i>aparapariya-vedaniya-kamma</i>). As explicações acerca destes tópicos são muito técnicas para o leitor em geral. Elas implicam o seguinte: o estágio do processo chamado de <i>kamma</i> volitivo consiste, na mente, de uma série momentos de pensamento impulsivos, ou <i>javana-citta</i>, que se sucedem em grande velocidade. Destes momentos impulsivos, o primeiro dará resultado nesta vida, o ultimo na próxima e os intermediários em vidas posteriores. Os dois tipos de <i>kamma</i> que dão frutos nessa vida e na seguinte podem por vezes se tornar inefetivos (<i>ahosi-kamma</i>). O <i>kamma</i>, portanto, que dá frutos em vidas posteriores será sempre efetivo, em qualquer tempo e lugar que surja uma oportunidade para que ele produza seu resultado; e enquanto o processo vital continue este <i>kamma</i> nunca se tornará inefetivo.</p>

<p class=Normal>O <i>Visuddhimagga</i> divide o <i>kamma</i>, de acordo com suas funções, em quatro tipos: <i>kamma</i> gerador, <i>kamma</i> mantenedor, <i>kamma</i> neutralizador e <i>kamma</i> destrutivo, dos quais todos podem ser saudáveis ou prejudiciais.</p>

<p class=Normal>Dentre estes quatro tipos, o gerador (<i>janaka-kamma</i>) produz no momento do nascimento e ao longo da vida os fenômenos neutros corpóreos e mentais, tais como os cinco tipos de consciência sensória e os fatores mentais a eles associados, como sensação, percepção, impactos sensoriais, etc.</p>

<p class=Normal>O <i>kamma</i> mantenedor (<i>upatthambhaka-kamma</i>), entretanto, não produz nenhum tipo de resultado kâmmico; mas tão logo qualquer outra volição kâmmica tenha efetivado o renascimento e um resultado kâmmico tenha sido produzido, este <i>kamma</i> mantém ou suporta segundo sua natureza, o fenômeno agradável ou desagradável e faz com que ele prossiga. </p>

<p class=Normal>O <i>kamma</i> neutralizador (<i>upapilaka-kamma</i>) também não produz resultado kâmmico algum; mas tão logo qualquer outra volição kâmmica tenha efetivado o renascimento e um resultado kâmmico tenha sido produzido ele neutraliza conforme sua própria natureza, o fenômeno agradável ou desagradável e não permite que este continue.</p>

<p class=Normal>O <i>kamma</i> destrutivo (<i>upaghataka-kamma</i>) não produz resultado kâmmico algum; mas tão logo qualquer outra volição kâmmica tenha efetivado o renascimento e um resultado kâmmico tenha sido produzido ele então destrói o <i>kamma</i> mais fraco e permite apenas seu próprio resultado kâmmico agradável ou desagradável.</p>

<p class=Normal>No Comentário ao Culakammavibhanga Sutta, o <i>kamma</i> gerador é comparado a um fazendeiro semeando; o <i>kamma</i> mantenedor, com a irrigação, adubação e cuidado com a plantação, etc., <i>kamma</i> neutralizador seria a seca que causa uma colheita pobre e o <i>kamma</i> destrutivo se compara com o fogo que destrói toda colheita.</p>

<p class=Normal>Outro exemplo é o seguinte: o nascimento de Devadatta numa família real foi devido a seu bom <i>kamma</i> produtivo. O fato de ele tornar-se monge e realizar elevados poderes espirituais deveu-se a seu bom <i>kamma</i> mantenedor. Sua intenção de matar o Buda foi um <i>kamma</i> neutralizador enquanto que o fato dele causar um cisma na Ordem foi um <i>kamma</i> destrutivo, devido ao qual ele renasceu num mundo de miséria. Descrever em detalhe todas as multifacetadas divisões do <i>kamma</i> encontradas nos Comentários é algo que vai muito além do escopo desta breve exposição. O que eu queria deixar claro nesta conferência é o seguinte: a doutrina Budista do renascimento nada tem a ver com a transmigração de uma alma ou entidade-ego, uma vez que em sentido último não existe um tal ego, tão somente um processo continuadamente mutante de fenômenos físicos e mentais. Além disso, foi minha intenção apontar que o processo do <i>kamma</i> e o do renascimento podem tornar-se ambos compreensíveis apenas pela suposição de um fluxo subconsciente de vida por trás de tudo na natureza.</p>

<p class=Normal>&nbsp;</p>
<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>


<p class=Normal><b>Notas:</b></p>

<p class=Normal><a name=N1></a>[1] Palestra, Universidade do Ceilão, 1947. [<a href="#R1">Retorna</a>]</p>

<p class=Normal><a name=N2></a>[2] Tudo que um corpo é está contido, como semente ou possibilidade, no embrião, (nota do tradutor). [<a href="#R2">Retorna</a>]</p>

<p class=Normal><a name=N3></a>[3] Chama-se precipitado ao sólido resultante ou de uma reação química, ou da excessiva saturação de um composto. A metáfora aqui, portanto, consiste em comparar o processo e os componentes do novo ser com uma reação química. [<a href="#R3">Retorna</a>]</p>

<p class=Normal><a name=N4></a>[4] O termo metempsicose é encontrado na filosofia grega, associado principalmente aos nomes de Pitágoras e Platão. Grosso modo metempsicose refere-se a noção de transmigração das almas através de vários corpos, humanos e não-humanos. Outro nome é metensomatose, usado por Plotino. Platão no Fedro atribui a metempsicose um papel purificador, ou seja, depois de um certo número de vidas, retorna-se ao convívio dos deuses, e caso se viva uma vida filosófica, esta purificação pode ser abreviada. [<a href="#R4">Retorna</a>]</p>

<p class=Normal><a name=N5></a>[5] Paleontólogo de renome que pretendia investigar o fundo de verdade presente nas várias tradições míticas da humanidade. Referência: <i>The Scientist and the Fairy Tale</i>, por: E.H. Krauss. In: http://www.theosophy-nw.org/theosnw/world/general/my-kraus.htm [<a href="#R5">Retorna</a>]</p>

<p class=Normal><a name=N6></a>[6] Provavelmente William James em <i>The Varieties of Religious Experience</i>. Tradução publicada pela cultrix: <i>As Variedades da Experiência Religiosa</i>. [<a href="#R6">Retorna</a>]</p>

<p class=Normal><a name=N7></a> [7] Há, aqui um jogo de palavras intraduzível, a palavra stream (fluxo, correnteza) que traduzimos por fluxo (de consciência) também se refere a correnteza de um rio. [<a href="#R7">Retorna</a>]</p>

<p class=Normal><a name=N8></a>  [8] Heráclito, fragmento 49a. In: Pré-socráticos, Coleção os Pensadores. [<a href="#R8">Retorna</a>]</p>

<p class=Normal><a name=N9></a>[9] O efeito de Fata Morgana, do italiano fata Morgana (ou seja: fada Morgana), em referência à fictícia feiticeira (Fada Morgana) meia-irmã do Rei Artur que, segundo a lenda, era uma fada que conseguia mudar de aparência, é um efeito de ilusão óptica.<br>
Trata-se de uma miragem que se deve a uma inversão térmica. Objetos que se encontrem no horizonte como, por exemplo, ilhas, falésias, barcos ou icebergues, adquirem uma aparência alargada e elevada, similar aos "castelos de contos de fadas".<br>
A Fata Morgana mais célebre é a que se produz no Estreito de Messina, entre a Calábria e a Sicília.
Com tempo calmo, a separação regular entre o ar quente e o ar frio (mais denso) perto da superfície terrestre pode atuar como uma lente refractante, produzindo uma imagem invertida, sobre a qual a imagem distante parece flutuar. Os efeitos Fata Morgana costumam ser visíveis de manhã, depois de uma noite fria. É um efeito habitual em vales de alta montanha, onde o efeito se vê acentuado pela curvatura do vale, que cancela a curvatura da Terra. Também se costuma ver de manhã nos mares árticos, com o mar muito calmo, e é habitual nas superfícies geladas da Antártida.<br>
Os efeitos de Fata Morgana são miragens ditas superiores, diferentes das miragens inferiores, que são mais comuns e criam a ilusão de lagos de água distantes nos desertos ou em estradas com o asfalto muito quente. Fonte: http://pt.wikipedia.org/wiki/Fata_Morgana. [<a href="#R9">Retorna</a>]</p>

<p class=Normal><a name=N10></a> [10] Devo adicionar aqui que o termo páli <i>vipaka</i>, que geralmente traduzo por <i>efeito ou resultado</i> não é realmente idêntico a estes dois termos. De acordo com o <i>Kathavatthu</i>, ele diz respeito apenas ao resultado mental produzido pelo <i>kamma</i>, tal como a sensação física prazerosa e dolorosa e todos os demais fenômenos mentais primários. Os fenômenos corporais, como os cinco órgãos dos sentidos, etc., não são chamados <i>vipaka</i> e sim <i>kammaja ou kamma-samutthana</i>, ou seja, nascido do <i>kamma</i> ou produzido pelo <i>kamma</i>, (nota do autor). [<a href="#R10">Retorna</a>]</p>

<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>



<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>