<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"meditando_naoeu");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO',"1 Setembro 2012 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'>Meditando no Não-eu </Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'>Ayya Khema</Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>

<p class=Normal>No Budismo nós usamos as palavras “eu” e “não-eu”, e é importante compreender o que é esse “não-eu”, <i>anata</i>, mesmo que a princípio seja apenas uma idéia, porque a essência dos ensinamentos do Buda, depende desse conceito. E nesse ensinamento o Budismo é único. Ninguém, nenhum outro professor espiritual, formulou o não-eu dessa forma. E por  ter sido formulado pelo Buda dessa forma, há também a possibilidade de falar sobre isso. Muito se tem escrito sobre o não-eu, mas para conhecê-lo, temos que experienciá-lo. E é isso que os ensinamentos visam, a experiência do não-eu. </p>

<p class=Normal>Para experienciar o não-eu, temos primeiro que conhecer o eu por completo. Conhecê-lo de fato. Mas a menos que saibamos o que é esse eu, esse eu chamado “eu”, é impossível saber o significado de “ali não há mais eu”. Para abrir mão de algo, é necessário primeiro tê-lo em mãos. </p>

<p class=Normal>Estamos constantemente tentando reafirmar o eu. O que já mostra que esse eu é muito frágil e insignificante, pois se assim não fosse porque temos que reafirmá-lo constantemente? Porque temos medo constantemente do “eu” ser  ameaçado pelas inseguranças, de não conseguir o que precisa para sobreviver? Se fosse uma tal entidade sólida como acreditamos que seja, não nos sentiríamos ameaçados tão freqüentemente. </p>

<p class=Normal>Afirmamos o “eu” novamente e novamente através da identificação. Identificamos com um certo nome, com a idade, sexo, habilidades, ocupação. “Sou um advogado, sou um médico, sou um contador, sou um estudante”. E nos identificamos com as pessoas nos nossos relacionamentos. "Sou um marido, sou uma esposa, sou uma mãe, sou um irmão, sou um filho.” Agora, nessa maneira de falar, temos que usar o “eu” – mas somente na hora de falar. Pensamos realmente que esse “eu” seja quem nós somos. Realmente acreditamos nisso. Não há duvida em nossa mente que esse “eu” seja quem somos. Quando qualquer um desses fatores é ameaçado, quando uma esposa é ameaçada, quando uma mãe é ameaçada, quando um advogado é ameaçado, quando um professor é ameaçado – ou quando perdemos a pessoa que nos possibilita ser aquele “eu” – que tragédia! </p>

<p class=Normal>A identificação com o "eu" se torna insegura, e “mim” encontra dificuldade em dizer “olhe para mim”, “isso sou eu”. Elogio e crítica estão incluídos. Elogio reafirma o “mim”. Crítica ameaça o “mim”. Assim gostamos de ser elogiados e não gostamos de ser criticados. O ego fica ameaçado. Fama e infâmia – a mesma coisa. Perda e ganho. Se ganhamos, o ego cresce; se perdemos ele fica um pouco menor. Assim estamos constantemente em um dilema, e num constante medo. O ego pode perder um pouco de sua grandeza. Alguém pode torná-lo um pouco menor. E isso acontece com todos nós. Eventualmente alguém com certeza irá nos censurar por algo. Até mesmo o Buda foi censurado. </p>

<p class=Normal>Mas a censura que nos é feita não é o problema. O problema é a nossa reação. O problema é que nos sentimos pequenos. O ego tem muita dificuldade  para se reafirmar novamente. Então o que usualmente fazemos é censurar de volta, fazendo com que o outro ego se sinta um pouco menor também. </p>

<p class=Normal>Identificar-se com qualquer coisa que fazemos e com o que temos, seja nossas posses, ou pessoas, é, assim acreditamos, necessária para a nossa sobrevivência.  A sobrevivência do “Eu”. Se não identificamos com isso ou com aquilo, nos sentimos como se estivéssemos no limbo. Essa é a razão porque é difícil parar de pensar durante a meditação. Porque sem o pensamento não há identificação. Se não penso com o que irei me identificar? É difícil chegar a um estágio na meditação no qual não há mais nada com o que se identificar. </p>

<p class=Normal>Felicidade, também, pode ser uma identificação. “Sou feliz”. "Sou infeliz". Por sermos tão ávidos para sobreviver, temos que seguir com a identificação. Quando essa identificação se torna uma questão de vida ou morte do ego, que em geral é o caso, então o medo da perda se torna tão grande que podemos estar em constante estado de medo. Constantemente com medo de perder as posses que fazem sermos quem somos, ou as pessoas que fazem sermos quem somos. Isso vale para todas as demais identificações. Não é um estado tranqüilo  de se viver e, porque é assim? Somente por uma coisa: ego, o desejo por ser/existir. </p>

<p class=Normal>Essa identificação resulta, claro, em desejo por possuir. E essas posses resultam em apego. O que temos, com o que identificamos, somos apegados também. Esse apego, esse agarramento, faz com que seja extremamente difícil ser livre e ter um ponto de vista  independente. Esse tipo de apego, seja ao que for que estejamos apegados – pode não ser apego a carros e casas, pode até mesmo não ser apego a pessoas – mas com certeza nos apegamos a opiniões e idéias. Nos apegamos à nossa visão do mundo. Nos apegamos à visão de como seremos felizes. Talvez nos apeguemos também à idéia de quem criou o universo. Seja o que for que nos apeguemos, até como o governo deve governar o pais, tudo isso faz com que fique extremamente difícil  ver as coisas como elas na verdade são. Ser uma mente aberta. E uma  mente é aberta somente  quando se aceita novas idéias e compreensões. </p>

<p class=Normal>O Buda comparou os discípulos a quatro diferentes tipos de potes de argila. O primeiro pote de argila tem buracos no fundo. Ao colocar água, ela escorre toda. Em outras palavras, qualquer ensinamento para aquela pessoa será inútil.  O segundo pote de argila tem rachaduras. Ao colocar água o pote goteja. Essas pessoas não  se lembram. Não conseguem fazer sentido dos ensinamentos com rachaduras na compreensão. O terceiro ele comparou a um pote completamente cheio. Não cabe mais água pois já está cheio até o topo. Tal pessoa, tão cheia de pontos de vista não pode aprender nada novo!  Mas, felizmente somos o quarto tipo. Um pote vazio sem qualquer buraco ou rachaduras. Completamente vazio. </p>

<p class=Normal>Eu ouso dizer que não somos. Mas talvez vazio o suficiente onde possa ser colocado algo mais. Para estar vazio assim, de crenças e opiniões, significa ausência de apego. Até ausência de apego ao que pensamos ser a realidade. Seja o que for que pensamos ser a realidade, com certeza não é, porque se fosse, nós nunca seríamos infelizes nem ao menos por um simples momento. Nunca sentiríamos falta de nada. Nunca sentiríamos falta de companhia, de posses. Nunca sentiríamos frustração, tédio. Se sentíssemos, então seja o que for que pensemos ser real, não é. O que é a verdadeira realidade é a completa satisfação. Se não formos completamente realizados, não estamos vendo a realidade perfeita. Por conseguinte, qualquer conceito que tenhamos está errado ou é parcial. </p>

<p class=Normal>Porque é errado ou parcial, e limitado pelo ego, precisamos olhar as coisas  com desconfiança. Qualquer coisa que nos apegamos nos mantém  ligados a ela.  Se agarramos o pé de uma mesa, não poderemos sair pela porta. É impossível nos movermos. Estaremos presos. Só teremos a oportunidade de escaparmos quando abrirmos mão. Qualquer identificação, qualquer posse a que nos apeguemos é o que nos impede de atingir a realidade transcendente. Agora, podemos ver com facilidade esse apego quando nos agarramos a coisas e pessoas, mas não podemos ver com facilidade porque os 5 <i>khandhas</i> são chamados de 5 agregados influenciados pelo apego. Assim são chamados, e eles são de fato aquilo a que mais nos apegamos. Eles são todo apego. Nós nem mesmo paramos para pensar quando olhamos para o nosso corpo e quando olhamos para a nossa mente ou quando olhamos para uma sensação, percepção, formações mentais e consciência – <i>vedana, sañña, sankhara</i> e <i>viññana</i>. Olhamos para essa mente e corpo, <i>nama-rupa</i>, e  nem mesmo duvidamos do fato de que essa é a minha sensação, minha percepção, minha memória, meus pensamentos e minha consciência. E ninguém começa a duvidar até que comece a ver. E para ver precisamos de uma certa distância  das idéias e opiniões. </p>

<p class=Normal>Apego é a maior possessividade e aderência que temos. Enquanto nos apeguemos não poderemos ver a realidade. Não podemos ver a realidade por que o apego está na frente. O apego colore qualquer coisa que acreditemos ser a verdade. Agora, não é possível dizer, “tudo bem, eu paro de me apegar.” Nós não podemos fazer isso. O processo de desmantelar o “eu”, de não acreditar mais que isso é um todo, é um processo gradual. Mas se a meditação tiver algum beneficio e sucesso, deve primeiro de tudo mostrar que há a mente e há um corpo. Não há nenhuma única coisa atuando em harmonia o tempo todo. Há a  mente que pensa e faz com que o corpo aja. Esse é o primeiro passo para conhecer a si mesmo um pouco mais claramente. E então podemos notar “essa é uma sensação” e “a essa sensação estou dando um nome”, que significa a memória e a percepção. “Esse é um pensamento que estou tendo sobre essa sensação. A sensação apareceu porque a consciência na mente se conectou com a sensação que surgiu.” </p>

<p class=Normal>Separe as 4 partes dos <i>khandhas</i> que pertencem à mente. Ao fazer isso, enquanto estiver acontecendo – não agora quando estamos pensando à respeito – mas enquanto estiver acontecendo, então podemos ter uma vaga idéia que isso não é realmente o eu, mas que são fenômenos que surgem, permanecem algum tempo e depois cessam. Por quanto tempo a consciência permanece num objeto? E por quanto tempo os pensamentos duram? E nós realmente os convidamos? </p>

<p class=Normal>O apego, o apego à consciência, é o que faz com que o ego surja. Por causa do apego a noção do “eu” surge e então surge o “meu” e o meu trás todos os problemas. Sem o "meu" haveria problemas? Se não houvesse ninguém dentro de mim – como pensamos que há – quem seria chamado de Eu ou de João, Clara, então quem está tendo o problema?  Os <i>khandhas</i> não têm nenhum problema. Os <i>khandhas</i> são apenas um processo. Eles são fenômenos e isso é tudo. Eles apenas continuam e continuam. Mas por que estou me apegando neles e tentando agarrá-los, dizendo: “isso sou eu, isso é minha sensação, isso é o meu desejo” os problemas então surgem. </p>

<p class=Normal>Se desejamos realmente nos livrarmos do sofrimento, completamente e totalmente, então o apego tem que ir embora. O caminho espiritual não é uma conquista; ele é sempre um abandono. Quanto mais abandonamos, mais haverá o vazio e o espaço aberto para que possamos ver a realidade. Aquilo que abandonamos não mais está lá, assim, há a possibilidade de simplesmente se mover, sem apego ao resultado desse movimento. Enquanto estivermos apegados aos resultados do que fazemos, enquanto estivermos apegados aos resultados do que pensamos, estaremos  aprisionados, estaremos confinados. </p>

<p class=Normal>Agora há uma terceira coisa que fazemos: estamos interessados em transformar-nos em alguma coisa ou transformar-nos em alguém. Interessados em transformar-nos num excelente meditador. Interessados em transformar-nos num formando. Interessados em transformar-nos em alguma coisa que não somos. E transformar-se em algo nos impede de ser. Quando somos impedidos de ser, não conseguimos prestar atenção no que realmente está presente. Todo esse negócio de transformar-se, é claro, está no futuro. Desde que qualquer coisa no futuro é conjetura, é um mundo de sonho no qual vivemos. A única realidade que podemos ter certeza é este momento em particular exatamente agora; é esse momento em particular que precisamos ser capazes de estar conscientes – já passou e este passou e o próximo também passou. Veja como eles estão todos passando! Essa é a impermanência de tudo. Cada momento passa, mas nos apegamos, tentando agarrá-los. Tentando fazer deles a realidade. Tentando fazer deles a segurança. Tentando fazer deles algo que não são. Veja como todos estão passando. Não conseguimos nem mesmo dizer de tão rápido eles passam. </p>
 
<p class=Normal>Não há nada que seja seguro. Nada em que se segurar, nada que seja estável. Todo o universo está constantemente se desintegrando e se juntando novamente. E isso inclui a mente e o corpo que chamamos “eu”. Você pode acreditar nisso ou não, não faz nenhuma diferença. Para sabê-lo é necessário experimentá-lo; ao experimentá-lo, tudo se torna perfeitamente claro. Ninguém pode dizer que não seja assim. Podem tentar, mas suas contestações são sem sentido porque você experienciou isso. É a mesma coisa que morder uma manga para conhecer seu sabor. </p>

<p class=Normal>Para experienciá-lo, é necessário meditar. Uma mente comum apenas conhece os conceitos e idéias comuns. Se  alguém quiser compreender e experienciar idéias e experiências extraordinárias, terá que ter uma mente extraordinária. Uma mente extraordinária surge através da concentração. Muitos meditadores já experienciaram algum estágio diferente do habitual. Mas temos que ir mais além do que o estágio inicial. Até o ponto em que a mente é verdadeiramente extraordinária. Extraordinária no sentido de que possa se dirigir para onde quer que deseje. Extraordinária no sentido de que não seja perturbada pelos eventos do dia a dia. E quando a mente pode se concentrar, então ela experiencia estados que não conhecia antes. Compreender que o seu universo constantemente se desintegra e volta a se juntar novamente é uma experiência meditativa. Isso requer prática, perseverança e paciência. E quando a mente está imperturbável e tranqüila, surgem a equanimidade, o equilíbrio, e a paz. </p>

<p class=Normal>Nessa hora a mente compreende a idéia da impermanência numa tal extensão que vê a si mesma como totalmente impermanente. E quando se vê a própria mente como sendo totalmente impermanente, há uma mudança no ponto de vista. Gosto de comparar essa mudança com um caleidoscópio que as crianças brincam. Um leve toque e se tem um desenho diferente. Tudo parece bem diferente com apenas uma leve mudança. </p>

<p class=Normal>Não-eu é experienciado através do aspecto da impermanência, através do aspecto da insatisfatoriedade e através do aspecto do vazio. Vazio do que? A palavra “vazio” é freqüentemente mal compreendida porque quando se pensa somente como um conceito, se diz “o que você quer dizer com vazio?” Tudo está ali: ali estão as pessoas, e dentro delas estão os ossos e o sangue e tudo tem substância – e a mente também não é vazia. Nela estão as idéias, pensamentos e sentimentos. E mesmo quando estes não estão presentes, o que você quer dizer com vazio?  A única coisa que é vazia é a vacuidade de alguma coisa. </p>

<p class=Normal>Não há entidade especifica em nada. Isso é o vazio. Isso é a vacuidade. Essa vacuidade é também experienciada na meditação. É vazio, desprovido de uma pessoa especifica, desprovido de uma coisa especifica, desprovido de qualquer coisa que seja permanente, desprovido de qualquer coisa que até possa torná-lo importante. Tudo é um fluxo. Assim o vazio é isso. E a vacuidade é para ser vista em tudo; para ser vista em si mesmo. Isso é o que se chama de <i>anatta</i>, não-eu.  Vazio de uma entidade. Não há ninguém ali. Tudo é imaginação. No começo isso nos faz sentir muito inseguros. </p>

<p class=Normal>Aquela pessoa com quem eu estava tão preocupada, aquela pessoa que tentava fazer isso ou aquilo, aquela pessoa que iria me dar segurança, que vai ser meu seguro para uma vida feliz – uma vez que eu encontre essa pessoa – essa pessoa na verdade não existe. Que idéia assustadora e insegura é essa! Que sentimento de medo surge! Mas de fato, é justamente o contrário. Se a pessoa aceita e suporta esse medo e vai além dele, ela se torna completamente aliviada e libertada. </p>

<p class=Normal>Vou dar um símile: imagine que você possui uma jóia de grande valor, tão valiosa que você deposita sua confiança que quando surgirem momentos difíceis, ela irá tomar conta de você. Ela é tão valiosa que você tem nela a sua proteção. Você não confia em ninguém mais. Você tem um cofre na sua casa e é lá que você guarda essa sua jóia. Agora, você tem trabalhado muito duro durante muitos anos e você pensa que merece umas férias. Então agora,  o que você fará com a sua jóia?  Com certeza você não pode levá-la consigo em suas férias na praia. Então você compra novas trancas para as portas, tranca as janelas e alerta seus vizinhos. Diz a eles sobre suas férias e pede que eles tomem conta de sua casa – e do cofre que há nela. E eles dizem, claro, que farão. Você se sente muito tranqüilo e sai para suas férias. </p>

<p class=Normal>Você vai para a praia e é ótimo. Maravilhoso. As palmeiras balançam ao vento e a cabana que você escolheu na beira da praia é agradável e limpa. As ondas são mornas e tudo é perfeito. No primeiro dia você realmente desfruta. Mas no segundo dia você começa a imaginar: os vizinhos são boas pessoas, mas eles gostam de visitar os seus filhos. Eles não estão sempre em casa, e ultimamente tem havido uma onda de assaltos pela vizinhança.  E no terceiro dia você se convence que algo terrível está para acontecer, e volta para casa.  Você entra em sua casa e abre o cofre. Tudo está perfeito. Você vai até os  vizinhos e eles perguntam, “Porque você voltou? Nós estávamos cuidando da sua casa. Você não precisava ter voltado. Tudo está bem." </p>

<p class=Normal>No ano seguinte, a mesma coisa. Novamente você fala com os vizinhos, “Agora nessas férias eu de verdade estarei fora por um mês. Preciso dessas férias pois tenho trabalhado muito.” Então eles dizem,” Absolutamente você não precisa se preocupar, pode ir. Vá para a praia.” Assim mais uma vez você tranca as janelas, as portas, deixa tudo em ordem e vai para a praia. Novamente, é maravilhoso, belo. Você fica por 5 dias. No quinto dia você está convencido de que algo terrível deve ter acontecido. E você volta para sua casa.  Você vai para casa e céus!, aconteceu. A jóia se foi. Você fica num estado de completo desespero. Deprimido. Então você vai até os vizinhos, mas eles não têm idéia do que possa ter acontecido, eles estiveram por ali o tempo todo. Então, você senta e considera o problema e se dá conta que já que a jóia se foi, você pode voltar para a praia e  se divertir! </p>

<p class=Normal>Aquela jóia é o eu. Uma vez que ela se foi, todo o peso de cuidar dela, todo o medo, todas as trancas nas portas e janelas não é mais necessário. Você pode ir e se divertir enquanto você ainda está nesse corpo. Após uma apropriada investigação, o aspecto assustador de perder as coisas que lhe pareciam tão preciosas se torna apenas um alivio e o liberta da preocupação que havia. </p>

<p class=Normal>Há três portas para a libertação: vazio, sem desejo e sem sinais. Se compreendermos a impermanência, <i>anicca</i>, completamente, ela é chamada de libertação sem sinais. Se compreendermos o sofrimento, <i>dukkha</i>, completamente, é a libertação  sem desejo. Se compreendermos o não-eu, <i>anatta</i>, completamente então é a liberação do vazio. Significando que podemos passar por qualquer uma dessas três portas. E estar libertado significa não ter que experienciar nenhum momento de infelicidade novamente. Também significa algo mais: significa que não mais será gerado <i>kamma</i>. Uma pessoa completamente libertada continua agindo, continua pensando, continua falando e continua vendo todas as intenções e propósitos como qualquer outra pessoa, mas essa pessoa perdeu a idéia do pensamento "Eu", eu estou pensando, eu estou falando, eu estou agindo. <i>Kamma</i> não mais é praticado, porque há apenas o pensamento, há apenas a fala e há apenas a ação. Há a experiência mas não há o experimentador. E por não ser mais gerado  <i>kamma</i>, não há o renascimento. Essa é a iluminação completa. </p>    

<p class=Normal>Nesta tradição, há três estágios de iluminação que antecedem o quarto estágio, que é a completa iluminação. O primeiro estágio, que nos diz respeito – pelo menos em teoria – é chamado <i>sotapanna</i>, aquele que entrou na correnteza. Significa que a pessoa experimentou Nibbana uma vez e portanto entrou na correnteza. Essa pessoa não pode mais ser impedida de percorrer o Caminho. Se o insight for forte, haverá somente uma vida mais. Se o insight for fraco, pode haver mais 7 vidas. Tendo visto Nibbana uma vez, algumas dificuldades que antes existiam são removidas. O mais drástico obstáculo removido é a idéia de que o que chamamos de “eu” seja uma entidade separada. O entendimento incorreto do "eu" é deixado de lado. Mas isso não significa que o <i>sotapanna</i> está constantemente consciente do não-eu. O entendimento incorreto é deixado de lado. Mas o entendimento correto tem que ser reforçado várias vezes e experienciado várias vezes através daquele reforço. </p>

<p class=Normal>Tal pessoa não tem mais grandes interesses, e certamente não crê em preceitos e rituais. Pode até executar tais ações porque seja tradição ou porque está acostumada, mas tal pessoa não mais acredita que isso possa lhe trazer qualquer tipo de libertação (se é que chegou a acreditar alguma vez).  Em seguida uma coisa interessante é deixada de lado: a dúvida. A dúvida é deixada de lado porque a pessoa viu por si mesma que aquilo que o Buda ensinou é exatamente correto. Até esse momento as dúvidas poderiam surgir com freqüência porque com facilidade se pode pensar: “Bem, talvez. Talvez seja assim, mas como posso ter certeza?” Pode-se somente ter certeza através da própria experiência. Então, é claro, não haverá mais dúvida porque a pessoa viu exatamente o que foi ensinado, e tendo visto isto, o coração e a mente compreendem fazendo possível ver todo o restante. </p>

<p class=Normal>O Dhamma precisa ter  como base a compreensão de que não há uma entidade especial. Há continuidade, mas não há uma entidade especial. E essa continuidade é que faz com que seja tão difícil enxergarmos que realmente não há ninguém dentro do corpo fazendo com que as coisas aconteçam. As coisas acontecem de qualquer forma. Então, o primeiro relance da libertação, chamada de entrar na correnteza, realiza mudanças dentro de nós. Isso certamente não desenraiza o desejo e a raiva – na verdade, estes não são nem mencionados. Mas, através da compreensão mais profunda que a pessoa alcançou, o desejo e a raiva diminuem. Eles não são tão fortes como antes, e não se manifestam de uma forma grosseira, mas continuam existindo de uma forma sutil. </p>

<p class=Normal>O próximo estágio é aquele que retorna uma vez, depois o que não retorna e então, o <i>arahant</i>. O que retorna uma vez, terá somente mais uma vida no mundo dos cinco sentidos. O que não retorna não terá mais nenhuma vida humana, e o <i>arahant</i>, é o completamente iluminado. Desejos sensuais e a raiva somente desaparecem com os que não retornam, e a presunção somente desaparece completamente com o <i>arahant</i>.</p>

<p class=Normal>Assim podemos aceitar o fato de que desde que não somos <i>arahants</i>, ainda temos desejo e raiva. Não é uma questão de se culpar por tê-los; é um problema de compreensão de como eles surgem. Eles surgem da delusão do eu. Quero proteger essa jóia que é o eu. É assim que eles surgem. Mas com a prática contínua da meditação, a mente pode se tornar mais e mais clara. E finalmente compreender. E quando ela compreende, pode transcender a realidade. Mesmo se for vista apenas por um momento mental, a experiência é de tão grande impacto que faz uma grande mudança em nossas vidas. </p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>

<p class=Normal><b>Notas:</b></p>

<p class=Normal>Traduzido do inglês por Teresa Cristina Geribello a quem agradecemos por essa valiosa contribuição ao Dhamma.</p>



<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>



<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>