<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"praticando_mundo");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO',"11 Janeiro 2014 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'> Praticando no Mundo</Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'>Ajaan Brahmavamso</Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>


<p class=Normal>O retiro que acabamos de experienciar foi longo. Esta noite todos vocês estarão indo para casa: de volta aos seus monastérios, para outros lugares, para outras palestras, ou para um outro retiro.</p>

<p class=Normal>O que realmente estaremos fazendo? Como podemos fazer uso de tudo que criamos neste retiro? A primeira coisa a mencionar é que vocês precisam ter muito cuidado ao deixarem este retiro, ao dirigir para casa e retornar para o mundo. Às vezes simplesmente não nos damos conta o quão relaxados e tranquilos nos tornamos num retiro como este. Todos aqui estão seguindo na mesma direção, então não temos muito com que nos compararmos. Às vezes pensamos que realmente não aconteceu nada no retiro. Mas garanto a vocês que devido à sua perspectiva calma, relaxada e pacífica, quando passarem dessas portas e saírem, o trânsito, o barulho e a agitação parecerão a mais completa loucura.</p>

<p class=Normal>Eu encorajo as pessoas antes de entrarem nos seus carros e dirigirem para casa, que subam e desçam as pequenas ruas laterais por alguns minutos, para acostumar-se ao mundo novamente. Às vezes é muito difícil responder quando alguém tenta cortar a sua frente, ou quando os semáforos de repente mudam para vermelho, e você tem que colocar o pé no freio muito rapidamente ao invés de dizer: "Solte, solte, solte, sem controle". Então, por favor, cuidem-se, quando saírem permitam-se tempo para realmente voltar para o mundo novamente.</p>

<p class=Normal><b> Não sejam Negligentes</b></p>

<p class=Normal>Lembro a primeira vez que estive em um retiro. Foi, na verdade, muitos, muitos anos atrás, em um monastério aparentemente tibetano no norte da Escócia. Eu estava apenas meditando e fazendo as minhas atividades. Todos os demais estavam fazendo o mesmo, assim realmente não notei nada até que saí do retiro e voltei para Londres. Foi realmente chocante como as pessoas eram barulhentas, como elas estavam frenéticas, quão alto falavam, e como se moviam agitadamente. Eu não tinha percebido que tinha desacelerado tanto. Então uma das primeiras coisas que vocês irão reconhecer ao voltarem para o mundo é que agora vocês têm algo para se compararem. Eu garanto que vocês descobrirão que mudaram muito, muito mais do que seria de se esperar.</p>

<p class=Normal>Sejam gentis com vocês mesmos ao voltarem para casa. É tão fácil jogar fora toda a paz, toda a tranquilidade, e toda a sabedoria que ganhamos em um retiro como este. É uma pena que às vezes não apreciamos essas qualidades. Nós pensamos que uma vez que tenhamos desenvolvido essas qualidades maravilhosas: quietude, silêncio, paz, satisfação interior e liberdade, elas sempre vão estar presentes. E por isso nós realmente não as mantemos, não as protegemos. Os <a href="../caminho_liberdade/esforco.php">Quatro Esforços Corretos</a> precisam ser trazidos à mente. O quarto esforço é talvez o mais importante, como se o Buda tenha deixado o melhor para o final. Esse quarto esforço correto é quando o praticante se esforça, estimula a energia, e aplica a mente para manter, desenvolver, e ajudar a crescer, todos os estados mentais saudáveis, hábeis, que surgem na mente. Nós cuidamos deles  e os mantemos, para que eles possam crescer mais fortes. Às vezes, fazemos todo o esforço para manter afastadas as coisas ruins, fazemos todo o esforço de cultivar, e trazer as coisas boas, mas assim que elas estão presentes, ficamos negligentes e permitimos que elas desapareçam.</p>

<p class=Normal>Por causa das características de sofrimento, impermanência e não-eu, e por causa das contaminações no mundo, a bondade é muito frágil. Ela precisa ser cultivada e mantida segura. Caso contrário, pode muito facilmente ser subjugada e perdida, simplesmente pelas forças destrutivas do mundo. Sabemos que as coisas como a paz e o amor, a bondade e a liberdade, é tão fácil perdê-las no mundo, porque somos negligentes. É por isso que o Buda disse, para não sermos negligentes, para ter cuidado e proteger os bons estados, os estados bondosos, os estados preciosos, que desenvolvemos.</p>

<p class=Normal>Quando deixarem este retiro, vejam se vocês conseguem proteger essa jóia preciosa que lhes foi dada. É muito preciosa. Não importa quanto vocês tenham avançado na sua meditação, alguma coisa foi obtida. Eu garanto isso. Eu sei disso. Vocês experimentaram um estado de paz, um estado de liberdade. É apenas um gosto de liberdade - mesmo que esse gosto de liberdade possa parecer ser apenas a luz no fim de um longo túnel - vocês chegaram mais perto do que vocês normalmente estariam. Vocês a viram por vocês mesmos. Sim, existe tal coisa como a liberdade, a paz e contentamento, e nisso realmente se encontra a felicidade. Se nós a cultivarmos, se a cuidarmos e a mantivermos o maior tempo possível, então, essa paz, liberdade, essa sabedoria no interior do coração, cuidará de vocês na vida diária.</p>

<p class=Normal><b>Nosso Verdadeiro Lar</b></p>

<p class=Normal>Na vida leiga trabalhamos muito duro, fazemos todas as nossas tarefas e deveres, mas nós sempre temos um lugar para voltar. No entanto, Ajaan Chah dizia: "Nosso verdadeiro lar é a paz interior". O nosso lar não é a casa em que vivemos, ou o kuti, que um monge ou um <i>anagarika</i> habita. O nosso verdadeiro lar está dentro de nós mesmos. Podemos ver isso na meditação. Às vezes sentamos e vamos para o interior da mente, e nos sentimos tão felizes quanto possível. Nós não queremos nada. Podemos realmente descansar e relaxar, nos sentirmos confortáveis. Um lar se supõem ser um lugar de conforto, um lugar onde podemos relaxar. Em casa, podemos abrir mão, soltar, não temos que lutar com o mundo. Não há nada pedido ou exigido de nós, podemos realmente descansar e estar em paz. Para isso é que construímos as nossas casas.</p>

<p class=Normal>Infelizmente, muitas casas são lugares de conflitos e brigas, e ainda pior, de tumulto. Isso não é um verdadeiro lar. O que queremos dizer com o lar ideal, o lar real, é o refúgio no Buda, Dhamma e Sangha, que tomamos profundamente dentro de nós mesmos. Um refúgio significa: um lugar de paz, um lugar de liberdade do perigo, um lugar de segurança, um lugar onde não há mais medição. O lar é um lugar onde podemos ser nós mesmos, estarmos em paz, estarmos à vontade, não sermos nada, apenas o vazio e liberdade.</p>

<p class=Normal>O objetivo da meditação é fazer com que entremos em contato com o nosso verdadeiro lar, o lugar de quietude dentro de nós. Percebemos que o nosso verdadeiro lar está conosco o tempo todo. Mas como vamos chegar lá? A porta do nosso coração está aberta para nós, não importa o que façamos. Liberdade, amor, compaixão, quietude, não controlar, abrir mão, soltar, é a porta para o lar dentro de nós. Não conseguimos entrar medindo e julgando. Entramos com a quietude e sem pensar. Assim passamos pela porta do nosso lar interior, onde podemos estar de acordo com a nossa vontade, a qualquer momento.</p>

<p class=Normal>Se conhecemos esse lar, esse lugar, isso significa que quando saímos de lá para o mundo, onde trabalhamos duro, nos esforçamos e lutamos para o bem de outros seres, pelo menos temos um lugar para onde voltar, um refúgio, um lar. Quando não temos esse refúgio, esse lar, não sabemos como escapar do tumulto da vida.</p>

<p class=Normal>Nos suttas, o Buda diz que devemos saber a gratificação, o perigo e a escapatória dessas coisas mundanas. Podemos entender a gratificação, podemos entender o perigo dos caminhos mundanos, mas por favor, saibam também como escapar. Eu lhes ensinei a escapatória: ir para o lar interior. Assim, conhecendo esse lar interior e tendo se familiarizado com ele, podemos sempre voltar a qualquer momento. É um lugar de descanso, o refúgio real do Buda, Dhamma e Sangha. Aquele que vê o Dhamma vê o Buda, não é Gotama o Buda, que faleceu em Nibbana milhares de anos atrás. Vemos o Dhamma dentro do nosso coração, aquele estado de liberdade, de conhecimento, o despertar, a libertação, que é o refúgio real. Isso é o que nos conecta, e todos os demais, aos <i>Ariyas</i> do mundo: é a '<i>Ariya Sangha</i> dentro do coração'. Por isso é um refúgio, porque está no fundo do nosso íntimo. Sabemos que é um refúgio, porque não importa o que estejamos fazendo lá fora no mundo, sempre podemos voltar para o nosso lar e colocar os pés para cima e tomar uma xícara de chá, como se fosse. Podemos voltar para casa e realmente relaxar no refúgio do nosso verdadeiro lar.</p>

<p class=Normal>Quando saímos de casa todas as manhãs - não me refiro à nossa casa, quero dizer o nosso lar interior - saímos para os nossos deveres e para o trabalho. Mas sabemos que sempre temos um lugar para voltar, um lugar de descanso e paz. Isso é o que fazemos no mundo. Esta tarde irei para Sydney. Vou trabalhar lá, mas levo o meu lar interior comigo. A qualquer momento, se nos sentimos cansados ou estressados, podemos voltar para o nosso lar interior. É um recurso maravilhoso. Às vezes, como um monge sênior, faço muitas coisas, e me sinto muito cansado fisicamente. Então, o que precisamos fazer é só ir para o lar interior e descansar por um tempo. Quando saímos podemos estar tão lúcidos, tão calmos e tão claros.</p>

<p class=Normal>É disso que vem o Dhamma, do lar interior. Lembro que uma vez, há muitos anos, fui a Canberra para dar algumas palestras. Canberra é um lugar muito frio e úmido. Não tendo estado lá antes, é claro, eu não levei as roupas apropriadas para o frio. Depois de apenas um par de dias eu peguei um forte resfriado. As pessoas em Canberra insistiram em me levar para visitar um monastério em Bundanoon, apenas para passar o dia. As pessoas nesse monastério insistiram em manter-me lá até muito tarde, e para se despedirem, elas organizaram toda uma cerimônia para dizer adeus. Quando finalmente votei para Canberra, onde deveria dar uma palestra, eu não tinha tomado banho, não tinha feito a barba, e tinha apenas cerca de quinze minutos para tomar uma xícara de chá. Eu tinha que dar uma palestra pública e me sentia absolutamente terrível. Meus olhos estavam lacrimejando, meu nariz estava escorrendo, eu estava espirrando e tossindo. Eu estava com um forte resfriado. Mas eu tinha que dar a palestra. Lembro-me de começar a palestra, mas foi absolutamente impossível. Eu simplesmente não conseguia manter uma linha de pensamento antes de espirrar e meus olhos lacrimejarem. As pessoas estavam com pena de mim, então eu disse, "Ok, vamos parar a palestra e meditar por meia hora". Nós meditamos por meia hora e eu fui para o meu lar interior. Depois que a meditação terminou, mais tarde me disseram, dei uma palestra realmente brilhante. Meu nariz parou de escorrer. Eu parei de espirrar. Meus olhos pararam de lacrimejar, e eu me senti tão feliz quanto poderia estar. Esse é o recurso que temos disponível, não importa o que esteja acontecendo. Às vezes tenho que lidar com o estresse do corpo, e até mesmo com o estresse do mundo, mas o meu recurso é o meu lar interior. Ao irmos para o mundo temos esse lugar, um recurso, um refúgio. Podemos usar esse refúgio habilmente.</p>

<p class=Normal><b>Um Lugar Sagrado</b></p>

<p class=Normal>Encorajo todos os Budistas a terem um lugar em suas casas, se não for um quarto, pelo menos um canto na casa, que seja o seu santuário, seu canto religioso. Às vezes, vejo como os banheiros são grandes. Alguns feitos com mármore, com torneiras extravagantes. Para que são usados? As pessoas usam esse local para limpar seus corpos!</p>

<p class=Normal>As pessoas também têm essas cozinhas incríveis, salas de estar, salas de jogos, salas de TV, e salas de jantar, quartos enormes, gigantescos, do tipo suíte. Mas muito poucas casas têm um quarto espiritual. Um quarto reservado só para o cultivo da prática do Dhamma, ou da prática religiosa. As pessoas não têm um refúgio espiritual nas suas casas, um lugar onde não limpem os seus corpos, mas limpem as mentes. Um lugar onde não estejam alimentando o estômago, mas que alimentem o coração. Eu acho que isso é tão necessário no mundo de hoje, ter uma sala de meditação, um santuário - um lugar de apenas paz e silêncio.</p>

<p class=Normal>Se vocês realmente não têm um quarto nas suas casas para fazer isso, perguntem a si mesmos: "Eu preciso de todas essas outras salas?" Elas são realmente tão importantes assim, um escritório e todo o demais? Coloque o escritório em um canto do seu quarto, e coloque a sua sala de meditação no lugar do seu escritório. O que é mais importante? Mas se você não tem um  quarto disponível, pelo menos, use um canto de algum quarto silencioso, um espaço tranquilo, onde você possa colocar a sua estátua do Buda, ou as suas fotografias, e os seus livros do Dhamma. Tenha isso como um espaço sagrado em sua casa, um lugar onde você pode ir a qualquer momento. Depois de um tempo, meditando lá regularmente, recitando, mesmo lendo livros do Dhamma, esse lugar acumula poder e se transforma num ponto de energia na sua casa. Um lugar onde você pode simplesmente sentar, porque a única coisa que você faz ali é: meditar, recitar, ler livros do Dhamma, aquietar. Esse lugar se torna psicologicamente habilitado como um lugar de paz.</p>

<p class=Normal>Tenho ensinado desta forma por muitos anos, encorajando as pessoas a criar esses espaços nas suas casas, ou no canto de algum quarto. Algumas pessoas me contaram histórias incríveis sobre o que acontece quando têm esses lugares tranquilos. Sempre que ficam nervosos, ou tensos, ou têm uma discussão com a esposa, ou o marido, elas simplesmente se retiram para o seu canto tranquilo e sentam-se para meditar por algum tempo. Isso salva muitos casamentos, e muita dor. Uma família me disse certa vez, que o filho e a filha estavam tendo uma discussão, uma briga. O filho bateu na filha, ou algo parecido, em vez de bater de volta, ela correu para o quarto de sua mãe, sentou no lugar sagrado e meditou por alguns minutos. Os pais ficaram muito impressionados, porque nunca tinham lhe ensinado a fazer isso. Ela simplesmente sentiu que quando estivesse muito decepcionada, ou  com muito medo, ou muito tensa, aquele era o lugar para ir. É maravilhoso para a sua família poder ter um lugar como esse, para que as pessoas da sua família, além de você mesmo, o seu parceiro ou filhos, tenham um lugar, um refúgio, que os recorde do seu lar interior.</p>

<p class=Normal>Quando temos um lugar na casa, que é um local sagrado, devemos nos certificar que o local não seja usado para nenhuma outra atividade. Por favor, respeitem a sacralidade da área. Não usem o local para ouvir o rádio ou CDs, ou para escrever livros, ou qualquer outra coisa. É um lugar sagrado, um lugar para não fazer nada, um lugar de relaxamento. Em qualquer outro lugar do mundo temos que fazer esforço, temos que exercer o controle, temos que fazer nossos deveres, e fazer o trabalho que é esperado de nós. Temos que suportar pessoas tolas dizendo para fazermos coisas estúpidas. Mas o fato é que quando vamos para o nosso cantinho, ali podemos estar em paz e abrir mão, soltar. É o nosso pequeno monastério, o nosso pequeno refúgio, o "Pico do Abutre" em nossa casa, e isso ajuda muito. Esse é um conselho hábil para vocês.</p>

<p class=Normal>Às vezes, podemos encontrar um local adequado, mesmo quando não estamos em nossa própria casa, mesmo quando estamos no nosso local de trabalho. Li recentemente sobre uma pessoa que fez uma coisa muito hábil para poder meditar no trabalho. Essa pessoa não conseguiu encontrar um lugar para meditar. Ela não conseguia sentar e meditar no seu escritório, porque vocês sabem como é o mundo. Você está sentado em seu escritório sem fazer nada, e com certeza alguém virá para pedir alguma coisa. Eles não vão deixá-lo sozinho, porque todo mundo está ocupado e ao verem que você não está fazendo nada, então é porque você está  disponível. Não livre em paz, mas livre para ajudá-los. "Você não está fazendo nada no momento, você pode nos dar uma mão?" Eles não percebem que não fazer nada e meditar pode ser tão importante e valioso. As pessoas não respeitam a paz em nossa sociedade, elas pensam que é uma evasão. É por isso que as pessoas ocupadas tendem a fazer as outras pessoas se ocuparem, porque elas não respeitam a tranquilidade. Então aquela pessoa decidiu que a cada hora ela iria fechar os olhos e meditar por um minuto. Não poderia ser exatamente no intervalo de uma hora, porque se houvesse uma conversa telefônica, ou uma reunião com um cliente, ou algo assim, ela teria que adiar por algum tempo. Mas, a cada hora ela sempre meditava por um minuto. Ela fechava os seus olhos, sentada no seu escritório, apenas ficando quieta e apreciando a atenção no momento presente, o silêncio e a respiração. Isso é lindo. Ela só tinha um minuto de silêncio e quietude. Funcionou tão bem que as pessoas que passavam, vendo-a com os olhos fechados, pensavam que ela estava pensando em alguma coisa, ou tomando alguma decisão.</p>

<p class=Normal>As pessoas não sabiam o que ela estava fazendo. Como não era por muito tempo, elas não a incomodavam. Ela tinha um minuto de paz a cada hora de trabalho. No seu escritório, ninguém sabia o que ela estava fazendo, e ela conseguiu o que queria. Imaginem se vocês fossem para o escritório e sentassem de pernas cruzadas num canto, o seu chefe viria e diria: "Nós não estamos lhe pagando para fazer isso, volte para o seu computador e trabalhe." Mas não foi isso que aconteceu. Ela só tomou um minuto de silêncio a cada hora, na sua escrivaninha, de modo que ela estava continuamente em repouso. Depois de 59 minutos de trabalho duro, ela fazia uma pausa de um minuto para se recompor, e para ficar quieta. Essa pessoa descobriu que tinha muito mais atenção plena durante os 59 minutos seguintes e assim a sua produtividade aumentou. Ela estava mais alerta, percebia os problemas com mais rapidez, na verdade uma funcionária mais eficiente depois do minuto de silêncio.</p>

<p class=Normal><b>Boa Gestão</b></p>

<p class=Normal>Muitos anos atrás, eu estava na Tailândia, num voo doméstico de Ubon para Bangkok. Me foi dado um exemplar do jornal Bangkok Post, e na seção de atrações havia um artigo sobre o Hotel Mandarin Oriental, em Bangkok. Esse é um hotel muito famoso. Naquele ano, eles ganharam um prêmio, como o melhor hotel do mundo! As pessoas na Tailândia ficaram muito, muito impressionadas, e satisfeitas com esse grande prêmio para um de seus hotéis. Então, por causa disso, vários artigos foram escritos sobre o Hotel Mandarin Oriental.</p>

<p class=Normal>O autor daquele artigo em particular entrevistou o gerente, e perguntou: "Por que o seu hotel ganhou esse grande prêmio este ano? Qual é o seu segredo? Diga-nos algumas das coisas que você faz para tornar o seu hotel bom o suficiente para ganhar um prêmio internacional". Uma das coisas que o gerente disse que fazia era a cada ano enviar cada membro da sua equipe - os porteiros, pessoal de limpeza, concierge, os cozinheiros, e os gerentes - para um monastério para meditar por uma semana. Não era tempo descontado das férias, era por conta da empresa. Então, lhe perguntaram por que ele fazia isso. O entrevistador quis saber se ele era um Budista fundamentalista, querendo converter todos da sua equipe. "Não", ele respondeu, e passou a explicar que isso era simplesmente um princípio básico de boa gestão. Meditar durante uma semana no monastério resultava em que a equipe não tinha licença médica tantas vezes, e eles não ficavam tão irritados uns com os outros. Não havia conflito na força de trabalho, e eles também eram muito mais sensíveis às necessidades dos hóspedes do hotel. São apenas pessoas melhores, pois são pessoas mais felizes. Gerir um hotel, você não quer que as pessoas que estão trabalhando estejam mal-humoradas o tempo todo, você quer que os hóspedes sejam recebidos com um sorriso. Você deseja ver as pessoas felizes, como resultado elas trabalham melhor. É um princípio básico de boa gestão enviar os colaboradores para um retiro de meditação, uma vez a cada ano.</p>

<p class=Normal>É uma pena eu não ter guardado uma cópia do referido artigo. Vocês poderiam tirar cópias para mostrar para o chefe de vocês. Assim, no próximo ano, vocês poderiam vir a este retiro pago pela companhia. Vocês poderiam dizer ao seu chefe: "Por favor, você pode pagar os 230 dólares? É do seu interesse!" O ponto da história é que o gerente do hotel valorizou os resultados da meditação na vida diária. Ele realmente pode vê-los no prêmio que o hotel ganhou naquele ano. Ele pode vê-los na maior eficiência, atenção e sensibilidade da sua equipe. Qualquer tipo de trabalho em que estejamos, tendo essa atitude, o trabalho é feito mais rapidamente e com mais alegria. Quer seja: o trabalho de um abade, o trabalho de um anagarika, o trabalho de mãe, o trabalho de marido, o trabalho de gerente, ou o trabalho de lavar pratos; qualquer coisa que façamos, iremos descobrir que somos mais eficientes.</p>

<p class=Normal>Quando compreendemos as coisas desta forma, podemos ver as conexões entre a meditação e o trabalho. Por vezes, não há uma diferença tão grande de um para o outro. Descobrimos que podemos trabalhar de forma mais eficiente com uma mente clara e pacífica, isso torna a meditação valiosa. Percebemos o seu valor, não apenas para o Despertar, mas na verdade para nos conduzir pela vida. Isso significa que realizamos mais.</p>

<p class=Normal><b>A Felicidade da Meditação</b></p>

<p class=Normal>Uma das coisas que eu sempre enfatizo com relação à meditação é a felicidade da meditação. A intenção da meditação é ser divertida. A meditação deve ser divertida. Na noite passada, um dos monges me contou uma história sobre Ajahn Mun que eu nunca tinha ouvido antes. Ajaan Mun era um grande mestre Tailandês de meditação. Um monge que havia passado muito tempo com ele, e o conhecia muito bem, disse que ele tinha um grande senso de humor, e que ria muito, uma grande risada, uma risada contagiante. Eu nunca soube disso acerca de Ajaan Mun. Mas faz muito sentido, porque é isso que os Arahants fazem, eles riem muito e sorriem muito. Eu sei que isso é um pouco atrevido, mas às vezes eles são chamados de 'Ha Ha Harahants'. Eu vou entrar em apuros por isso, mas não me importo. Foi muito bom ouvir essa história.</p>

<p class=Normal>A felicidade é uma coisa importante na meditação. Se você sentir felicidade na sua prática de meditação, sempre irá querer meditar. Não é o caso de se levantar pela manhã e dizer: "Ah, tenho que fazer a minha meditação agora. Devo tirar isso da frente para poder tomar o café da manhã." Você sabe como é? Você faz a sua meia hora todos os dias como se tomasse um remédio. Não é nada disso. Se você realmente entende o que é a meditação, você ama fazer meditação. Você só quer fazer isso. Às vezes, você tem que tirar da frente o café da manhã para meditar, ou você tem que tirar da frente o seu trabalho para meditar. Você senta na sua cadeira, ou no seu banco, ou na sua almofada, e a sua mente salta sobre o silêncio. O Buda disse que quando a mente salta ou pula sobre a quietude, a tranquilidade, a calma, o não-fazer, esse é um importante estágio no caminho da sabedoria, no caminho para a iluminação.</p>

<p class=Normal>Espero que eu tenha condicionado muitos de vocês forte o suficiente para perceber o quão bonito é o silêncio. Para que em momentos durante o dia, quando vocês não tenham nada para fazer, a sua mente salte para a oportunidade de quietude, em vez de tentar preencher essas lacunas com coisas estúpidas, coisas inúteis, que são apenas distrações irracionais. A mente agarra a chance, vai para a quietude, estabilidade, paz e liberdade.</p>

<p class=Normal>Esse é o sinal de um praticante, alguém que está no caminho. Esse é o sinal de alguém que tem sabedoria suficiente para que a sua mente reconheça o que é de seu próprio interesse. Para que no período da manhã, ou à noite, a mente apenas salte para a sua almofada de meditação. Sua meditação não é um medicamento, não é algum tipo de castigo, não é algum tipo de penitência, é simplesmente algo que você quer fazer. A razão porque algumas pessoas que são cristãs não vão à igreja, é porque isso é chato, elas não gostam de ir. Porque é domingo, elas não saltam e dizem: "Vamos para a igreja, vamos lá e ouvir um bom sermão". Isso se tornou chato e frio. É por isso que as pessoas se afastaram das igrejas no Ocidente. As pessoas também irão se afastar da meditação e parar de meditar rapidamente, a menos que se divirtam com isso.</p>

<p class=Normal>Assim, desenvolver a diversão na meditação em casa e aqui, onde quer que estejamos, é a maneira de dar continuidade a essa prática. Pouco a pouco, dando  continuidade à prática no mundo, mantendo-a por conta da diversão, por conta da paz, por conta de um lugar de liberdade. Não temos outra escolha. Algumas pessoas dizem, e eu entendo isso muito bem, porque era igual quando eu era um leigo, que se você não meditar por um dia, é como não comer. Seu coração se sente doente, sem força, e você fica mal-humorado, fica irritado, porque você não está recebendo esse alimento de felicidade. Não importa se as pessoas disserem que você está viciado na meditação. Ótimo! Seja viciado na paz, na felicidade. Seja viciado na liberdade, não existe vício melhor.</p>

<p class=Normal>Algumas pessoas dizem que não devemos nos apegar a essas coisas, e elas citam o símile da balsa. O Buda disse que a balsa era só para atravessar o rio de uma margem para a outra, mas que não devemos nos agarrar à balsa (<a href="../sutta/MN22.php">MN 22</a>). Temos que soltar da balsa uma vez que tenhamos atravessado para a outra margem. Mas é claro que não devemos jogar fora a balsa no meio do rio! Isso é o que muitas pessoas fazem. Portanto agarre-se a essa balsa, apegue-se à meditação, apegue-se aos preceitos, e apegue-se à bondade.</p>

<p class=Normal>Entendam deste símile a importância dos estados pacíficos, a importância da bondade, e então receberemos nossa recompensa. Lembrem-se dos preceitos. Lembrem-se da bondade, da generosidade, da gentileza, do altruísmo que tenhamos feito ao longo do ano. Em seguida, receberemos o pagamento na nossa meditação. O pagamento é a mente bela. Você entenderá que esta mente bela é a razão porque mantemos os preceitos, porque somos generosos, por isso que damos, por isso que damos de nós mesmos, por isso que perdoamos os outros, e porque perdoamos a nós mesmos. É tudo parte de <i>dana</i>, tudo parte da generosidade. Por isso que praticamos o amor bondade e damos às pessoas o benefício da dúvida. Nós damos a nossa felicidade e compartilhamos nossos méritos com os outros. Por que fazemos isso? Fazemos isso porque vemos que isso realmente faz esta mente tão bela. Sentimos isso no dia a dia, temos algo dentro de nós do qual nos sentimos muito, muito orgulhosos. É bom sentir orgulho da bondade.</p>

<p class=Normal><b>Aquilo que é Digno de Louvor</b></p>

<p class=Normal>A bondade é digna de louvor. A boa meditação é digna de louvor, e é por isso que devemos louvar a nós mesmos. Diga para si mesmo como a meditação é boa, como é maravilhosa. Assim você irá fazer isso de novo, e de novo. A mente se alimenta de louvor, se alimenta de alegria. Use isso como um dos meios hábeis, para incentivar-se mais, e mais, e mais. Nós até temos uma palavra no Budismo: <i>Sadhu, Sadhu, Sadhu</i>, muito bem, muito bem, muito bem! Vocês já ouviram isso tantas vezes.</p>

<p class=Normal>No Budismo usamos o louvor, o encorajamento, porque isso funciona. Então venere aquilo que é digno de veneração. Não elogie as pessoas tolas, não louve as estrelas do esporte que ganham troféus, ou as estrelas do cinema, ou o que quer que seja. Se alguém ganha uma guerra, não louvem esse tipo de coisa. Louve aqueles que são dignos de louvor. Não vale a pena elogiar as qualidades do mundo. Se você se tornar um milionário, isso não é digno de louvor.</p>

<p class=Normal>O que é digno de louvor? Alguém que acabou de dar flores no templo, ou alguém que se dedica à meditação, são dignos de louvor. Talvez, tenha sido a primeira vez que ele esteve num retiro, e se saíu tão bem. Isso é digno de louvor. Alguém que pela primeira vez tenha mantido a mente no momento presente, mesmo que apenas durante parte do tempo durante este retiro de nove dias, isso é digno de louvor. Louvado seja o que é digno de louvor. Trabalhe naquilo que é verdadeiramente viável, e então encoraje-se, incentive as boas qualidades no mundo. Isso significa que a meditação se torna forte. A bondade se torna forte. A virtude se torna forte. Não só significa que o nível de felicidade na vida aumenta, mas também significa que quando você vem para um retiro de meditação, todo o trabalho de base já foi feito. Você vem para o retiro não com as mãos vazias, mas com todas essas grandes qualidades espirituais, com essa grande riqueza espiritual, com toda a bondade que você fez.</p>

<p class=Normal><b>Praticando a Virtude</b></p>

<p class=Normal>Nas meditações profundas, especialmente nos estágios dos <i>nimittas</i> e dos <i>jhanas</i>, a mente se torna poderosa, forte e bela. Mas os <i>nimittas</i> também podem surgir mais cedo do que o esperado; eles brotam da respiração, simplesmente porque são demasiado poderosos para serem ignorados. Mas se os <i>nimittas</i> não surgem, ou se quando surgirem forem muito fracos, isso pode significar que a sua mente não é pura o suficiente, não é forte o suficiente. A mente não tem poder suficiente através da bondade, da virtude, da pureza, da força. Quando se percebe isso, também se compreende que os preceitos não são observados apenas para renascer no paraíso. Não se pode meditar e simplesmente esquecer os preceitos como sendo um "adendo cultural" ao Budismo. Não observamos os preceitos só porque diz isso nas escrituras, ou porque um monge disse isso. Pode ser visto em primeira mão, que uma das razões pelas quais temos que manter esses preceitos é para ter sucesso na meditação.</p>

<p class=Normal>Quando vemos essa conexão em primeira mão, também vemos a importância de não somente manter os preceitos, mas também de realmente fazer o oposto da violação os preceitos. O oposto de matar é ajudar as pessoas, salvar a vida das pessoas, e aliviar a sua dor cuidando delas. Compaixão é o oposto da morte. O oposto de roubar é a generosidade, não apenas não tirando dos outros, mas também dando aos outros. O oposto de adultério é o compromisso fiel, manter as nossas promessas. O oposto da mentira é ser honesto e sincero, e falar gentilmente um com o outro. Nunca dizer uma palavra que você não goste venha ser dita para você mesmo. E, por último, o oposto de tomar bebidas alcoólicas e drogas que obscurecem a mente é desenvolver a atenção plena, e praticar a meditação, que clareia a mente.</p>

<p class=Normal>Nossa prática da virtude não é apenas evitar o mau, é também fazer esforço para fazer o bem. É um aspecto ativo de nossas vidas, apoiando: a comunidade, a BSWA, o monastério, nossos pais, os idosos, ou qualquer outra coisa que possamos fazer. Nós, na verdade, saímos e fazemos alguma coisa em vez de pensar: "Olhe para mim, eu sou tão bom, eu não mato, eu não roubo, eu não cometo adultério, não minto, eu não tomo álcool e drogas. Eu não falo com ninguém. Eu fico só na minha pequena casa durante todo o dia e toda a noite". Mas isso não é bom o suficiente! Será?</p>

<p class=Normal>Aqueles de vocês, que me conhecem há muito tempo, sabem o quão ocupado eu tenho estado, especialmente nos primeiros anos de construção do nosso monastério em Serpentine. Isso realmente foi um trabalho árduo, trabalhando todos os dias desde o início da manhã até tarde da noite, e depois tomar banho no lago frio, com o vento como um fator adicional de resfriamento. Costumávamos trabalhar o dia todo e quase não dormíamos porque ficávamos ao relento com o vento. Acordávamos no meio da noite e ficávamos acordados durante o resto da noite. Nas noites de sexta-feira, costumávamos ir para o nosso pequeno centro na cidade, no norte de Perth. Eu aguardava esse dia ansiosamente, porque primeiro antes de tudo poderia tomar um banho quente pela primeira vez na semana, e limpar toda a sujeira, e depois, poderíamos ter um bom sono para nos recuperarmos.</p>

<p class=Normal>Foi uma época muito difícil, e às vezes eu pensava que estava sacrificando a minha meditação. Eu pensava que estava trabalhando demais, e não tendo tempo para mim. Sempre que voltávamos à noite, simplesmente desmaiávamos até as quatro horas da manhã, para então sairmos da cama para mais um dia de trabalho. Foi tão difícil. Eu pensava que não estava fazendo nenhum progresso. Mas a surpresa veio quando eu tive uma semana de folga. Quando me sentei para meditar, fui direto de volta para os <i>nimittas</i> belos, e tive uma bela meditação. Num primeiro momento não pude acreditar. O que está acontecendo? Eu não tinha estado meditando faziam semanas, meses, realmente não de forma contínua. Eu tentava, mas sempre estava muito sonolento. Mas assim que tive algum tempo, tudo voltou novamente. Na época, eu não entendia muito bem porquê.</p>

<p class=Normal>Por que foi tão fácil meditar após um período tão longo de trabalho árduo? É claro, foi porque eu tinha acumulado virtude, aumentado o poder da mente. Eu estava sendo altruísta, dando-me para um dos maiores atos de bom <i>kamma</i> no mundo - a construção de um monastério. Foi um imenso ato de bom <i>kamma</i>. Eu estava realmente ajudando, eu estava colocando todo o meu esforço, e também realizando enormes quantidades de bom <i>kamma</i>. Assim, quando parei de trabalhar a mente bela estava lá, e ela simplesmente brotou na minha mente.</p>

<p class=Normal>Na época compreendi, como percebi várias vezes desde então, que não perdemos nada por dar aos outros. Não é como se perdêssemos energia, nós ganhamos mais energia. As pessoas às vezes dizem, "Ajaan Brahm trabalhou tão duro no retiro, deu duas palestras por dia, além de todas as entrevistas". Se forem contadas as horas que dei, foi na verdade um monte de horas. Na verdade, no mercado de trabalho, provavelmente ninguém esperaria que alguém trabalhasse tanto. No entanto, eu recebo tanta felicidade disso. Se recebemos felicidade, então é um bom <i>kamma</i>, e sempre que você parar, entrará em um espaço belo. Eu adoro fazer esses retiros. São as minhas férias, porque tenho meditações belas. Temos a oportunidade de iluminar as nossas mentes ao dar ainda mais.</p>

<p class=Normal><b><i>Samadhi</i> Acompanhado pela Virtude</b></p>

<p class=Normal>Não façam tanta distinção entre a meditação e a vida lá fora. Façam da vida lá fora um apoio para a meditação. Mantenham seus preceitos, mas também façam coisas boas. Prestem serviço à comunidade. Depois é só observar a respiração e você irá descobrir que esses estados mentais belos irão surgir. Tanta pureza! Tanta inspiração! Uau! Isso é tão bom, de onde veio isso? Isso veio de todo altruísmo, toda generosidade, do coração puro. O Buda disse que a meditação de <i>samadhi</i>, quando é acompanhada pela virtude produz grandes frutos, grandes benefícios. Podemos entender que quando a virtude está por trás da meditação, e a bondade sendo forte, então a sabedoria vem de <i>samadhi</i>. É a prática suportada pela sabedoria, que conduz à destruição das impurezas da mente, das contaminações, da ignorância.</p>

<p class=Normal>Portanto, como praticantes devemos treinar a virtude, torná-la completa. Devemos praticar a meditação. Completá-la. Devemos praticar a sabedoria e torná-la completa para realizar a iluminação. Mas, certamente, vocês podem ver como a virtude suporta <i>samadhi</i>. Assim, vivendo no mundo podemos praticar a meditação, praticando aquilo que lhe dá suporte, certificando-nos que somos virtuosos e bons.</p>

<p class=Normal>Assim é como vocês devem levar de volta para o mundo aquilo que aprenderam neste retiro. Há sempre ocasiões em que podemos praticar a virtude. Há sempre alguém no escritório, em casa, ou alguém que você conhece, que precisará do seu tempo, que você pode ajudar. Não pense que você está negligenciando a sua meditação. O que você está fazendo é construir os suportes para a meditação, a construção de suportes para a liberdade, a construção de suportes para <i>nibbana</i>.</p>

<p class=Normal>O Buda disse que mesmo os monges e as monjas não devem deixar de fazer méritos, fazer <i>puñña</i>. Quando ouvi isso pela primeira vez fiquei surpreso. Pensei na época que méritos era exatamente o que os leigos fazem. Pensei que no Budismo tradicional, ir aos templos, oferecer <i>dana</i>, observar os cinco preceitos e recitar, eram coisas de pessoas leigas. Mas isso também são coisas dos monges, são coisas de todos. Isso capacita a mente, e os frutos serão colhidos na meditação. Em retiros como este, vemos o quadro geral. Vemos como a meditação, a virtude, conduz à sabedoria, ao insight e como isso conduz à verdadeira liberdade. Isso conduz à  libertação das contaminações, a libertação das <i>asavas</i>, as impurezas da mente, livre do renascimento, e no final livre de <i>samsara</i>. Quer seja um monge ou um leigo, uma vez que vejamos o problema, uma vez que vejamos o que está realmente acontecendo, então vemos onde a felicidade, a verdade e a liberdade realmente estão.</p>

<p class=Normal>Chega um ponto em que não podemos nem mesmo esquecer esses ensinamentos, um ponto em que realmente não podemos jogá-los fora. Eles sempre voltam, de novo, e de novo, e de novo. Uma pessoa que eu conhecia veio para a BSWA logo no início mas depois foi embora e não praticou durante três ou quatro anos. Depois, ela voltou novamente, e disse: "Sabe, mesmo que eu tentasse, eu não poderia esquecer esses ensinamentos". Não podemos colocá-los de lado. O que acontece é que eles ficam gravados dentro de nós, como o reconhecimento de uma verdade, o reconhecimento da verdadeira felicidade, e do caminho para a liberdade. Já aconteceu comigo e isso também já aconteceu com muitos de vocês na sua meditação, que parece tão pura, que promete essa liberdade. Você pode não ser  capaz de apontar o dedo para o que é, e explicá-lo para você mesmo de modo tão claro, mas isso é real, está lá.</p>

<p class=Normal><b>Um Momento de Paz</b></p>

<p class=Normal>A primeira vez que meditei foi incrível! Os primeiros dez minutos estão gravados na minha memória para sempre. Foi no Wordsworth Room no Kings College da Universidade de Cambridge, na Inglaterra. Mesmo agora, eu lembro a sala, onde, pela primeira vez fiz meditação. Eu não entrei nos <i>jhanas</i> ou algo parecido, mas simplesmente me senti muito bem. Foi tão pacífico, e daquele momento em diante fui fisgado. É estranho como esse momento de paz parecia tão familiar, o que nos mostra que, espera aí, este é o caminho para a paz. É a coisa mais pura que já vi, esta é a verdadeira liberdade.</p>

<p class=Normal>O Buda disse: "experimentem a liberdade". Quando temos apenas o gosto dessa liberdade, ela permanece na nossa mente para sempre. É preciso desenvolvê-la e cultivá-la, até que tenhamos não só o gosto, mas toda a refeição. E essa refeição cumpre o seu papel, preenchendo a mente com sabedoria, e dando a libertação plena e verdadeira. Assim, cada um de nós - quer seja monge ou leigo - estamos nesse caminho para <i>nibbana</i>. Nós já fomos longe demais para pararmos.</p>

<p class=Normal>Quando vocês tiverem provado uma meditação profunda, vocês terão provado algo que excede em muito o poder, a felicidade e a liberdade de qualquer outra coisa no mundo. A mente se inclina na direção disso. A mente sempre volta, às vezes aos trancos e barrancos, para revisitar a experiência. Às vezes a mente se perde e não encontra o caminho de volta. Mas não será capaz de desistir. A mente não irá ser capaz de abandonar a tarefa. Ela vai continuar se inclinando na direção de <i>nibbana</i>. A experiência vai mudar o seu estilo de vida, pouco a pouco. Você muda o seu estilo de vida para se ajustar ao caminho para <i>nibbana</i>.</p>

<p class=Normal>Você não irá encontrar oportunidades suficientes para ajudar as pessoas, ou para praticar a generosidade, e você encara isso como sendo um privilégio, não uma obrigação. Se você participar de um comitê isso será um privilégio. Se for ajudar a comunidade de alguma forma, você diz: "Obrigado por me convidar, é uma coisa maravilhosa que eu possa fazer isso por outra pessoa". Você pratica bons atos e é generoso, porque isso é uma coisa maravilhosa de ser feita.</p>

<p class=Normal>No Budismo algumas vezes é dito que aqueles que entraram na correnteza (<i>sotapanna</i>) têm que ser cuidados pela Sangha. Na época do Buda, certa vez houve o caso de uma família, que se supunha serem <i>sotapannas</i>, que sempre davam muito para a Sangha na coleta de esmolas. Eles eram muito pobres e não tinham muito o que comer. As pessoas começaram a criticar os monges, dizendo: "É bom que vocês recebam essas coisas, mas essas pessoas, elas mesmas não têm o suficiente para comer". Então, o Buda convocou uma reunião e estabeleceu uma regra para esse tipo de situação. A Sangha concordou que, nessas circunstâncias deveriam ter compaixão com a família, e não aceitar muito deles. Algumas vezes acontece isso quando alguém tem muita fé. A pessoa acha que é muito melhor dar a sua comida para a Sangha, do que ela comer. É muito melhor passar fome. "Por favor, aceite. Fico tão feliz em dar, eu posso comer num outro dia, então por favor me dê a oportunidade de fazer mais méritos. Por favor! Por favor!"</p>

<p class=Normal>Assim, os monges tiveram que dizer, "Agora espere, o Buda disse que não podemos fazer isso, dito pelo Buda, por isso não podemos discutir sobre isso". Isso é o que acontece quando nós realmente entendemos como as coisas são. Às vezes, você tem que conter as pessoas. Estou falando principalmente sobre as pessoas que dão qualquer coisa, que dão a camisa que estão vestindo, e a comida de seus pratos. Às vezes elas até mesmo dão as suas vidas. Essas pessoas podem se tornar pobres, mas os seus <i>nimittas</i> são algo para ser visto. Uau! Quem se importa estar com fome quando se tem <i>nimittas</i> tão belos? Uau! Isso é muito bom. Essa é a pureza. Essa é de fato a realização de méritos inspiradora, e nós precisamos estar inspirados assim para entrar nos <i>jhanas</i>.</p>

<p class=Normal><b>Emoções Inspiradoras</b></p>

<p class=Normal>Não tenham medo das emoções inspiradoras. Se vocês tiverem a oportunidade de visitar os lugares sagrados na Índia, ou alguns dos antigos monastérios no Sri Lanka, Myanmar e Tailândia, façam valer o dinheiro gasto. Derramem todas as lágrimas que puderem. Sintam-se realmente inspirados. Imaginem o Buda ali sentado, imaginem Ajaan Chah na floresta nos primórdios ensinando os monges. Simplesmente permita que a alegria preencha e flua através de todo o corpo. Vocês ficarão tão inspirados. As pessoas na atualidade não sabem como corretamente se entregar às emoções positivas de alegria, inspiração e fé. Essas emoções são chamadas de poderes que controlam as faculdades, e são elas que realmente fazem a meditação avançar. É o caminho mais rápido para a iluminação.</p>

<p class=Normal>Então, visite esses lugares e obtenha alegria, obtenha inspiração. Quando ler os suttas, ou recitá-los, recite com o coração, e não apenas com a boca. Não se preocupe como soa do lado de fora, preocupe-se como soa dentro, e de onde está vindo. É ótimo ser capaz de recitar e compreender o significado. Ficamos tão inspirados, tão lindamente inspirados, e isso é pura emoção. Então, lá fora, no mundo, desenvolva emoções e inspirações puras. Elas só podem ser boas, e conduzem a <i>nibbana</i>.</p>

<p class=Normal><b>Resumo e Conclusão</b></p>

<p class=Normal>Então, essas são algumas práticas que vocês podem realizar no mundo. Vocês podem fazê-las a qualquer momento. Em particular, há muitas oportunidades para praticar os dois primeiros estágios da meditação: a atenção no momento presente e a atenção silenciosa. Quando vocês estiverem trabalhando na sua escrivaninha, pratique a atenção no momento presente, trabalhem em silêncio. O seu trabalho irá render muito mais. Ao dirigir o carro desliguem o rádio. Desliguem o CD. Nem mesmo ouçam um discurso do Dhamma por Ajaan Brahm. Ouçam o silêncio, porque de qualquer maneira aquilo que vocês ouviriam seria Ajaan Brahm lhes dizendo para ficarem quietos. Qualquer pessoa que realmente entenda diria, "Ah, sim, isso está certo", e simplesmente desligaria.</p>

<p class=Normal>Existem tantas oportunidades na vida para realmente praticar a atenção no momento presente, e a atenção silenciosa. Existem tantas ocasiões e oportunidades durante o dia para abrir mão, soltar. Mesmo se estivermos atrasados para o trabalho, às vezes simplesmente não é possível fazer nada a respeito, solte. Preocupar-se com isso não fará você chegar mais rápido. Veja se vocês podem aprender a ficar apenas em paz com o mundo, e tentem incorporar estas sugestões na sua prática. Pratiquem o não controle, abrindo mão. Há tantas oportunidades na vida. Muitas vezes, não há nada que podemos fazer. Não há nenhum modo de fazer com que a aeronave voe mais rápido porque você está atrasado. Não podemos ir até o capitão e lhe pedir para voar mais depressa, simplesmente não podemos fazer isso na vida, é por isso que temos que abrir mão. Nós todos temos que abrir mão de algumas coisas na vida, por isso, poderíamos muito bem começar agora.</p>

<p class=Normal>Aprendemos muito como abrir mão neste retiro de meditação. Quando forem para o mundo, terão aprendido a habilidade de abrir mão das coisas que não podem controlar. Já fizemos isso durante todo o retiro, então agora podem continuar fazendo isso. Isso realmente nos ajuda no mundo lá fora. As coisas que não podemos fazer nada a respeito, apenas abrimos mão. Se este é o seu marido, ou a sua esposa, se você não pode fazer nada à respeito, basta abrir mão. Se os seus filhos estão bagunçando e você não pode interferir, basta abrir mão. Através da prática, aprendemos a habilidade de abrir mão.</p>

<p class=Normal>Com as crianças, sempre podemos usar o símile do búfalo. Certa vez, na Tailândia, um homem estava levando o seu búfalo para pastar no campo. O búfalo ficou muito animado e saiu correndo. O homem tentou detê-lo. Tente parar um búfalo. Pense no tamanho de um búfalo. É enorme, e ele era apenas um pequeno agricultor Tailandês. Ele segurou a corda. A corda se enrolou em torno de seu dedo e arrancou o dedo! Ele veio para o monastério faltando metade de um dedo. Obviamente, havia sangue por toda parte, e muita dor. O abade levou o homem para o hospital local para ser medicado. Depois o homem se recuperou. Mas essa é uma grande metáfora. A metáfora é que apenas um tolo tentaria parar um búfalo; simplesmente ele vai lhe arrancar os dedos. Seu marido, sua esposa, seus filhos, e às vezes a sua mente é como um búfalo. Se você tentar detê-los, o que acontece é que algo é "arrancado", e você terá muita  dor e sofrimento. O que acontece se você soltar o búfalo? O búfalo só irá correr cerca de meio quilômetro ou até a estrada. Ele não irá tão longe. Ele pára e se acalma, e então você pode andar até lá e suavemente trazê-lo de volta. Ele para, e fica fácil de ser controlado. Às vezes é isso que precisamos fazer com maridos e esposas, e as crianças. Elas fogem, e depois param e você pode trazê-las de volta. Muitas vezes, a mente é assim na meditação, sai correndo atrás de pensamentos e fantasias. Deixem-na ir. Não deixe que ela arranque o dedo. Tendo perambulado um pouco, ao parar, depois de ter a sua diversão, agora traga a mente de volta para o silêncio.</p>

<p class=Normal>Esse na verdade é um bom um símile para a nossa vida. Estamos aprendendo a soltar, abrir mão. Podemos fazer isso com a mente. Também podemos fazer isso com outras coisas na vida, e tornar-nos uma pessoa muito mais tranquila e um gestor muito mais eficiente. Podemos nos tornar num gestor do marido, da esposa, dos filhos, um gestor das contas, um gestor da vida. Com frequência costumo dizer que a meditação é como um microcosmo do mundo real, se soubermos como meditar, saberemos como viver. Se soubermos como abrir mão e estar em paz, saberemos tudo o que precisamos saber sobre a vida no mundo.</p>

<p class=Normal>Podemos viver uma vida muito feliz, uma vida muito bonita, mesmo se quisermos dar um passo além e realizar a iluminação. Sabemos como fazer isso também. É o mesmo processo apenas intensificado. Então, isso é o que fazemos lá fora no mundo, não pense que estar lá fora vai ser uma transição muito grande. Vai ser um choque para o sistema, mas, na verdade, você vai aprender a se adaptar. Você pode estar em paz entre os pacíficos. Você pode trabalhar com as pessoas que estão trabalhando, e rir com os que estão rindo. Você pode ser solidário com aqueles que estão chorando, e você tem todos os recursos para ajudar e servir no mundo.</p>

<p class=Normal>Mencionei no início deste retiro que não há diferença entre a meditação <i>vipassana</i> e meditação <i>samatha</i>. Agora vou acrescentar também que não há diferença entre o caminho do <i>Bodisatva</i>, e o caminho do <i>Arahant</i>. Essas são apenas diferenças que as pessoas criam, porque elas realmente não entendem. A melhor coisa que alguém pode fazer para o mundo inteiro, o melhor presente que alguém pode dar aos outros, é tornar-se Iluminado, de modo que possa ter enorme compaixão e enormes recursos de sabedoria para compartilhar com os outros. Você realiza a iluminação para o seu próprio bem e para o bem dos outros. Não existe qualquer diferença entre essas duas formas. As pessoas criam todas essas diferenças. Então, vá para o mundo, e para seu próprio bem realize a iluminação, e realize a iluminação para o bem dos outros.</p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>

<p class=Normal>Fonte: Palestra dada no dia 26.04.2003 ao final de um retiro de nove dias.</p>



<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>

<!-- Counter/Statistics -->
<script language="JavaScript"
src="http://us.js2.yimg.com/us.js.yimg.com/lib/smb/js/hosting/cp/js_source/whv2_001.js">
</script>
<script language="javascript">geovisit();</script>
<noscript><img src="http://visit.webhosting.yahoo.com/visit.gif?time"
alt="setstats" border="0" width="1" height="1"></noscript>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-42601555-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>