<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"processo ");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO'," 9 Agosto 2008 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'> A Prática como um Processo  </Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'>Ajaan Pasanno </Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>

<p class=Normal>&nbsp;</p>

<p class=Normal>Um assunto que poderia ser levantado para discussão  diz respeito às realizações ou progresso na prática. É algo com que todos nós nos preocupamos: falamos sobre isso e acabamos envolvidos nisso de vários modos. Essa é a atitude que temos em relação ao nosso progresso na prática. Estamos avançando? Não estamos retrocedendo? Estamos piorando na prática, ou ...? Como medimos a nossa prática? </p>

<p class=Normal>Gastamos um bom tempo medindo a nossa prática nos comparando com outras pessoas. Vocês sabem: eles estão mais avançados do que nós estamos? Estamos menos avançados? Ficamos dando voltas com essa idéia de tentar medir o progresso ou crescimento na prática. É algo que precisamos investigar e vigiar porque podemos cair em extremos e acabar enredados tentando decidir o que é o progresso; e depois ir para um  outro extremo ao dizer que na verdade não deveríamos pensar em termos de progresso e que nós não deveríamos sequer nos preocupar em considerar o que é o progresso. </p>

<p class=Normal>Essa foi uma das coisas que me dei conta quando viajei pelos Estados Unidos, ao ler um artigo sobre a prática Budista, descobri que cada vez há menos ênfase na iluminação. As pessoas não querem mais falar sobre a iluminação porque é atemorizante pensar na prática levando em conta a iluminação; porque isso parece tão distante e remoto, significando que as pessoas estão tomando um padrão mais mundano para decidir o que a prática deveria ser. Eu penso que muito disso está relacionado com os extremos que adotamos ao tentar medir o progresso ou ao evitar medí-lo. Daí a confusão sobre o que é a prática e como nos relacionarmos com ela; ou o que devemos considerar ser crescimento e amadurecimento na prática. Então, eu gostaria de oferecer algumas reflexões sobre o que o Buda deu como padrões de crescimento no Dhamma, crescimento na prática e maturidade na prática. </p>

<p class=Normal>Há um conjunto de quatro dhammas dos quais não se fala muito. Eles são chamados os quatro dhammas que conduzem ao crescimento e à maturidade. O primeiro é estar em contato com uma pessoa sábia, <i>sappurisa sasevana</i> –  o simples contato com alguém que seja sábio. O segundo é ouvir o Dhamma, ouvir os ensinamentos, <i>sadhamma savanaa</i>. O terceiro é a reflexão com sabedoria, a sábia consideração, <i>yoniso manasikaara</i>. E por último, <i>Dhammanupata patipattaa</i>, praticar o Dhamma de acordo com o Dhamma. Esse é o padrão de referência para avaliar o crescimento. </p>

<p class=Normal>Uma das coisas que fazemos é tender a medir o progresso em relação às nossas  experiências. Temos algum tipo de experiência e pensamos “Isto é ...” e depois avaliamos isso e dizemos, “Isso quer dizer que de alguma forma estou progredindo.” E depois temos algum outro tipo de experiência e dizemos, “Bem, isso deve significar que estou regredindo.” Nós não olhamos para as coisas como um processo. Tendemos a isolar os incidentes, isolar as experiências; e depois medi-las, avaliá-las, e ficar felizes ou tristes  por causa delas. Os ensinamentos do Buda estão mais relacionados com os processos. Como nos envolvemos no processo de amadurecimento? Como entramos no processo de crescimento e progresso na nossa prática, ao invés de nos agarrarmos a alguma experiência ou mesmo de tentarmos criar alguma experiência, de modo que possamos dizer, “Ah, certo, definitivamente devo estar progredindo, devo estar crescendo.” </p>

<p class=Normal>É necessário interessar-se por esse processo. É algo cíclico, algo que não acontece numa progressão linear. Como podemos observar, em relação a ter contato com uma pessoa sábia, ouvir o Dhamma, reflexão com sabedoria, praticar o Dhamma de acordo com o Dhamma, essas são coisas que giram uma em torno da outra o tempo todo. Não estamos tomando uma progressão linear e indo do ponto A ao ponto B. É um processo que está em operação o tempo todo no nível externo e no nível interno, porque a pessoa sábia que deveríamos ter contato é também a pessoa sábia que está dentro de nós. </p>

<p class=Normal>No nível externo precisamos contar com professores, com pessoas que dêem o exemplo, assim precisamos buscar um professor, buscar alguém que seja um bom exemplo. E mesmo se estivermos vivendo num monastério, praticando em conjunto, nós também buscamos o professor, buscamos as pessoas que servem como exemplo. Nesse aspecto o apoio mútuo é muito importante. Não signfica que se você estiver no começo da fila você é um professor ou você é chamado de uma pessoa sábia. Para cada um de nós, é nossa responsabilidade dar o exemplo para os outros, e, à medida que vivemos em comunidade, tentar apoiar uns aos outros na prática. Assim, buscar um ao outro é buscar aqueles que nos podem encorajar e que nos podem orientar. </p>

<p class=Normal>Do mesmo modo em relação a ouvir os ensinamentos, se for sob a forma de um discurso formal ou ouvindo fitas, ou cds, ou lendo livros, qualquer que seja a forma pela qual recebamos, reflitamos e contemplemos os ensinamentos, ela favorecerá o crescimento. A nossa prática é nutrida através do contato com ensinamentos que sejam retos e de acordo com a verdade, <i>sadhamma sevan</i>. <i>Sadhamma</i> é o ‘bom Dhamma' que estivermos ouvindo, os bons ensinamentos – ensinamentos que estão de acordo com a Verdade. Investigando, ouvindo, escutando: escutar o Dhamma é uma das condições para o surgimento do entendimento correto. Se não ouvirmos os ensinamentos ou não tivermos contato com os ensinamentos que são retos e íntegros, é difícil que o entendimento correto surja. Só se você for um Buda perfeitamente iluminado ou um <i>paccekabuddha</i>, senão, será difícil. Precisamos ouvir, precisamos prestar atenção, precisamos ter contato com os ensinamentos. E se não estivermos ouvindo, não prestarmos atenção, então, é claro, mesmo se os ensinamentos estiverem sendo dados, eles não serão absorvidos, não encontrarão o seu lugar no coração. Portanto, abram os ouvidos para os ensinamentos. </p>
 
<p class=Normal>Reflexão com sabedoria é usar a capacidade de investigação para reconhecer de modo claro como é que as coisas funcionam. Como empregamos o nosso processo de pensamento? Isso é algo que nós temos: definitivamente temos habilidade para pensar. Algumas vezes a qualidade <i>yoniso</i> - considerar cuidadosamente, refletir com habilidade -  não é tão exercida quanto deveria. Lembro de um artigo que li (alguém escreveu um livro a respeito disso; o título do livro está baseado no artigo): numa pequena cidade, foi reportado um incêndio no andar superior de uma casa. A fumaça estava saindo pelas janelas e foram chamados os bombeiros. Eles foram até a casa, arrombaram a porta, subiram as escadas e descobriram que a cama estava pegando fogo, soltando fumaça e que havia alguém deitado na cama. Assim eles salvaram aquela pessoa e apagaram o incêndio. Depois do fogo ter sido apagado e o perigo terminado, eles perguntaram para a pessoa que estava na cama como o fogo havia começado. E a pessoa disse, “Eu não sei, já estava queimando quando deitei.”  Que é uma clara falta de <i>yoniso</i>! Nós damos risada disso mas, quantas vezes nós mesmos não fizemos coisas realmente imbecis? E o tipo de sofrimento em que nos metemos, a confusão e o caos que criamos nas nossas vidas, deveriam fazer soar todos os tipos de alarme! Mas nós os ignoramos e seguimos em frente e metemos a nossa cabeça nessa parede de sofrimento. Portanto, com <i>yoniso</i>, consideração cuidadosa, podemos olhar para o que é que está criando o sofrimento. Essa é a nossa diretriz para a prática. </p> 

<p class=Normal>O Buda, de um modo bastante brilhante, empregou o sofrimento como a base dos seus ensinamentos. O que está criando sofrimento? Qual é o meio para escapar do sofrimento? Qual é a causa do sofrimento? Nós precisamos ter habilidade para refletir e considerar. </p>
<p class=Normal>Existem vários e distintos modos para investigar isso: investigar a experiência do sofrimento; como ele é causado; de onde ele vem; em torno do que ele gira. Podemos também refletir simplesmente sobre a natureza da nossa experiência, quais coisas são prazerosas, quais são sofrimento. Qual é o meio de escapar das duas? Porque a nossa tendência natural é ir em busca do prazeroso e tentar evitar aquilo que causa sofrimento. Mas talvez essa não seja a saída. Precisamos ter habilidade para algumas vezes refletir e contemplar as coisas que nos dão prazer: elas podem proporcionar um prazer passageiro, mas intrinsicamente elas nos levam a mais sofrimento. Algumas coisas que são sofrimento não são necessariamente só sofrimento; pode haver algo benéfico nelas. Assim, precisamos ter a capacidade para investigar as nossas experiências também. Algumas coisas que também parecem prazerosas são de fato prazerosas e devem ser cultivadas. </p> 

<p class=Normal>Embora o Buda tenha usado o sofrimento como a base ou fundamento dos seus ensinamentos, também é hábil reconhecer que o caminho que seguimos, o caminho da prática, conduz a algo que é considerado felicidade e é prazeroso: o prazer ou bem-estar de manter os nossos preceitos; o prazer ou bem-estar da contenção; o prazer ou bem-estar da boa vontade e compaixão; o prazer ou bem-estar da mente em paz. Essas são coisas que precisamos cultivar, desenvolver. Precisamos entender o seu uso, ou função, e como fazer para que elas cresçam. Mas também temos de reconhecer a cobiça pelos prazeres dos sentidos que conduz a frustrações e assim a mais sofrimento. Do mesmo modo, o sofrimento é visto de duas formas: o sofrimento que conduz a mais sofrimento e o sofrimento que conduz ao fim do sofrimento. Podemos observar, quando estamos sofrendo com alguma aversão ou raiva, que isso é desagradável no momento presente e conduz a mais sofrimento. </p> 

<p class=Normal>Enquanto que com algo como o sofrimento de ter que agüentar alguma coisa, o sofrimento do treinamento, por exemplo, o sofrimento de ter que ficar sentado quieto e observar a respiração: há um elemento de sofrimento nisso, porém há também algo que conduz a uma sensação de bem-estar, à estabilidade, à tranqüilidade. Então é importante ser capaz de investigar, de considerar cuidadosamente as nossas experiências.  A nossa tendência, como eu disse, é sempre considerar tudo como branco ou preto: “Isso é prazeroso, eu quero isso.” -  “Isso é sofrimento, quero sair fora disso, quero evitar isso.” Enquanto que se olharmos para as coisas como um processo, veremos que há uma causa para que alguma outra coisa surja. Nós estaremos, deste modo, vendo as coisas sob uma outra pespectiva, nos relacionando com elas de uma forma diferente. Assim, a nossa consideração, a nossa reflexão, será um suporte para o nosso crescimento na prática. Temos que considerar: qual é a saída? Qual é o caminho para a paz? Qual é a direção para a liberdade, para a libertação? </p>

<p class=Normal>Com relação à prática do Dhamma de acordo com o Dhamma, há uma história na tradição Cristã. Durante a construção da grande catedral em Chartres, havia muita excitação pelo grande monumento que estava sendo construído. É claro que demoraram várias gerações para terminar a construção e praticamente toda a Europa tomou conhecimento da grande catedral que estava sendo construída. Numa ocasião, um peregrino italiano chegou em Chartres para prestar as suas homenagens e ver a catedral em construção. Chegando no final da tarde, entrando na cidade e olhando à sua volta, ele viu pessoas empacotando coisas e fazendo isso e aquilo, fazendo limpeza, e ele também viu um homem todo coberto com lascas de madeira e lhe perguntou, “O que você está fazendo aqui?” -  “Eu sou um carpinteiro, estou fazendo portas e janelas. Eu sou reponsável por todo serviço de marcenaria aqui.” Então ele viu uma outra pessoa, toda suja e desleixada, coberta com poeira e novamente perguntou, “O que você está fazendo aqui?” -  “Eu faço o trabalho em pedra, esculpindo as pedras para a construção.” E depois ele viu uma outra pessoa, coberta com várias cores e brilhando com pequenas lascas de vidro e perguntou, “O que você está fazendo aqui?” -  “Eu trabalho com o vidro, estou fazendo esses vitrais.” Depois ele viu uma velhinha que estava fazendo limpeza e varrendo ao final do dia e perguntou, “O que você está fazendo aqui?” Ela pára e olha para cima, olha ao redor e para a catedral com um olhar de veneração e diz “Eu estou aqui ajudando a construir essa grande catedral para a glória de Deus.” Essa é uma perspectiva diferente. Esse é o sentido de ver o que é a prática, ver o que significa quando dizem, “praticar o Dhamma de acordo com o Dhamma.” Você tem de ter uma visão de para o que você está indo, uma visão da razão pela qual você está praticando. Você tem de ter a visão de qual é o propósito. E isso é o que constitui a nossa prática. A prática que estamos realizando é o que está indo nessa direção. </p>
  
<p class=Normal>Se nós não tivermos uma visão daquilo que estamos fazendo, uma noção clara daquilo para o que estamos indo, e se tentarmos alçar as nossas mentes nessa direção, ficaremos presos nos nossos pequenos dramas do “eu” praticando o Dhamma e as “minhas” dificuldades e o “meu” sofrimento em vista disso. Ou acabaremos como simpáticos “mongezinhos” Vinaya, que obedecem todas as regras e assumem que esse é o caminho, ou tentando fazer a nossa meditação afundar ... essas coisas fazem parte do caminho. Precisamos aprender como manter os preceitos, precisamos aprender como agir com contenção de acordo com uma disciplina, <i>sila</i>. Mas também temos de ver qual é o propósito, em que direção estamos indo, como com a construção da catedral: aprisionados nas suas tarefas específicas, eles não entenderam o principal e deixaram de desfrutar da alegria da catedral à sua volta. Assim, na nossa prática também, nós temos de ter uma noção do que é a nossa prática, o que estamos fazendo, para compreendê-la com clareza. Mas aí, qual é a direção que estamos seguindo? Temos de estar sempre levantando a cabeça nessa direção. </p>

<p class=Normal>Nosso <i>sila</i> é para alçar a mente para além da tendência do descontrole, para que ela se estabeleça no sentido de desejar fazer a coisa certa, que está de acordo com a verdade. E a meditação não é só habilidade de manter a mente na respiração. É ser capaz de desenvolver uma atenção plena e uma claridade que seja capaz de permanecer com o objeto de meditação, mas que possa também ver qual é a sua natureza. Porque a mente se curva às nossas próprias sensações, percepções e pensamentos? Porque seguimos tomando isso como ‘eu’? Se não tivermos essa noção de erguer a mente para além da simples atenção plena ou de um estado de concentração, ficaremos atolados e não experimentaremos a libertação da mente, não experimentaremos a cessação do sofrimento. O mesmo com relação aos ensinamentos do Buda ou os ensinamentos sobre a sabedoria: eles não são só para serem memorizados ou copiados nos nossos livros de anotações e consultados quando nós precisamos deles. Eles são para serem interiorizados e reconhecidos. Para que eles servem? Eles servem para cortar as nossas delusões, para cortar os nossos apegos. Então temos de mantê-los sempre presentes. </p> 

<p class=Normal>Um modo de ver a nossa prática do Dhamma é seguir na direção de um objetivo: tem de ir na direção de alguma coisa. Outro aspecto disso, penso eu, é colocar os “pequenos dhammas” nos “grandes dhammas.” Quero dizer, sermos ordenados. <i>Dhammaanupatipadaa</i>: <i>anu</i> são as pequenas coisas que vão na direção dos grandes dhammas. Portanto, a nossa prática é uma prática progressiva, é um processo. Temos de aprender como ajuntar as coisas. E também como regressar. Algumas vezes temos dificuldades na prática, algumas vezes surgem dúvidas. Temos de aprender como regressar ao princípio. Aprender como começar de novo. Ir ao princípio e fazer aquilo que é o básico e depois evoluir a partir disso para que a nossa prática seja um tipo de crescimento constante. Nosso progresso então acontece por conta própria. Nós também temos que nutrí-lo, tomar conta do processo. Isso é o que precisamos aprender: como prestar atenção na prática e como desenvolver a nossa prática. A nossa maturidade vem disso. Há uma tendência de criar algum tipo de experiência e depois agarrar-se a essa experiência – tentar ter uma experiência mais clara do “Isso é que é o Dhamma,” “Isso é o que é a prática,” ou “Isso é o que é a paz.” Penso que isso é um grande obstáculo que sempre enfrentamos. Temos de aprender a dar atenção ao processo que envolve o cuidar das coisas que suportam o Dhamma – aí ele cresce a partir disso. </p>

<p class=Normal>Isso é o que Ajahn Chah enfatizava constantemente com relação à prática. Nós o procurávamos e perguntávamos todo tipo de coisas, “Dê-nos um método, diga o caminho.” E ele freqüentemente nos dizia, não é só  espremer alguma experiência da mente. É como plantar uma árvore: você não a planta na terra e depois força o seu crescimento. Você tem de preparar o solo, colocar a semente na terra, fertilizar a terra, tem de aguar a planta, cuidar dela ... e depois a árvore cresce por si mesma. E a árvore irá crescer de acordo com a sua própria natureza, e dará os frutos de acordo com a sua própria natureza. Não é nossa tarefa tentar estabelecer ou forçar para que a árvore cresça mais rápido, ou que dê frutos de um jeito especial de acordo com o que pensamos. Aprender como cuidar da mente é semelhante ao aprendizado de como cuidar de uma árvore. </p>

<p class=Normal>Ofereço estas palavras para a sua reflexão. </p>


<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>


<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>
