<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA'," sassata_uccheda");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO',"7 Fevereiro 2015 "); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'> A Crítica Budista a Sassatavada e Ucchedavada:<br>
A Chave para Compreender Corretamente a Origem<br> das Doutrinas do Budismo Original </Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'> Y. Karunadasa </Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>
<p class=Normal>&nbsp;</p>

<p class=Normal>Os discursos Budistas mais antigos muitas vezes se referem à oposição mútua entre dois pontos de vista. Um é a visão de permanência ou eternalismo (<i>sassatavada</i>). Outro é a visão de aniquilação (<i>ucchedavada</i>). O primeiro é por vezes referido como <i>bhava-ditthi</i>, a crença no ser, e este último como <i>vibhava-ditthi</i>, a crença no não-ser. Em geral o mundo tem a tendência de inclinar-se para um desses dois pontos de vista. Assim, dirigindo-se a Kaccayana, o Buda disse: “Kaccayana, em geral este mundo depende de uma dualidade, a noção da existência e a noção da não existência" (<a href="../sutta/SNXII.15.php">Kaccayanagotta Sutta</a>). O que nos interessa aqui é o fato de que é contra esses dois pontos de vista que as polêmicas Budistas são continuamente dirigidas. Além disso, todas as doutrinas fundamentais do Budismo original são apresentadas de tal forma que se desdobram, ou seguem numa seqüência lógica, com a sustentada crítica de <i>sassatavada e ucchedavada</i>. Esse contexto particular, é por vezes explicito, e em outros momentos é um pressuposto implícito. Portanto, é no âmbito da crítica Budista de <i>sassatavada e ucchedavada</i> que as doutrinas Budistas parecem assumir a sua importância. Pois é através da demolição dessas duas visões do mundo, que o Budismo procura construir a sua própria visão do mundo. A conclusão é que foi como uma resposta crítica à oposição mútua entre esses dois pontos de vista que o Budismo surgiu como uma nova fé em meio a muitas outras religiões.</p>

<p class=Normal>Isso deve ficar claro se examinarmos brevemente o meio religioso e intelectual em que o Budismo se originou. Na verdade, o clima predominante na época está muito bem refletido nos próprios discursos Budistas. O <a href="../sutta/DN1.php">primeiro <i>sutta</i></a> do primeiro <i>nikaya</i> do <i>Tipitaka</i>  começa com uma enumeração, e uma refutação sob o ponto de vista Budista, de 62 outros pontos de vista. Este e muitos outros <i>suttas</i> nos primeiros quatro <i>nikayas</i> mostram que prevalecia uma grande variedade de especulações mutuamente exclusivas sobre a natureza e o destino do homem e seu lugar no cosmos. Apesar da grande variedade de idéias, podemos classificá-las em três grupos principais. O primeiro inclui todas as religiões existentes na época, o segundo compreende as teorias materialistas que surgiram em direta oposição às religiões, e o terceiro consistia de todas as formas de ceticismo que surgiram como uma reação contra ambos.</p>

<p class=Normal>Entre as muitas religiões da época, algumas foram um desenvolvimento linear do pensamento Védico, enquanto outras parecem ter surgido de forma isolada ou em oposição a esse pensamento. No primeiro caso, a tendência era mais para o teísmo, monismo e ortodoxia; no segundo caso, foi mais na direção do não-teísmo, pluralismo e heterodoxia. Entre os dois grupos houve uma variedade de ensinamentos religiosos que estavam baseados em fundamentos epistemológicos como a autoridade das escrituras, a revelação, a onisciência do professor, o conhecimento adquirido através da percepção extra-sensorial, e argumentos baseados no puro raciocínio. Embora representassem um amplo espectro de pontos de vista e práticas religiosas, todos parecem ter subscrito à crença em uma alma ou uma identidade. Esta crença comum, embora tivesse muitas variações, é representada nos discursos Budistas com uma declaração geral: <i>jiva</i> ou alma é uma coisa e o corpo outra. Essa distinção parece enfatizar o fato de que enquanto a alma é algo permanente, o corpo é algo perecível. Esta distinção também ocorre entre o corpo físico e o eu metafísico. Parece ter havido um acordo geral entre todas as religiões que uma vez que essa entidade é algo imutável, ela sobrevive à morte, e é nessa entidade que a verdadeira essência do homem pode ser encontrada. Este ponto de vista religioso ou espiritual da personalidade humana é a teoria do eu metafísico. Foi essa crença em uma substância espiritual permanente dentro do homem que veio a ser representada nos <i>suttas</i> em Pali como <i>sassatavada</i>. Assim, do ponto de vista Budista, todas as religiões da época, que subscreviam uma entidade espiritual eterna eram apenas diferentes tipos de <i>sassatavada</i>.</p>

<p class=Normal>A tradição materialista que surgiu em oposição direta à religião também parece ter tido mais do que uma escola de pensamento. A sua posição no terreno epistemológico foi que a percepção sensorial seria o único meio válido de conhecimento. Portanto, foi questionada a validade das teorias teológicas e metafísicas que não têm origem no âmbito da experiência dos sentidos. Isso explica porque a tradição materialista rejeitou a versão religiosa do <i>atmavada</i>, a crença em um eu metafísico, e lhe deu uma nova interpretação. Essa nova interpretação é expressa nos <i>suttas</i> em Pali com a frase: o eu é o mesmo que o corpo. Isto é um grande contraste com a visão religiosa que enfatizava a dualidade, em vez da identidade. A linha de argumentação que parece ter levado a essa conclusão pode ser expressa da seguinte maneira: não há uma entidade "eu" que possa ser observada separada do corpo, e uma vez que apenas o observável existe, essa entidade "eu" deve ser idêntica ao corpo físico. Portanto, para o materialismo, essa entidade é um produto dos quatro elementos primários da matéria. Essa visão materialista da personalidade humana é a teoria do eu físico. Como o materialismo identifica o eu com o corpo físico, segue necessariamente, que no momento da morte, com a dissolução do corpo, o eu também é aniquilado, sem qualquer perspectiva de existência pós-morte. Diante dessa conclusão inevitável da visão materialista da vida, esta veio a ser representada nos textos Budistas como <i>ucchedavada</i> (aniquilação).</p>

<p class=Normal>Há uma crença geral entre alguns estudiosos modernos que o materialismo (<i>ucchedavada</i>) completamente rejeita o que é chamado <i>atmavada</i> ou a crença em uma alma ou eu. De um modo geral isso pode ser verdade, mas do ponto de vista Budista, isso não é válido. De acordo com o entendimento Budista de <i>atmavada</i>, qualquer tipo de coisa, seja material, mental ou espiritual, se for tomado com um objeto de auto-identificação, pode se tornar um <i>atman</i>. Este processo de auto-identificação é dito se manifestar de três formas: isso é meu (<i>etam mama</i>), isso sou eu (<i>esoham asmi</i>), e isso é o meu eu (<i>eso me atta</i>). Visto que o materialismo considera o corpo como sendo o eu, um objeto de auto-identificação, isso também é uma variedade de <i>atmavada</i>. Uma objeção que pode ser levantada aqui é que aquilo que os materialistas identificam como o eu não é uma entidade metafísica, mas o corpo físico perecível. No entanto, no contexto dos ensinamentos Budistas o que importa não é a permanência ou impermanência do objeto de auto-identificação, mas o próprio fato da auto-identificação. Assim os Budistas visualizam tanto <i>sassatavada</i> como <i>ucchedavada</i> como duas variedades de <i>atmavada</i>.</p>

<p class=Normal>Visto que <i>sassatavada</i> enfatiza a dualidade entre a alma e o corpo, a sua teoria da emancipação do homem está baseada nessa noção de dualidade. Entre a alma e o corpo, é a alma que está em cativeiro. Por isso, se algo deve ser salvo, tem que ser a alma. O que impede a sua jornada para cima é a atração gravitacional do corpo, isto é, a gratificação da sensualidade. Assim, a libertação da alma, a sua perpetuação em um estado de bem-aventurança eterna, exige a mortificação da carne. Isto é o que veio a ser representado nos textos Budistas como <i>attakilamathanuyoga</i> (auto-mortificação). É muito provável que durante a época do Buda tenha sido essa crença que levou a uma série de práticas ascéticas. Um exemplo foi o Jainismo, que defendia rigorosas austeridades para libertar a alma.</p>

<p class=Normal>Por outro lado para <i>ucchedavada</i> (materialismo) o homem "é um puro produto da terra" aguardando a sua aniquilação no momento da morte. Portanto, o seu objetivo nesta vida temporária não pode ser a rejeição dos prazeres sensuais na busca de um ideal espiritual mais elevado. Se for para buscar algo, deveria ser exatamente o oposto. Isto é o que veio a ser descrito nos textos Budistas como <i>kamasukhallikanuyoga</i> (gratificação sensual). Por conseguinte, a auto mortificação e a gratificação sensual representam respectivamente os aspectos práticos das duas teorias de <i>sasssatavada e ucchedavada</i>.</p>

<p class=Normal>É muito provável que tenha sido essa polarização do pensamento intelectual em <i>sasssatavada e ucchedavada</i>, com um número de seitas e sub-seitas dentro de cada tradição, que abriu o caminho para o surgimento do ceticismo. É claro ser verdade, como observado por KN Jayatilake, que houve indícios céticos e tendências agnósticas mesmo no pensamento indiano pré-Budista. No entanto, como ele também observa, o real "ímpeto e a ocasião para o surgimento do ceticismo parece ter sido fornecido pela presença de diversas, conflitantes e irreconciliáveis teorias referentes a convicções morais, religiosas e metafísicas". No entanto, no contexto indiano, o ceticismo não significa necessariamente a completa dissociação de qualquer ideal de salvação. Pois há evidências que sugerem que alguns adotaram o ceticismo com base em que o conhecimento não somente seria impossível, mas também um perigo para o desenvolvimento moral e da salvação.</p>

<p class=Normal>A polarização do pensamento religioso e intelectual em <i>sassatavada e ucchedavada</i> pavimentou o caminho para o nascimento do ceticismo, e parece muito provável que essa mesma circunstância também levou ao surgimento do Budismo. Esta conclusão é, de fato, sugerida pelo <a href="../sutta/SNLVI.11.php">primeiro discurso</a> do Buda. É com <i>sassatavada e ucchedavada</i> como pano de fundo que o Buda estabelece o seu recém-descoberto caminho para a emancipação, o <a href="../caminho_liberdade/dukkha_caminho.php">Nobre Caminho Óctuplo</a>. O próprio Buda chama o caminho de <i>majjhima patipada</i> (caminho do Meio), porque evita os dois extremos da entrega aos prazeres dos sentidos e da auto-mortificação. Evitar esses dois extremos também significa evitar as duas teorias que sustentam a sua origem, ou seja, <i>sassatavada e ucchedavada</i>, ou seja, as teorias física e metafísica sobre a natureza da personalidade humana. Assim, o uso das duas palavras Caminho do Meio põe em foco a formação religiosa e intelectual contra a qual o Budismo se originou. Que o Caminho do Meio não é um compromisso entre os dois extremos ou uma mistura deles é indicado por sua definição no mesmo discurso como <i>ubho ante anupagamma</i> (evitando os dois extremos). Isso mostra que é chamado de Caminho do Meio, porque transcende a oposição mútua entre os dois extremos.</p>

<p class=Normal>Na verdade, a própria vida do Buda delineia o conflito perene entre <i>sassatavada e ucchedavada</i> e sua transcendência pelo Caminho do Meio. A vida como um príncipe exemplifica um extremo; sua vida como um asceta praticando austeridades severas exemplifica o outro. E a sua realização da iluminação, abandonando os dois extremos mostra a eficácia do Caminho do Meio para a libertação de todo sofrimento.</p>

<p class=Normal>A crítica Budista das idéias ou pontos de vista, pode-se notar aqui, não se limita aos argumentos baseados na lógica, epistemologia e ontologia, mas também leva em consideração a motivação psicológica, isto é, as disposições mentais que servem como seus fatores causais. A teoria por trás disso é que os nossos desejos e expectativas têm um impacto sobre aquilo no que tendemos a acreditar. De acordo com o diagnóstico Budista da "psicologia" de <i>sassatavada (= bhava-ditthi)</i> e <i>ucchedavada (= vibhava-ditthi)</i>, o primeiro é devido ao desejo de ser/existir (<i>bhava-tanha</i>), o desejo de perpetuar a individualidade, e o último é devido ao desejo de não-ser/existir (<i>vibhava-tanha</i>), o desejo de ser completamente aniquilado na morte. Do ponto de vista Budista o raciocínio que justifica essa idéia pode ser conjecturado da seguinte forma: visto que <i>ucchedavada</i> rejeita a sobrevivência, tende a incentivar o homem a levar uma vida sem ser sobrecarregado por um senso de responsabilidade moral ou atormentado por inibições morais. Por conseguinte, abomina qualquer perspectiva de existência após a morte, uma vez que isso implica a possibilidade de retribuição moral. É essa resistência psicológica por parte de quem acredita em <i>ucchedavada</i> que leva ao desejo de aniquilação com a morte. Assim, o conflito mútuo entre <i>sassatavada e ucchedavada</i> representa não só o conflito perene entre o espiritual e as teorias materialistas da existência, mas também a oscilação da mente humana entre dois desejos profundamente arraigados.</p>

<p class=Normal>Pelo que temos observado até agora, duas coisas devem estar claras. A primeira é que <i>sassatavada</i> é o termo Budista para todas as outras religiões, exceto o Budismo, que eram correntes na época de Buda. A segunda é que <i>ucchedavada</i> é o termo Budista para todas as formas de materialismo que rejeitam todas as religiões, incluindo o Budismo. Assim, a crítica Budista de <i>sassatavada e ucchedavada</i> identifica a posição do Budismo em relação a outras visões de mundo contemporâneas.</p>

<p class=Normal>Também deve ser mencionado aqui que, apesar do Budismo rejeitar tanto <i>sassatavada</i> como <i>ucchedavada</i>, assim o faz depois de uma avaliação crítica. De acordo com essa avaliação, o Buda foi mais simpático com relação a <i>sassatavada</i> e mais crítico de <i>ucchedavada</i>. Isso também fica claro no primeiro discurso do Buda, onde ele se refere aos dois extremos da entrega aos prazeres dos sentidos e da auto-mortificação. Três dos termos usados para criticar o primeiro, que representa <i>ucchedavada</i>, são <i>hina</i> (inferior), <i>gama</i> (rústico ou vulgar) e <i>pothujjanika</i> (mundano). No entanto, estes três termos estão conspicuamente ausentes na avaliação do Buda da auto-mortificação, que representa <i>sassatavada</i>. A implicação parece ser que, embora <i>sassatavada</i> não leve à realização do ideal de emancipação, no entanto, não leva ao colapso da vida moral, não subverte a fundação moral da sociedade humana. Visto que reconhece uma fonte espiritual no homem, também reconhece distinções morais. Na verdade, de acordo com a avaliação do Budismo, todas as religiões são formas diferentes de <i>kammavada</i>, porque todas defendem a supremacia de uma vida moral. Por outro lado, <i>ucchedavada</i>, que representa a teoria materialista, incentiva um padrão de vida que toma a gratificação da sensualidade como objetivo final na vida. Assume como certo que a presente existência do homem é inteiramente devida a circunstâncias fortuitas e, portanto, ele não é moralmente responsável pelo que faz durante a sua estada temporária neste mundo.</p>

<p class=Normal>Observamos anteriormente que é com base no <a href="../caminho_liberdade/dukkha_caminho.php">Nobre Caminho Óctuplo</a> que o Budismo transcende a oposição mútua entre a entrega aos prazeres dos sentidos e a auto-mortificação. Então, qual a base para que o Budismo transcenda a oposição mútua entre <i>sassatavada e ucchedavada</i>? A resposta é fornecida pelo <a href="../sutta/SNXII.15.php">Kaccayanagotta Sutta</a>, onde o Buda diz o seguinte:</p>

<p class=Normal style='margin-left:.75in'> “Kaccayana, em geral este mundo depende de uma dualidade, a noção da existência e a noção da não existência. Mas para aquele que vê com correta sabedoria a origem do mundo, tal como na verdade ela ocorre, a noção da ‘não existência’ com relação ao mundo não lhe ocorrerá. Aquele que vê com correta sabedoria a cessação do mundo, tal como na verdade ela ocorre, a noção da ‘existência’ com relação ao mundo não lhe ocorrerá. ’Tudo existe’: Kaccayana, esse é um extremo. ‘Tudo não existe’: esse é o outro extremo. Evitando esses dois extremos, o Tathagata ensina o Dhamma pelo meio."</p>

<p class=Normal>É claro que as palavras "o Dhamma pelo meio" são uma referência à doutrina Budista da <a href="../origem_dependente.php">origem dependente</a>  (<i>paticcasamuppada</i>) não somente com base no contexto, mas também daquilo que vem a seguir no discurso. Pois na sequência imediatamente o Buda se refere especificamente à origem dependente, o que implica que é através dessa doutrina particular que o Budismo evita tanto <i>sassatavada</i> como <i>ucchedavada</i>. Assim, será visto que, tal como o Nobre Caminho Óctuplo é chamado de Caminho do Meio, porque evita os dois extremos da gratificação sensual e da auto-mortificação, a doutrina da origem dependente é chamada a Doutrina do Meio, porque evita da mesma forma esse referencial teórico.</p>

<p class=Normal>A posição central atribuída a essa doutrina particular pode ser confirmada pela declaração do Buda que aquele que vê a origem dependente vê o Dhamma (<i>Yo paticcasamuppadam passati so dhammam passati</i>). Essa afirmação tem sido muitas vezes entendida como uma referência à conhecida fórmula causal de doze elos. No entanto, é muito provável que a referência aqui seja ao princípio da causalidade, que é o fato da origem dependente e não a sua aplicação. O princípio da causalidade, tal como indicado nos <i>suttas</i> em pali, é o seguinte: 'sempre que A estiver presente, B estará presente (<i>imasmim sati idam hoti</i>); sempre que A estiver ausente, B estará ausente (<i>imasmim asati idam na hoti</i>)'. Portanto, 'do surgimento de A, B surge (<i>imass'uppada idam uppajjati</i>), à partir da cessação de A, B cessa (<i>imassa nirodha idam nirujjhati</i>)'. Esse princípio deve ser distinguido de sua aplicação, visto que tem muitas aplicações. Na verdade, é com base neste princípio que o Budismo procura explicar todas as suas doutrinas fundamentais, tais como a análise da mente e a teoria da percepção, <i>karma</i> e a ordem moral, e a natureza da individualidade empírica e a sua dimensão <i>samsárica</i>. Isso explica porque, como mostra a citação acima, a visão do princípio da origem dependente é dito constituir a visão do próprio coração do Dhamma. Dito de outra forma, isso significa ser esse o fundamento da visão Budista do mundo, e é através dessa doutrina que o Budismo transcende as outras duas visões do mundo representadas por <i>sassatavada e ucchedavada</i>.</p>

<p class=Normal>O Budismo rejeita <i>sassatavada</i>, significando que não há uma identidade no homem que seja impermeável à mudança. Isso também pode ser interpretado como a negação de qualquer tipo de substância espiritual no homem que se refere a algum tipo de realidade transcendental servindo como fundamento último da existência. O Budismo rejeita <i>ucchedavada</i>, significando que a personalidade humana não é um produto puro da matéria, mas é um processo ininterrupto e interconectado entre os fenômenos psico-físicos que não termina com a morte. Embora o Budismo não concorde completamente com <i>sassatavada</i>, a sobrevida (<i>punabbhava</i>) e a responsabilidade moral (<i>kammavada</i>) não são negadas.</p>

<p class=Normal style='margin-left:.75in'> "Aquilo que surge é apenas o sofrimento surgindo, aquilo que cessa é apenas o sofrimento cessando." (<a href="../sutta/SNXII.15.php">SN XII.15</a>)</p>

 <p class=Normal style='margin-left:.75in'>"Anuradha, tanto antes, como agora, eu declaro somente o sofrimento e a cessação do sofrimento." (<a href="../sutta/SNXXII.86.php">SN XXII.86</a>)</p>

  <p class=Normal style='margin-left:.75in'>"Da mesma forma como o oceano tem um único sabor – aquele do sal – assim também, esta Doutrina e Disciplina tem um único sabor: aquele da libertação." (<a href="../sutta/UdV5.php"> Ud V.5</a>)</p>

<p class=Normal>Essas três citações dos discursos do Buda mostram o que o Budismo é, e o que não é. O Budismo está interessado, não principalmente, como alguns estão inclinados a acreditar, mas totalmente com a situação existencialista do homem, que de acordo com o Budismo é a questão do sofrimento. Se o Budismo é para ser entendido nesse contexto, segue-se que todos os ensinamentos Budistas - se eles se relacionam com a ontologia, epistemologia, psicologia e ética - são, em última análise relacionados com a questão do sofrimento e a sua solução final. É sobre esse tema que todos os ensinamentos Budistas convergem e é em relação a isso que eles assumem o seu significado. A doutrina Budista da <a href="../origem_dependente.php">origem dependente</a>, que o próprio Buda quer que consideremos como o coração do Dhamma, representa na verdade, quando é compreendida em ambos aspectos progressivos e regressivos, como uma declaração da origem e cessação do sofrimento. O segundo aspecto, que explica a cessação do sofrimento, é muitas vezes esquecido nos escritos modernos o que resulta na visão equivocada de que o ensinamento Budista sobre a causalidade está preocupado apenas com a origem do sofrimento.</p>

<p class=Normal>Que todos os ensinamentos Budistas convergem para o problema do sofrimento e sua solução também é mostrado pela referência nos <i>suttas</i> em pali a dois tipos de ensinamentos. O primeiro é chamado <i>anupubbi-katha</i> ou o <a href="../caminho_liberdade/dharma.php">ensinamento gradual</a>. Ensinamentos sobre a generosidade (<i>dana</i>), sobre a virtude (<i>sila</i>), sobre o paraíso como recompensa por uma vida virtuosa, sobre as desvantagens, o perigo e a natureza contaminadora dos prazeres sensuais e as vantagens da renúncia - isso é o que constitui o 'ensinamento gradual'. É esse aspecto que o Budismo parece ter compartilhado com todas as outras religiões da época, como diferentes tipos de <i>kammavada</i> ou seja, que no geral defendem a vida moral. O segundo tipo de ensinamento é <i>sumukkamsika-desana</i> ou os 'discursos elevados', que consistem no diagnóstico Budista da condição humana e a sua solução. Se o primeiro é chamado de 'ensinamento gradual', isso pode ser entendido de duas maneiras. Uma delas é que gradualmente se prepara a base necessária para a transmissão do 'discurso elevado' . A outra é que também gradualmente se prepara a mente do ouvinte como um receptáculo adequado para a compreensão adequada. Isto mostra claramente que o 'discurso elevado', que se refere ao fato do sofrimento e sua solução, é o ensinamento mais proeminente e todos os outros ensinamentos servem apenas como prelúdio. Se o Buda emprega o 'ensinamento gradual', não é pelo ensinamento em si, mas com o único propósito de preparar o terreno para proferir a doutrina caracteristicamente Budista.</p>

<p class=Normal>O Budismo apresenta sua doutrina sobre o problema do sofrimento e a sua solução através de quatro proposições: existe sofrimento (<i>dukkha</i>), há uma causa para esse sofrimento, há a cessação do sofrimento mediante a remoção da causa do sofrimento, há um caminho que leva à eliminação da causa do sofrimento que resulta na cessação do sofrimento. São essas quatro proposições que o Buda introduziu como as <a href="../caminho_liberdade/quatro_nobres_verdades.php">Quatro Nobres Verdades</a>.</p>

<p class=Normal>É bastante óbvio que a formulação das Nobres Verdades não resta sobre uma teoria de graduações da verdade. Pois o que é colocado em foco não é a dicotomia entre dois tipos de verdade correspondentes a dois níveis de realidade, como é o caso da teoria de duas verdades que veio a ser desenvolvida nas escolas de pensamento Budista. O que é posto em foco, em vez disso, é a seqüência lógica entre quatro fatos. Portanto, estes não se prestam a ser interpretados de forma hierárquica. Se a primeira verdade se refere à presente situação do homem (patológica), a segunda procura explicar a sua origem (diagnóstico), a terceira refere-se à eliminação completa do sofrimento (ideal), a quarta mostra o caminho para a sua realização (prescritivo). Sem ignorar o fato de que as quatro verdades em combinação implicam dois níveis de realidade, a dimensão <i>samsárica</i> da individualidade empírica e a sua dimensão <i>nibbanica</i> quando é dado um fim à primeira dimensão. No entanto, essa distinção entre dois níveis de experiência (= realidade) de forma alguma dá às Quatro Nobres Verdades uma distinção qualitativa como quatro declarações da verdade. Tomadas como quatro proposições, elas são co-ordenadas. Esta parece ser a razão pela qual todas são apresentadas como Nobres Verdades.</p>

<p class=Normal>Devido à seqüência lógica das Quatro Nobres Verdades, o significado de cada uma não pode ser entendido em um contexto onde as outras três são excluídas. Cada uma assume importância em relação às outras três. Se a verdade do sofrimento for vista de forma isolada do resto, tal entendimento levará necessariamente à conclusão de que o Budismo defende uma visão pessimista da vida. Um equívoco desse tipo pode ser facilmente removido se a verdade for entendida no seu contexto próprio, ou seja, em relação às outras três verdades. Mesmo <i>nibbana</i>, que é o objetivo final do Budismo e que corresponde à terceira Nobre Verdade, assume a sua importância no contexto das outras três Nobres Verdades. Sua relação e inter-conexão mútua são tais que não seria incorreto dizer que elas não são quatro proposições diferentes  mas sim quatro aspectos de uma única e mesma proposição. Na verdade, nos próprios discursos Budistas é dito que  'quando a primeira nobre verdade é compreendida, a segunda está implícita, quando a segunda é compreendida, a terceira está implícita, quando a terceira é compreendida, a quarta está implícita'. Tal como observado por Arvind Sharma, 'as Quatro Nobres Verdades constituem uma série progressiva, cada uma conduzindo à próxima e cada uma iluminando a próxima'.</p>

<p class=Normal>A seqüência lógica exibida pelas Quatro Nobres Verdades também é levada em consideração quando se tornam a base para a prática da vida religiosa. Por conseguinte, é notado que o fato do sofrimento deve ser completamente compreendido (<i>parinneyya</i>), a causa do sofrimento deve ser removida (<i>pahatabba</i>), a cessação do sofrimento deve ser realizada (<i>sacchikatabba</i>), e o caminho que leva à cessação do sofrimento deve ser desenvolvido (<i>bhavetabba</i>). Se a segunda e a quarta Nobre Verdade forem tomadas como dois aspectos relacionados com a prática, então aqui temos as três dimensões principais do Budismo como uma teoria e prática, ou seja, a compreensão, a prática, e a realização. É sob esses três aspectos que todos os ensinamentos Budistas relativos ao problema do sofrimento e da sua solução final são apresentados.</p>

<p class=Normal>Igual a muitos outros ensinamentos Budistas, o ensinamento sobre o sofrimento também é apresentado no contexto de teorias semelhantes da época. Menção é feita nos <i>suttas</i> em pali sobre quatro teorias que explicam o sofrimento humano. De acordo com a primeira, o sofrimento é auto-provocado (<i>sayamkata</i>). Essa idéia está baseada no entendimento que há uma entidade que persiste, que age e sofre as conseqüências. A segunda baseia-se na teoria da causalidade externa, segundo a qual o homem sofre devido a uma entidade externa (<i>paramkata</i>), como um Deus criador, ou destino, ou natureza. De acordo com a terceira o sofrimento é tanto auto-provocado como causado por uma entidade externa (<i>ca paramkatam sayamkatam</i>). É uma tentativa de combinar as duas primeiras teorias. A quarta rejeita todas as três teorias mencionadas acima e procura explicar o sofrimento do homem como acontecendo por acaso, ou seja, devido a circunstâncias fortuitas (<i>adhiccasamuppanna</i>).</p>

<p class=Normal>O Budismo rejeita todas essas quatro teorias e explica o sofrimento com base na <a href="../origem_dependente.php">origem dependente</a>. Esse é o significado da fórmula causal de doze elos, em que cada elo sucessivo é dito resultar do que precede imediatamente. O que isto significa é que as causas do sofrimento são identificáveis sem referência a um princípio externo e sem postular uma entidade que persiste durante todo o ciclo de existência <i>samsárico</i> e também sem subscrever a idéia de que o sofrimento acontece por acaso.</p>

<p class=Normal>Isso não significa que a fórmula causal Budista explica apenas a origem do sofrimento. Ela também explica a sua cessação. É só na sua ordem progressiva que a origem do sofrimento é explicada. Esta baseia-se no princípio: sempre que A está presente, B (também) está presente. Portanto: a partir do surgimento de A, B surge. Na ordem regressiva, a fórmula causal mostra como o sofrimento cessa. Esta baseia-se no princípio: sempre que A está ausente, B (também) está ausente. Portanto: a partir da cessação de A, B (também) cessa. O que isto significa é que cada enunciado referente ao surgimento do sofrimento é sempre complementado por outro enunciado que explica como o sofrimento chega ao fim, para ser mais preciso, como pode ser dado um fim.</p>

<p class=Normal>A causalidade do sofrimento também mostra que, embora o Budismo reconheça a dimensão <i>samsárica</i> da individualidade empírica, as causas do sofrimento não são traçadas a nenhuma realidade transcendental.</p>

<p class=Normal>Na obra <i>Spokes of the Wheel</i>, Arvind Sharma levanta uma questão muito pertinente: Quando o Budismo fala em sofrimento, isso significa 1) há sofrimento na vida ou 2) que a vida em si é sofrimento. A sua resposta é que o ensinamento Budista parece alternar entre estes dois entendimentos. Deve ficar claro se essa resposta é justificável ao examinarmos como o fato do sofrimento é definido nos textos Budistas. Na obra <i>Religions of Man</i>, Huston Smith identifica seis ocasiões particulares nas quais o sofrimento é reconhecido no Budismo. Elas são: 1) o trauma do nascimento, 2) a patologia da doença, 3) a morbidade da decrepitude, 4) a fobia da morte, 5) a separação do que se ama. Antes de mencionar o que Huston Smith cita como a sexta ocasião, mais dois itens devem ser adicionados à lista acima. São eles: 6) a associação com o que é desagradável e 7) impedimento da vontade ou expectativa não cumprida. O último item que Smith cita como o sexto é um resumo abrangente do que é o sofrimento. Ou seja, 8) em resumo os cinco agregados do apego são sofrimento. Esta frase conclusiva na definição Budista do sofrimento é a mais importante, e poderia ser a mais controversa. Pois as sete ocasiões de sofrimento listadas antes da última, podem ser aceitas por quase todos como verdadeiras fontes de sofrimento.</p>

<p class=Normal>Como veremos no decorrer deste artigo, de acordo com o Budismo os cinco agregados do apego constituem a personalidade humana em sua dimensão <i>samsárica</i>. O próprio fato de serem descritos como sofrimento, claramente mostra que do ponto de vista Budista não é correto dizer que há sofrimento na vida. A resposta correta deve ser que a própria vida é sofrimento.</p>

<p class=Normal>Se a vida em si é sofrimento isso não é desmentido pela evidência empírica? Não existem prazeres da gratificação sensual, na excitação dos sentidos? O Budismo não questiona esse tipo de afirmação. "Se não houvesse nenhuma satisfação no mundo" - assim corre o argumento Budista - "seres não estariam aprisionados ao mundo". Os textos Budistas elogiam as bênçãos da boa vida em família. Menção é feita aos vários tipos de prazer e felicidade que podem ser obtidos através de meios justos ou injustos. Há felicidade ao ser elogiado, na obtenção de riqueza, e pelo nascimento num dos paraísos. A bem-aventurança da vida celestial é registrada em termos elogiosos. Como Arvind Sharma corretamente observa, o próprio fato de que o Budismo rejeita <i>kamasukhallikanuyoga</i> mostra que uma vida entregue à gratificação sensual não é algo impossível. Nem é sequer descrita como sofrimento, tal como ocorre com o seu oposto, <i>attakilamathanuyoga</i>, uma vida entregue à auto-mortificação. Se a gratificação sensual é rejeitada, não é por causa de sua impossibilidade, mas por causa de sua futilidade. Mais uma vez, o fato de <i>nibbana</i> ser definido como a felicidade suprema mostra também, implicitamente, que existem muitas outras formas de felicidade que são inferiores. O que tudo isto sugere é que o Budismo reconhece diferentes níveis de felicidade que culminam em <i>nibbana</i>. Por conseguinte, a própria felicidade passou a ser definida como aquela que tem <i>nibbana</i> como sua consumação (<i>nibbanam paramam sukham</i>).</p>

<p class=Normal>Na verdade, a definição Budista do sofrimento a que nos referimos anteriormente, também pode ser considerada como uma definição de felicidade. O fato de que o sofrimento é definido como a associação com o que é desagradável  mostra que, o contrário, a dissociação do que é desagradável é uma fonte de alegria. Em segundo lugar, se a dissociação do que é agradável é uma fonte de sofrimento, a sua condição oposta deve necessariamente ser uma fonte de felicidade. Em terceiro lugar, se o impedimento da vontade ou uma expectativa não cumprida é sofrimento, segue que o cumprimento da vontade, a realização dos nossos desejos e expectativas, são uma fonte segura de felicidade.</p>

<p class=Normal>Existe então uma contradição entre a afirmação de que a vida é sofrimento e o reconhecimento da realidade e da possibilidade de prazeres na vida? A resposta a esta pergunta deve ficar clara se regressarmos à definição Budista do sofrimento. Essa definição mostra que o Budismo reconhece três níveis de sofrimento. No nível mais elementar, o sofrimento aparece como a dor física e a opressão. Este é representado por ocasiões como <i>jati, jara e vyadhi</i>, que Huston Smith traduziu como o trauma do nascimento, a patologia da doença e a morbidade da decrepitude. A isso podem ser adicionadas experiências como a fome, sede, privação e acidentes. O próximo nível é o sofrimento como experiência psicológica. Associação com o que é desagradável ou dissociação do que é agradável, ou o impedimento da vontade ou uma expectativa não cumprida, poderiam ser citados como exemplos apropriados. No terceiro, ou no nível mais profundo, é a angústia ou a desarmonia, que parece ser a própria essência da vida humana. É este nível que o Budismo leva em consideração quando diz que os cinco agregados do apego são em si mesmos sofrimento. Será visto que as várias ocasiões de sofrimento que são identificadas na definição acima são enumeradas de modo a colocar em evidência esses três níveis de sofrimento.</p>

<p class=Normal>Aquilo que apresentamos acima como os dois primeiros níveis de sofrimento não excluem completamente as possibilidades de felicidade. Pois nos dois primeiros níveis apenas algumas ocasiões que levam ao sofrimento são identificadas e discriminadas. Portanto, se levarmos em consideração apenas os dois primeiros níveis, então devemos concluir que na vida há sofrimento e não que a vida é sofrimento. Mas quando chegamos ao terceiro nível, a definição é tão abrangente que justifica a conclusão de que a vida é sofrimento, e não que na vida há sofrimento.</p>

<p class=Normal>Agora, vamos considerar porque e como os cinco agregados do apego são ditos serem sofrimento. É um fato bem conhecido que segundo a análise Budista a individualidade empírica consiste de cinco agregados conhecidos como <a href="../glossario.php#khandha"><i>khandhas</i></a>. A personalidade humana portanto pode ser definida como a sua soma total. No entanto, a definição Budista de sofrimento não diz respeito aos cinco agregados (<i>pañcakkhandha</i>), mas aos cinco agregados do apego (<i>pañcaupadanakkhandha</i>), que são caracterizados como sofrimento. Isso mostra que, embora os cinco agregados em si mesmos não são sofrimento, eles podem ser uma fonte de sofrimento quando se tornam objetos de apego (<a href="../glossario.php#upadana"><i>upadana</i></a>). Portanto há uma distinção clara entre os cinco agregados, por um lado, e por outro lado os cinco agregados do apego. Estritamente falando, o que o Budismo chama de indivíduo não são os cinco agregados, mas os cinco agregados quando são apegados ou apropriados. Isso explica porque na definição Budista do sofrimento, a referência é feita aos <a href="../sutta/samyutta_nikaya.php#RXXII">agregados do apego</a> e não aos agregados em si. Portanto, o assim chamado indivíduo pode ser reduzido a um processo causalmente condicionado pelo apego. Sendo que é esse processo de apego que o Budismo descreve como sofrimento. Daí a conclusão Budista de que a vida, no seu nível mais fundamental ou essencial, é caracterizada pelo sofrimento.</p>

<p class=Normal>Essa explicação dá origem a duas perguntas. Uma delas é quem se apega aos cinco agregados? A outra é como e porque esse processo de apego leva ao sofrimento? A resposta à primeira pergunta é que, além do processo de apego, não há nenhum agente que executa o ato de apego. Isto pode parecer um pouco paradoxal, no entanto, é compreensível no contexto da doutrina Budista de <a href="../glossario.php#anatta"><i>anatta</i></a> e a da <a href="../origem_dependente.php">origem dependente</a>. O que tanto se procura mostrar é que o indivíduo é um processo condicionado, sem um agente dentro ou fora do processo. Esse processo de apego se manifesta de três maneiras: Isso é meu (<i>etam mama</i>), isso eu sou (<i>esoham asmi</i>), e isso é o meu eu (<i>eso me atta</i>). O primeiro é devido ao desejo (<a href="../glossario.php#tanha"><i>tanha</i></a>), o segundo é devido à presunção (<a href="../glossario.php#mana"><i>mana</i></a>), e o terceiro é devido à crença equivocada em uma identidade (<a href="../glossario.php#sakkaya_ditthi"><i>sakkaya-ditthi</i></a>). É através desse processo de auto-identificação tríplice que as idéias de "meu", "eu sou" e "meu eu" surgem. Se na dimensão <i>samsárica</i> existe uma coisa chamada individualidade, esta ocorre inteiramente devido à sobreposição dessas três idéias nos cinco agregados.</p>

<p class=Normal>Agora vamos responder a segunda questão: porque e como os agregados do apego são eles próprios chamados de sofrimento. Isso ocorre porque os cinco agregados que se tornam objeto de auto-identificação estão em um estado de constante mudança, em um estado de fluxo contínuo, sem uma essência duradoura, sem uma substância perene. A sua natureza é tal que eles não permanecem da maneira que queremos que permaneçam. Eles não estão sob o nosso controle. Como já mencionamos antes, este é um dos significados fundamentais de <a href="../glossario.php#anatta"><i>anatta</i></a>. Assim, identificando-nos com o que é impermanente, com o que não está sob nosso completo controle, passamos a sofrer. Isso explica porque o Budismo conecta o fato do sofrimento com o fato da impermanência (<i>yad aniccam tam dukkham</i>). Por isso, o próprio ato de auto-identificação é em si mesmo sofrimento. Quando o processo de auto-identificação é eliminado, o sofrimento, também chega ao fim. Essa é a diferença entre <i>samsara e nibbana</i>. <i>Samsara</i> continua enquanto o processo de auto-identificação persiste. Enquanto persistir haverá sofrimento. No momento em que o processo de auto-identificação pára, o processo <i>samsárico</i> também chega ao fim, juntamente com  todo o sofrimento que também chega ao fim. Esse é o significado do primeiro enunciado que citamos no início desta palestra: "Aquilo que surge é apenas o sofrimento surgindo, aquilo que cessa é apenas o sofrimento cessando."</p>

<p class=Normal>Nos textos Budistas três tipos de sofrimento são identificados os quais não correspondem exatamente aos três níveis de sofrimento que foram destacados até agora. O primeiro tipo é <i>dukkha-dukkha</i>. Esta forma duplicada do termo refere-se ao sofrimento como este geralmente é entendido, ou seja, a dor física, bem como sua experiência psicológica profunda como tristeza e angústia. Portanto esse primeiro tipo corresponde aos dois primeiros níveis da nossa classificação. O segundo tipo de sofrimento é <i>viparinama-dukkha</i>, ou seja, o sofrimento da mudança, que Edward Conze traduz como "o sofrimento da reversão". Isto se refere a situações em que, mesmo quando estamos felizes, o sofrimento está nos aguardando num segundo plano. Momentos de felicidade não são obtidos numa continuidade ininterrupta, mas têm a tendência de serem interrompidos por uma mudança de circunstâncias. É uma análise mais profunda do que o primeiro tipo. O terceiro tipo, que é chamado <i>sankhara-dukkha</i> corresponde exatamente ao terceiro nível de sofrimento que discutimos acima, ou seja, o sofrimento envolvido no apego aos cinco agregados.</p>

<p class=Normal>Comentando sobre a teoria do sofrimento como geralmente entendida pelas religiões indianas clássicas, BK Motilal coloca uma questão importante: se a 'tese do sofrimento é uma afirmação factual ou uma declaração de avaliação, trata-se de uma proposta ou uma exclamação (ou seja, uma exortação para agir), se é uma descrição de como as coisas são ou uma receita de como nós devemos considerá-las'. Na sua opinião, a referência acima como <i>dukkha-dukkha</i> é claramente uma proposição factual. Assim, por exemplo, o sofrimento experimentado devido ao impedimento da vontade é um sofrimento factual e experienciado. Por outro lado, ele observa que o terceiro nível de sofrimento que é <i>sankhara-dukkha</i> é claramente uma avaliação, uma avaliação em relação a <i>nibbana</i>. </p>

<p class=Normal>Embora tendemos a concordar com essa conclusão, também deve ser aceito que essa conclusão é feita sob o ponto de vista da existência <i>samsárica</i>. Por outro lado, a definição Budista de todo o sofrimento (não só <i>sankhara-dukkha</i>) é feita sob o ponto de vista de <i>nibbana</i>. É claro ser verdade que tais exemplos palpáveis de sofrimento como a fobia da morte podem ser compreendidos sem referência a <i>nibbana</i>. No entanto, o fato de que <i>nibbana</i> também é definido como "a libertação da morte" (<i>amata</i>) mostra que de acordo com a avaliação Budista, mesmo a fobia da morte como sofrimento tem significado em relação a <i>nibbana</i>. <i>Nibbana</i> é a própria negação de <i>samsara</i>. E uma vez que <i>nibbana</i> é definido como o mais alto nível de felicidade, sob esse ponto de vista, toda a experiência de <i>samsara</i> é sofrimento. Mesmo em termos gerais não deve ser incorreto dizer que toda apreciação do sofrimento envolve algum tipo de avaliação. Pois o sofrimento assume importância em relação ao seu contrário, que é a felicidade. O medo da morte deve ser entendido em relação ao desejo de viver. Se a associação com o desagradável é uma ocasião de sofrimento, é porque a dissociação do que é desagradável é uma fonte de felicidade. Portanto, é difícil entender por que apenas <i>sankhara-dukkha</i> deve ser apontada como uma instância de avaliação.</p>

<p class=Normal>De todo modo, o Budismo descreve o sofrimento como <i>tatha</i> (real e objetivo) , <i>avitatha</i> (não irreal e não não-objetivo) e <i>anannatha</i> (invariável). Estas três características também são aplicadas ao princípio da origem dependente (<i>paticcasamuppada</i>). O que parece ser enfatizado aqui é que, embora o sofrimento seja uma experiência subjetiva, este é apresentado como um fato objetivo, a fim de enfatizar a sua universalidade.</p>

<p class=Normal>Se o Budismo enfatiza a universalidade do sofrimento, isso pode ser entendido sob um outro ponto de vista, o ponto de vista da causa do sofrimento. A causa do sofrimento é o desejo egoísta, que se manifesta de várias formas. Daí a universalidade do sofrimento também significar a universalidade do desejo egocêntrico. Dizer que o homem sofre é o mesmo que dizer que o homem é motivado por desejos egocêntricos. As duas afirmações são mutuamente conversíveis, a primeira por meio do efeito e a segunda por meio da causa. Nos escritos modernos sobre o Budismo este fato, ou seja, o fator causador do sofrimento, é muitas vezes esquecido.</p>

<p class=Normal>A grande preocupação do Budismo com o problema do sofrimento pode, numa avaliação superficial, parecer ser uma obsessão excessiva com um problema infundado, especialmente ao considerá-lo no contexto das alegrias e prazeres da vida. O que não deve ser esquecido aqui é que se o Budismo se preocupa com o problema do sofrimento é porque está igualmente preocupado com a sua solução. Identificar todas as fontes e ocasiões de sofrimento visa assegurar que a alegria esteja fundamentada numa base segura e sólida. Assim, mesmo a experiência dos <a href="../glossario.php#jhana"><i>jhanas</i></a> e as delícias da existência celestial, que para todos os efeitos práticos podem ser descritas como uma instância suprema de felicidade, também são identificadas como sofrimento. Portanto, o ensinamento Budista sobre o sofrimento também pode ser entendido como o ensinamento Budista sobre a busca da felicidade.</p>

<p class=Normal>A atitude Budista em relação ao sofrimento é muito bem analisada por Alexandra David-Neel no livro <i>Buddhism, its Doctrines and its Methods</i>. Ela menciona quatro possíveis atitudes em relação ao sofrimento. A primeira, em face de todas as evidências, é a negação do sofrimento. Isto pode ser interpretado como otimismo ingênuo. A segunda é  'a resignação passiva, a aceitação do estado de coisas que se considera inevitáveis'. Isto pode ser interpretado como completo pessimismo. A terceira é a camuflagem do sofrimento com a ajuda de sofismas pomposos ou gratuitamente anexando-lhe tais virtudes e objetivos transcendentes que se pensa podem enobrecê-lo ou diminuir o seu amargor. Isto pode ser interpretado como a racionalização do sofrimento. A quarta é a 'luta contra o sofrimento, acompanhada pela fé na possibilidade de superá-lo.' Isto pode ser descrito como racional e a atitude mais inteligente em relação ao sofrimento. O Budismo adota esta quarta atitude em relação ao sofrimento. Isso também explica por que o Budismo não faz quaisquer tentativas de interpretar o sofrimento. Pois qualquer interpretação do sofrimento implica uma tentativa de racionalizá-lo. A racionalização do sofrimento, por sua vez, implica uma tentativa de 'esconder a sua amargura' baseado em motivos espirituais ou outros. Isso equivale ao escapismo em face do sofrimento, o que em outras palavras significa o adiamento da sua solução.</p>

<p class=Normal>Conseqüentemente o Budismo enfatiza a urgência da necessidade de uma solução para o problema de sofrimento. Portanto, a situação existencial do homem é comparada com uma pessoa que foi atingida por uma flecha envenenada. Esse símile chama a atenção não só para a presente situação, mas também para a urgência em resolvê-la. Também chama a atenção para duas outras coisas: ou seja, o que deve ser feito e o que não deve ser feito em tal situação. Em primeiro lugar, a pessoa não deve perder seu tempo formulando perguntas bobas sobre quem disparou a flecha, qual o seu nome, classe social, etc. Também não deve insistir que a flecha envenenada não deve ser removida até que ela saiba as respostas a essas perguntas. Levantar essas questões é a criação de um outro problema que não tem nenhuma relevância para o problema em questão, e ainda mais, o paciente morreria antes que pudesse obter respostas satisfatórias às suas perguntas.</p>

<p class=Normal>É com base nessa analogia que a atitude Budista para o problema do sofrimento e a solução de questões metafísicas deve ser entendida. Por isso, quando <a href="../sutta/MN63.php">Malunkyaputta</a> perguntou ao Buda se o mundo é eterno ou não é eterno, ou se o mundo é finito ou infinito, o Buda se recusou a responder. Malunkyaputta então decidiu deixar a <i>Sangha</i>. Depois, dirigindo-se a Malunkyaputta o Buda disse: 'Se existe a idéia "o mundo é finito," ... "o mundo é infinito" ... existindo ou não essas idéias, existe nascimento, existe envelhecimento, existe morte, existe tristeza, lamentação, dor, angústia e desespero, a destruição dos quais eu prescrevo aqui e agora.' Foi para ilustrar esse ponto que o Buda usou o símile da flecha envenenada. Se o Buda se recusou a responder a tais questões metafísicas era porque a sua solução - se existe solução ou não é uma outra questão - não tem relevância para a compreensão da presente situação ou para resolvê-la. Essas perguntas, como diz o Buda: 'não trazem beneficio, não pertencem aos fundamentos da vida santa, não conduzem ao desencantamento, ao desapego, à cessação, à paz, ao conhecimento direto, à iluminação, a <i>nibbana</i>.' O que é mais importante de ser notado aqui é que, imediatamente após dizer isso, o Buda passa a explicar as <a href="../caminho_liberdade/quatro_nobres_verdades.php">Quatro Nobres Verdades</a>, que é a formulação Budista do problema do sofrimento e a sua solução. É neste contexto que a segunda citação mencionada no início desta palestra torna-se significativa: </p>

<p class=Normal style='margin-left:.75in'>"Anuradha, tanto antes, como agora, eu declaro somente o sofrimento e a cessação do sofrimento."</p>





<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>

<!-- Counter/Statistics -->
<script language="JavaScript"
src="http://us.js2.yimg.com/us.js.yimg.com/lib/smb/js/hosting/cp/js_source/whv2_001.js">
</script>
<script language="javascript">geovisit();</script>
<noscript><img src="http://visit.webhosting.yahoo.com/visit.gif?time"
alt="setstats" border="0" width="1" height="1"></noscript>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-42601555-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>