<!-- DEFINE PARAMETROS -->
<?
DEFINE ('PAGINA',"vacuidade ");  // CAMINHO+NOME DO ARQUIVO SEM EXTENSAO
DEFINE('REVISAO'," 2 Junho 2007"); // DATA DA REVISAO
?>
<!--INCLUI TOPO-->
<?
include("../topo.inc"); // VERIFICAR SE O CAMINHO ESTÁ CERTO
?>

<!-- INICIO DO TEXTO -->

<p class=Tit1 align=center style='text-align:center'> A Integridade da Vacuidade  </Tit1>
<p class=Tit3 align=center style='text-align:center'> Por  </Tit3>
<p class=Tit2 align=center style='text-align:center'>Ajaan Thanissaro </Tit2>

<p class=Normal align=center style='text-align:center'><span lang=PT-BR style='font-size:
7.0pt;mso-ansi-language:PT-BR'><b> Somente para distribuição gratuita.</b><br>
<i>Este trabalho pode ser impresso para distribuição gratuita.<br>
Este trabalho pode ser re-formatado e distribuído para uso em computadores e redes de computadores<br>
contanto que nenhum custo seja cobrado pela distribuição ou uso.<br>
De outra forma todos os direitos estão reservados. </i> <o:p></o:p></span></p>

<p class=Normal>&nbsp;</p>

<hr size=2 width="100%" align=center>

<p class=Normal>&nbsp;</p>

<p class=Normal>Apesar da sutileza dos seus ensinamentos, o Buda tinha um teste simples para medir a sabedoria. Você é sábio, ele dizia, quando consegue fazer coisas que não gosta de fazer, mas que sabe irão resultar em felicidade, e de evitar fazer coisas que você gosta de fazer, mas que sabe irão resultar em dor e prejuízo. </p>

<p class=Normal>Ele deduziu esse padrão de sabedoria do seu insight sobre a radical importância da ação intencional em moldar a nossa experiência de felicidade e tristeza, prazer e dor. Dada a importância das ações que, no entanto, são com freqüência mal direcionadas, a sabedoria tem de ser tática, estratégica, ao fomentar ações que sejam realmente benéficas. Tem de ser mais astuta que as preferências míopes, para produzir uma felicidade duradoura. </p>

<p class=Normal>Porque o Buda observou todos os aspectos da experiência, do grosseiro ao sutil, em relação às ações intencionais e os seus resultados, o seu padrão tático para a sabedoria também se aplica a todos os níveis, da sabedoria simples da generosidade até a sabedoria da vacuidade e da perfeita iluminação. A sabedoria em todos os níveis é sábia, porque ela funciona. Ela influencia aquilo que você faz e a felicidade resultante. E para que funcione, ela requer integridade: a disposição para olhar com honestidade para os resultados das suas ações, admitir quando você tiver causado dano e mudar o seu modo de agir para não repetir o mesmo erro outra vez. </p>

<p class=Normal>O que impressiona em relação a esse padrão de sabedoria é a sua objetividade e praticidade. Isso pode ser uma surpresa, pois a maioria das pessoas não pensa na sabedoria Budista como bom senso e descomplicação. Ao invés, a frase “Sabedoria Budista” invoca ensinamentos mais abstratos e paradoxais que desafiam o bom senso – sendo a vacuidade o principal exemplo. A vacuidade, nos disseram, significa que nada possui existência inerente. Em outras palavras, num nível básico, as coisas não são aquilo que por convenção tomamos por “coisas.” Elas são processos que de forma nenhuma estão separadas de outros processos dos quais elas dependem. Essa é uma idéia filosófica sofisticada que fascina o filosofante, mas que não oferece um apoio muito claro para ajudá-lo a levantar mais cedo para meditar numa manhã fria e tampouco para convencê-lo a abandonar um vício destrutivo. </p> 

<p class=Normal>Por exemplo, se você é alcoólatra, não é porque você sente que o álcool tem algum tipo de existência inerente. É porque, de acordo com os seus cálculos, o prazer imediato derivado do álcool tem mais peso que o dano a longo prazo que ele causa na sua vida. Esse é um princípio geral: o apego a um vício não é um problema metafísico. Ele é um problema tático. Temos apego às coisas e às nossas ações, não devido ao que pensamos que elas sejam, mas devido ao que acreditamos que elas possam fazer pela nossa felicidade. Se prosseguirmos superestimando o prazer e subestimando a dor que elas causam, continuaremos apegados a elas independentemente do que, em última análise, acreditamos que elas sejam. </p>

<p class=Normal>Como o problema é tático, a solução tem de ser tática também. A cura para o vício e para o apego encontra-se na reeducação do seu pensamento e das suas intenções através do desenvolvimento da noção do poder das suas ações e da possível felicidade que você poderá alcançar. Isso significa aprender a ser mais honesto e sensível para com as suas ações e as suas conseqüências, e ao mesmo tempo permitir-se imaginar e dominar rotas alternativas para uma felicidade mais completa, com menos desvantagens. Idéias metafísicas podem algumas vezes participar da equação, mas elas, no máximo, desempenham um papel secundário. Muitas vezes são irrelevantes. Mesmo se você visse o álcool e o seu prazer como desprovidos de existência inerente, ainda assim você buscaria esse prazer enquanto o visse valendo mais que o dano causado. Algumas vezes, as idéias metafísicas da vacuidade podem na verdade ser prejudiciais. Se você começar a focar em como o dano causado pela bebida – e as pessoas prejudicadas pelo seu vício – são vazios de existência inerente, você poderá desenvolver uma justificativa racional para continuar a beber. Portanto, o ensinamento da vacuidade metafísica não parece que passaria no teste do próprio Buda para a sabedoria. </p> 

<p class=Normal>A ironia é que a idéia da vacuidade como ausência de existência inerente tem muito pouco a ver com aquilo que o próprio Buda falou sobre a vacuidade. Os seus ensinamentos sobre a vacuidade – tal qual relatado nos textos Budistas mais antigos, o Cânone em Pali – tratam diretamente das ações e dos seus resultados, com as questões do prazer e da dor. Para compreender e experimentar a vacuidade, conforme esses ensinamentos, não requer sofisticação filosófica, mas a integridade pessoal disposta a admitir as reais motivações que se encontram por detrás das suas ações e os reais benefícios e danos que elas causam. Por essas razões, essa versão da vacuidade é mais relevante no desenvolvimento do tipo de sabedoria que passaria no teste do Buda, baseado no bom senso, para medir o quão sábio você é. </p>

<p class=Normal>Os ensinamentos do Buda, sobre a vacuidade - apresentados em dois discursos mais longos e vários outros menores – definem-na de três modos distintos: como um método de meditação, como um atributo dos sentidos e dos seus objetos e como um estado de concentração. Embora essas formas de vacuidade difiram nas suas definições, em última instância elas convergem para o mesmo caminho da libertação do sofrimento. Para ver como isso acontece, precisaremos examinar os três significados da vacuidade um a um. Ao fazer isso, iremos descobrir que cada um aplica o teste de sabedoria do Buda, baseado no bom senso em relação às ações sutis da mente. Mas para compreender como esse teste se aplica nesse nível sutil, primeiro precisamos ver como ele se aplica a ações num nível mais óbvio. Nesse sentido, não há melhor introdução que o conselho do Buda para o seu filho Rahula, sobre como cultivar a sabedoria ao realizar as atividades rotineiras do dia a dia. </p>

<p class=Normal><b>Observando as Ações Diárias</b></p>

<p class=Normal>O Buda disse para o seu filho Rahula, que tinha sete anos na época, para usar os seus pensamentos, palavras e ações como se fossem um espelho. Em outras palavras, da mesma forma que você usa um espelho para verificar se o seu rosto está limpo, Rahula deveria usar as suas ações como um meio para descobrir se ainda havia algo impuro na sua mente. Antes de agir, ele deveria tentar antecipar os resultados da ação. Se ele visse que ela seria prejudicial para ele mesmo ou para os outros, ele não deveria dar seguimento à ação. Se ele não antecipasse nenhum dano, ele poderia seguir adiante com a ação. Se, enquanto estivesse praticando a ação, ele percebesse que ela estaria causando um dano inesperado, ele deveria parar o que estava fazendo. Se ele não visse nenhum dano, ele poderia seguir adiante com a ação. </p>

<p class=Normal>Se, depois de ter praticado a ação, ele visse algum dano que tivesse sido causado, ele deveria consultar algum companheiro na vida santa para entender melhor o que ele havia feito e como evitar fazer aquilo novamente e depois determinar-se a não mais repetir o mesmo erro. Em outras palavras, ele não deveria se sentir apreensivo ou envergonhado de revelar os seus erros para pessoas que ele respeitava, pois, se ele começasse a esconder deles os seus erros, em pouco tempo ele passaria a escondê-los de si mesmo. Se, por outro lado, ele não visse nenhum dano resultando da ação, ele deveria se alegrar com o seu progresso na prática e continuar com o seu treinamento. </p>

<p class=Normal>O nome correto para esse tipo de reflexão não é “auto-purificação.” É “purificação da ação.” Você desvia os julgamentos de bom e mau da sua noção de eu, onde eles podem atá-lo com a presunção e a culpa. Ao invés disso, você foca diretamente nas ações em si mesmas, onde os julgamentos permitirão que você aprenda com os seus erros e encontre uma alegria saudável naquilo que você fez corretamente. </p>

<p class=Normal>Continuando a refletir dessa forma, servirá vários propósitos. Primeiro e mais importante de tudo, obriga-o a ser honesto com relação às suas intenções e com relação aos efeitos das suas ações. A honestidade neste caso é um princípio simples: você não acrescenta nenhum tipo de racionalização a posteriori para encobrir aquilo que você na verdade fez e tampouco tenta subtrair da verdade através da recusa em aceitar os fatos. Porque você está empregando essa honestidade em áreas onde a reação normal é sentir-se envergonhado ou com medo da verdade, trata-se de  mais do que um simples registro dos fatos. Requer também integridade moral. É por isso que o Buda enfatizava a virtude como pré-condição para a sabedoria e declarou que o princípio de virtude mais elevado é o preceito contra a mentira. Se você não adquirir o hábito de admitir as verdades desconfortáveis, a verdade como um todo evadir-se-á. </p>

<p class=Normal>O segundo propósito dessa reflexão é enfatizar o poder das suas ações. Você vê que as suas ações representam a diferença entre o prazer e a dor. Terceiro, você exercita a prática de aprender com os seus erros sem sentir vergonha ou remorso. Quarto, você compreende que quanto mais honesto você for na avaliação das suas ações, mais poder você terá para mudar o seu modo de agir numa direção positiva. E por fim, você desenvolve boa vontade e compaixão, considerando que você decidirá agir apenas com base em intenções que não causem dano a ninguém e focar continuamente no desenvolvimento da habilidade de ser inofensivo como a sua principal prioridade. </p>

<p class=Normal>Todas essas lições são necessárias para desenvolver o tipo de sabedoria avaliadas no teste do Buda para a sabedoria; e, no fim das contas, elas estão diretamente relacionadas com o primeiro significado da vacuidade, como um método de meditação. Na verdade, esse tipo de vacuidade toma simplesmente as instruções que Rahula recebeu para observar as suas ações diárias e as amplia para a ação da percepção da mente. </p>

<p class=Normal><b>A Vacuidade como um Método de Meditação</b></p>

<p class=Normal>A vacuidade como um método de meditação é o mais básico dos três tipos de vacuidade. No contexto deste método, a vacuidade significa “vazio de perturbações” – ou para colocar isso em outras palavras, vazio de sofrimento. Você traz a mente para a concentração e depois examina esse estado de concentração para detectar a presença ou ausência de perturbações sutis, ou sofrimento, ainda presentes naquele estado. Ao encontrar uma perturbação, você a segue até a percepção – o rótulo mental ou ato de identificação – na qual a concentração está baseada. Então, você abandona aquela percepção por uma outra mais refinada, uma que conduza a um estado de concentração com menos perturbação presente. </p>

<p class=Normal>No discurso em que explica este significado de  vacuidade (<a href="../sutta/MN121.php">MN 121</a>), o Buda ilustra a sua explicação com um símile. Ele e Ananda estão num palácio abandonado que agora é um silencioso monastério. O Buda diz para Ananda observar e apreciar que o monastério está vazio das perturbações que continha quando era usado como palácio – as perturbações causadas pelo ouro e prata, elefantes e cavalos, assembléias de mulheres e homens. A única perturbação restante é aquela causada pela presença dos bhikkhus meditando em conjunto. </p>

<p class=Normal>Tomando esse símile, o Buda deu início à descrição da vacuidade como um método de meditação. (O símile é reforçado pelo fato de que a palavra em Pali para “monastério” ou “residência” – <i>vihara</i> – também significa “atitude” ou “método”). Ele descreve um bhikkhu meditando na floresta que está simplesmente notando para si mesmo que ele agora está na floresta. O bhikkhu permite que a sua mente se concentre e desfrute dessa percepção, “floresta.” Ele então retrocede mentalmente, observando e avaliando que esse modo de percepção está vazio das perturbações que acompanham as percepções da vida no vilarejo que ele deixou para trás. As únicas perturbações restantes são aquelas associadas à percepção, “floresta” – por exemplo, quaisquer reações emocionais em relação aos perigos que a floresta possa conter. Como referido pelo Buda, o bhikkhu vê com precisão quais perturbações não estão presentes nesse modo de percepção; quanto às perturbações que restam, ele as vê  com precisão, “Isto está presente.” Em outras palavras, ele não adiciona e não elimina nada do que ali está. Assim é como ele entra na vacuidade meditativa que é pura e não distorcida. </p> 

<p class=Normal>Depois, notando as perturbações presentes no ato de focar na “floresta,” o bhikkhu abandona essa percepção e a substitui por uma percepção mais refinada, uma com menos potencial de despertar perturbações. Ele escolhe o elemento terra, expelindo da sua mente todos os detalhes das colinas e ravinas da terra, simplesmente tomando nota da sua qualidade terral. Ele repete o processo aplicado na percepção da floresta – estabelecendo-se na percepção da “terra,” desfrutando plenamente dela e depois retrocedendo para observar que as perturbações associadas com a “floresta” desapareceram, enquanto que as únicas perturbações presentes são aquelas associadas à unicidade da mente baseada na percepção, “terra.” </p>

<p class=Normal>Ele depois repete o mesmo processo com percepções ainda mais refinadas, estabelecendo-se nos jhanas imateriais ou absorções meditativas: espaço infinito, consciência infinita, nada, nem percepção, nem não percepção, e a concentração desprovida de objeto. </p> 

<p class=Normal>Por fim, vendo que mesmo essa concentração desprovida de objeto é fabricada e fruto da vontade, ele abandona o seu desejo de continuar fabricando mentalmente alguma coisa. Desse modo ele é libertado das impurezas mentais – desejo sensual, ser/existir, idéias e ignorância – que poderiam fermentar num contínuo vir a ser. Ele observa que essa libertação ainda contém as perturbações associadas ao funcionamento das seis bases sensuais, mas que está vazia de todas as impurezas, de todo o potencial de mais sofrimento. Isto, conclui o Buda, é  a entrada na vacuidade pura e não distorcida, que é suprema e insuperável. É a vacuidade na qual ele mesmo permanece e que, durante todo o tempo, nunca foi nem nunca será superada. </p> 

<p class=Normal>Em cada ponto dessa descrição, a vacuidade significa uma coisa: vazio de perturbação ou sofrimento. O meditador é ensinado a observar a ausência de perturbação como uma realização positiva e de ver qualquer perturbação criada pela mente, não importando quão sutil ela seja, como um problema para ser solucionado. </p>

<p class=Normal>Quando você compreender a perturbação como uma forma sutil de dano, você verá as conexões entre esta descrição da vacuidade e as instruções do Buda para Rahula. Ao invés de tomar os seus estados meditativos como uma avaliação da sua identidade ou do seu valor próprio – por ter desenvolvido um eu que é mais puro, mais expansivo, mais em harmonia com o fundamento da existência – o bhikkhu encara aquilo simplesmente como ações e suas conseqüências. E os princípios que aqui se aplicam, no nível meditativo, são os mesmos que se aplicam aos conselhos do Buda para Rahula com relação à ação em geral. </p>

<p class=Normal>Aqui, a ação é a percepção que suporta o seu estado de concentração meditativa. Você se estabelece nesse estado ao repetir a ação de percepção continuamente até que esteja perfeitamente familiarizado com ela. Assim como Rahula descobriu as conseqüências das suas ações ao observar o dano óbvio causado para si mesmo e para os outros, aqui você descobre as conseqüências da concentração naquela percepção, ao ver quanta perturbação surge da ação mental. Ao perceber a perturbação, você pode mudar a sua ação mental, movendo a sua concentração para uma percepção mais refinada, até que por fim você pode parar por completo a fabricação de estados mentais. </p> 

<p class=Normal>No núcleo dessa prática meditativa encontram-se dois princípios importantes derivados das instruções para Rahula. O primeiro é a honestidade: a habilidade para se libertar do embelezamento ou negação que, sem adicionar nenhuma interpretação à perturbação presente no momento, tampouco tenta negar o que está ali presente. Uma parte integral dessa honestidade é a habilidade de ver as coisas simplesmente como ação e resultado, sem lhes adicionar a presunção “Eu sou.” </p>

<p class=Normal>O segundo princípio é a compaixão – o desejo de dar um fim ao sofrimento - considerando que você continuará tentando abandonar as causas do sofrimento e das perturbações sempre que você as encontrar. Os efeitos dessa compaixão se estendem não só até você, mas até os outros também. Quando você não se sobrecarrega com o sofrimento, é menos provável que você seja um fardo para os outros; você também estará em  melhor posição para ajudá-los a carregar os seus fardos quando for necessário. Dessa forma, os princípios de integridade e compaixão estão na base até mesmo das expressões mais sutis da sabedoria que conduz à libertação. </p> 

<p class=Normal>Esse processo de desenvolvimento do vazio das perturbações não é necessariamente isento de problemas e direto. Ele requer a força de vontade necessária para abrir mão de todos os apegos. Porque um passo essencial para conhecer a percepção meditativa como uma ação é aprender a se estabelecer nela, desfrutar dela – em outras palavras, apreciá-la por inteiro, até o extremo do apego. Esse é um dos papéis da tranqüilidade na meditação. Se você não aprender a desfrutar da meditação o suficiente para mantê-la com regularidade, você não se familiarizará com ela. Se você não tiver familiaridade, o insight dos seus efeitos não irá surgir. </p>

<p class=Normal>No entanto, a menos que você já tenha praticado usando as instruções para o Rahula, para superar os apegos mais grosseiros, então, mesmo que você experimente o insight das perturbações causadas pelo seu apego à concentração, faltará integridade ao seu insight. Como você não teve nenhuma prática em relação aos apegos mais óbvios, você não será capaz de se libertar dos apegos mais sutis de uma forma confiável. Você primeiro precisa desenvolver o hábito de observar as suas ações e as suas conseqüências, acreditando com firmeza, com base na experiência, no valor de abster-se do mal ainda que sutil. Só então você terá a habilidade necessária para desenvolver a vacuidade como um método de meditação de um modo puro e não distorcido, que irá conduzi-lo por todo o caminho até o objetivo almejado. </p> 

<p class=Normal><b>A Vacuidade como um Atributo dos Sentidos e dos seus Objetos</b></p>

<p class=Normal>A vacuidade como um atributo, quando usado como um ponto de partida para a prática, conduz a um processo similar mas por uma rota diferente. Enquanto a vacuidade, como um método de meditação, foca nas questões de perturbações e sofrimento, a vacuidade como um atributo foca nas questões de eu e não-eu. E enquanto a vacuidade, como um método de meditação, começa com a tranqüilidade, a vacuidade como um atributo começa com o insight. </p>

<p class=Normal>O Buda descreveu este tipo de vacuidade num discurso breve  (<a href="../sutta/SNXXXV.85.php">SN XXXV.85</a>). Novamente, Ananda é o interlocutor, abrindo o discurso com uma pergunta: De que modo o mundo está vazio? O Buda responde que cada um dos seis sentidos e os seus objetos estão vazios de um eu ou algo que pertença a um eu. </p>

<p class=Normal>O discurso não oferece explicações adicionais, mas discursos afins mostram que esse insight pode ser colocado em prática de duas formas. A primeira é refletir sobre o que o Buda falou sobre o “eu” e como as idéias de um eu podem ser compreendidas como formas de elaboração mental. A segunda, que discutiremos na seção seguinte, é desenvolver a percepção de que todas as coisas estão vazias de um eu como base para um estado de concentração refinada. No entanto, como veremos, ambas as abordagens acabam no final conduzindo de volta ao uso da primeira forma de vacuidade como um método de meditação para completar o caminho para a iluminação. </p> 

<p class=Normal>Quando falava sobre o “eu,” o Buda se recusava a dizer se este existe ou não, mas dava uma detalhada descrição de como a mente desenvolve a idéia de um eu como uma estratégia apoiada sobre o desejo. Na busca pela felicidade, nós repetidamente agimos de um modo que o Buda chamava de “fabricação de um eu” e “fabricação do meu” como formas de tentar exercer controle sobre o prazer e a dor. Como a fabricação de um eu e a fabricação de um meu são ações, elas se encaixam dentro do alcance das instruções do Buda para Rahula. Sempre que agirmos dessa maneira, deveremos verificar se isso conduz à aflição; se assim for, então deveremos abandoná-las. </p>

<p class=Normal>Essa é uma lição que, num nível mais óbvio, aprendemos quando ainda criança. Se você disser que é seu um doce que pertence à sua irmã, você irá se meter numa briga. Se ela for maior que você, melhor você não dizer que o doce é seu. À medida que crescemos, muito da nossa educação prática está situada no descobrimento de onde é benéfico criar um senso do “eu” em torno de algo e onde não é. </p>

<p class=Normal>Se você aprender a encarar a sua fabricação de um eu e fabricação do meu, sob a perspectiva das instruções para Rahula, você irá em grande parte refinar esse aspecto da sua educação e  ao mesmo tempo se verá forçado a ser mais honesto, sábio e compassivo, vendo onde um “eu” é um passivo e onde ele é um ativo. Num nível mais grosseiro, você irá descobrir que enquanto há muitas áreas nas quais o “eu” e “meu” conduzem apenas a conflitos inúteis, há muitas outras nas quais eles podem ser benéficos. A noção de “eu” que faz com que você seja generoso e íntegro nas suas ações é um “eu” que vale a pena ser fabricado, digno de ser dominado como uma técnica. Assim também é a noção de “eu” que pode assumir a responsabilidade pelas suas ações e que está disposta a sacrificar um pequeno prazer no presente por uma felicidade maior no futuro. Esse tipo de “eu,”com a prática, irá afastá-lo da aflição e conduzi-lo a níveis crescentes de felicidade. Esse é o “eu” que em algum momento o levará a praticar a meditação, pois você vê os benefícios a longo prazo, que provêm do treinamento do seu poder de atenção plena, concentração e sabedoria. </p>

<p class=Normal>No entanto, enquanto a meditação refina a sua sensibilidade, você começa a notar os níveis sutis de aflição e perturbação que a fabricação de um eu e a fabricação do meu são capazes de criar na mente. Eles podem fazer com que você se apegue a um estado de tranqüilidade, de tal modo que você ressinta quaisquer intrusões na “minha” tranqüilidade. Eles podem fazer com que você se apegue aos seus insights, de tal modo que você desenvolva orgulho pelos “meus” insights. Isso pode ser um obstáculo para o progresso, pois a noção de “eu” e “meu” podem impedi-lo de ver o sofrimento sutil sobre o qual estão baseadas a tranqüilidade e o insight. No entanto, se você se tivesse treinado nas instruções para Rahula, você  valorizaria as vantagens de aprender a ver até mesmo a tranqüilidade e insight como vazios de qualquer coisa que pertença ao eu. Essa é a essência do segundo tipo de vacuidade. Quando você remove os rótulos de “eu” ou “meu” até mesmo dos seus próprios insights e estados mentais, como você os vê? Simplesmente como ocorrências de sofrimento surgindo e desaparecendo – perturbações surgindo e desaparecendo – sem adicionar ou eliminar nada. À medida que você prosseguir com essa forma de percepção, você estará adotando o primeiro tipo de vacuidade, como um método de meditação. </p>

<p class=Normal><b>A Vacuidade como um Estado de Concentração</b></p>

<p class=Normal>O terceiro tipo de vacuidade ensinada pelo Buda – como um estado de concentração – é em essência uma outra forma de empregar o insight da vacuidade como um atributo dos sentidos e dos seus objetos como um meio para alcançar a libertação. Um discurso (<a href="../sutta/MN43.php">MN 43</a>) descreve isso da seguinte forma: um bhikkhu senta para meditar num local tranqüilo e de forma intencional percebe os seis sentidos e os seus objetos como vazios de um eu ou daquilo que pertença a um eu. Enquanto ele se dedica a essa percepção, isso não traz a mente diretamente para a libertação, mas para o jhana imaterial da base do nada, que é acompanhado por forte equanimidade. </p>

<p class=Normal>Um outro discurso (<a href="../sutta/MN106.php">MN 106</a>) desenvolve ainda mais esse tema, observando que o bhikkhu desfruta da equanimidade. Se ele permanecer só desfrutando dela, a sua meditação não irá adiante. Mas se ele aprender a ver aquela equanimidade como uma ação – fabricada, produto da vontade – ele poderá identificar o sofrimento sutil que isso implica. Se ele puder observar esse sofrimento em si mesmo, surgindo e cessando, sem adicionar ou eliminar nenhuma outra percepção, ele estará novamente adotando a vacuidade como um método de meditação. Abandonando as causas de sofrimento onde quer que elas sejam encontradas na concentração, ele por fim alcançará a forma mais elevada de vacuidade, livre de todas as fabricações mentais. </p>

<p class=Normal><b>A Sabedoria da Vacuidade</b></p>

<p class=Normal>Portanto, os dois últimos tipos de vacuidade por fim acabam conduzindo de volta ao primeiro, a vacuidade como um método de meditação – o que significa que os três tipos de vacuidade acabam no final das contas conduzindo ao mesmo destino. Quer o tipo de vacuidade seja interpretado com o significado de vazio de perturbações, (sofrimento), ou vazio de um eu, quer estimule o insight através da tranqüilidade ou a tranqüilidade através do insight, todos eles culminam numa prática que preenche as tarefas apropriadas a cada uma das quatro nobres verdades: <i>compreender</i> o sofrimento, <i>abandonar</i> as suas causas, <i>realizar</i> a cessação e <i>desenvolver</i> o caminho para essa cessação. O cumprimento dessas tarefas conduz à libertação. </p>

<p class=Normal>O que é distinto neste processo é o modo como ele evolui dos princípios da ação-purificação que o Buda ensinou para Rahula, aplicando esses princípios a cada passo da prática do mais elementar ao mais refinado. Como disse o Buda para Rahula, esses princípios são o único meio possível através do qual a purificação pode ser alcançada. Embora a maioria das explicações deste enunciado definam a purificação como  pureza de virtude, a explicação do Buda sobre a vacuidade, como um método de meditação, mostra que a purificação neste caso também significa a pureza da mente e a pureza da sabedoria. Todos os aspectos do treinamento são purificados ao vê-los como ações e suas conseqüências. Isso ajuda a desenvolver a integridade que está disposta a reconhecer as ações inábeis e a boa vontade madura que permanece objetivando conseqüências que impliquem cada vez menos em dano, perturbação e sofrimento. </p>

<p class=Normal>É nisso que este tipo de vacuidade difere da definição metafísica de vacuidade como sendo a “ausência de existência inerente.” Enquanto a perspectiva metafísica da vacuidade não necessariamente envolve integridade - visto que é uma tentativa de descrever a realidade última da natureza das coisas e não de julgar ações – esta abordagem da vacuidade requer um julgamento honesto das suas ações mentais e dos seus resultados. A integridade é dessa maneira parte essencial dessa habilidade. </p>

<p class=Normal>Desse modo, os níveis mais elevados de discernimento e sabedoria evoluem não do tipo de conhecimento fomentado pelos debates e pela análise lógica, nem do tipo fomentado pela pura atenção ou a mera notação, mas do conhecimento fomentado pela integridade, desprovido de presunção, unido à compaixão e boa vontade. </p>

<p class=Normal>A razão disso é tão óbvia que com freqüência passa despercebido: se você quer dar um fim ao sofrimento, precisa da compaixão para ver que esse é um objetivo que vale a pena e da integridade para reconhecer o sofrimento que você causou  no passado desnecessariamente e por negligência. A ignorância, que faz surgir o sofrimento, ocorre não porque você não tem conhecimentos suficientes ou não é sofisticado filosoficamente o suficiente para entender o verdadeiro significado da vacuidade. Ela provém da sua recusa em admitir que o que você está claramente fazendo, diante dos seus próprios olhos, está causando sofrimento. É por isso que a iluminação destrói a presunção: ela o desperta completamente da cegueira deliberada que o manteve por todo o tempo cúmplice dum comportamento inábil. Essa é uma experiência purificadora. A única coisa honesta a ser feita em resposta a essa experiência é abrir-se para a libertação. Essa é a vacuidade que é superior e insuperável. </p>

<p class=Normal>Ao formular o caminho para essa vacuidade sobre os mesmos princípios que suportam os níveis mais elementares da ação-purificação, o Buda conseguiu evitar a criação de dicotomias artificiais entre a realidade convencional e a realidade última, na prática. Por essa razão, esta abordagem para a sabedoria última ajuda também a validar os níveis mais elementares. Quando você entender, que a compreensão não distorcida da vacuidade depende de habilidades que são desenvolvidas com a adoção de uma atitude responsável, honesta e gentil em relação a todas as suas ações, é mais provável que você trará essa atitude para tudo aquilo que você fizer – grosseiro ou sutil. Você dará mais importância a todas as suas ações e às suas conseqüências, você dará mais importância à sua noção de integridade, pois você compreende que essas coisas estão diretamente relacionadas com as habilidades que conduzem à completa libertação. Você não pode desenvolver uma atitude descartável em relação às suas ações e respectivas conseqüências, pois você estará jogando fora a sua oportunidade para uma felicidade verdadeira e incondicional. As habilidades que você precisa para se convencer a meditar numa manhã escura e fria, ou para resistir a um trago numa tarde preguiçosa, são as mesmas que no final das contas irão assegurar a realização não distorcida da paz mais elevada. </p>

<p class=Normal>Assim é como os ensinamentos do Buda sobre a vacuidade nos encorajam a exercitar a sabedoria em tudo aquilo que fizermos. </p>


<p class=Normal>&nbsp;</p>

<p class=Normal>&nbsp;</p>



<!-- FIM DO TEXTO -->

<!-- INCLUI BASE -->
<? include("../base.inc"); ?>
